import { name as __pkgName, version as __pkgVersion } from '../package.json' with { type: 'json' }
import { registerSingleton } from '@pyreon/reactivity'

// Singleton sentinel — fail-loud detection of duplicate @pyreon/hooks
// instances in the same heap. See @pyreon/reactivity/singleton-sentinel for
// full rationale. Hardcoded version is acceptable here — it's a diagnostic
// aid, not a load-bearing identity check.
registerSingleton(__pkgName, __pkgVersion, import.meta.url)

export type { BreakpointMap } from './useBreakpoint'
export { useBreakpoint } from './useBreakpoint'
export { useClickOutside } from './useClickOutside'
export type { UseClipboardResult } from './useClipboard'
export { useClipboard } from './useClipboard'
export type {
  HapticImpactStyle,
  HapticNotificationType,
  UseHapticsResult,
} from './useHaptics'
export { useHaptics } from './useHaptics'
export type { UseShareResult } from './useShare'
export { useShare } from './useShare'
export type { UseLinkingResult } from './useLinking'
export { useLinking } from './useLinking'
export type { UseNotificationsResult } from './useNotifications'
export { useNotifications } from './useNotifications'
export { useColorScheme } from './useColorScheme'
export { useSizeClass } from './useSizeClass'
export type { UseControllableState } from './useControllableState'
export { useControllableState } from './useControllableState'
export type { UseCounterOptions, UseCounterResult } from './useCounter'
export { useCounter } from './useCounter'
export type { UseDebouncedCallback } from './useDebouncedCallback'
export { useDebouncedCallback } from './useDebouncedCallback'
export { useDebouncedValue } from './useDebouncedValue'
export type { UseDialogResult } from './useDialog'
export { useDialog } from './useDialog'
export type { DocumentVisibility } from './useDocumentVisibility'
export { useDocumentVisibility } from './useDocumentVisibility'
export type { Size } from './useElementSize'
export { useElementSize } from './useElementSize'
export { useEventListener } from './useEventListener'
export type { UseFetchResult } from './useFetch'
export { useFetch } from './useFetch'
export type { UseFocusResult } from './useFocus'
export { useFocus } from './useFocus'
export type { InitialFocusTarget, UseFocusTrapOptions } from './useFocusTrap'
export { useFocusTrap } from './useFocusTrap'
export { useFocusReturn } from './useFocusReturn'
export type { UseFocusReturnOptions } from './useFocusReturn'
export type { UseHoverResult } from './useHover'
export { useHover } from './useHover'
export type { UseIdleOptions } from './useIdle'
export { useIdle } from './useIdle'
export type { UseInfiniteScrollOptions, UseInfiniteScrollResult } from './useInfiniteScroll'
export { useInfiniteScroll } from './useInfiniteScroll'
export { useIntersection } from './useIntersection'
export type { UseInterval } from './useInterval'
export { useInterval } from './useInterval'
export type { UseIsomorphicLayoutEffect } from './useIsomorphicLayoutEffect'
export { default as useIsomorphicLayoutEffect } from './useIsomorphicLayoutEffect'
export { useKeyboard } from './useKeyboard'
export type { UseLatest } from './useLatest'
export { useLatest } from './useLatest'
export { useMediaQuery } from './useMediaQuery'
export type { UseMergedRef } from './useMergedRef'
export { useMergedRef } from './useMergedRef'
export { useOnline } from './useOnline'
export type { AppStatePhase } from './useAppState'
export { useAppState } from './useAppState'
export { usePrevious } from './usePrevious'
export { useReducedMotion } from './useReducedMotion'
export type { UseRootSize } from './useRootSize'
export { useRootSize } from './useRootSize'
export { useScrollLock } from './useScrollLock'
export type { UseSpacing } from './useSpacing'
export { useSpacing } from './useSpacing'
export type { UseThemeValue } from './useThemeValue'
export { useThemeValue } from './useThemeValue'
export type { UseThrottledCallback } from './useThrottledCallback'
export { useThrottledCallback } from './useThrottledCallback'
export type { UseTimeAgoOptions } from './useTimeAgo'
export { useTimeAgo } from './useTimeAgo'
export type { UseTimeout } from './useTimeout'
export { useTimeout } from './useTimeout'
export type { UseToggleResult } from './useToggle'
export { useToggle } from './useToggle'
export type { UseUpdateEffect } from './useUpdateEffect'
export { useUpdateEffect } from './useUpdateEffect'
export type { WindowSize } from './useWindowResize'
export { useWindowResize } from './useWindowResize'
export type { ScrollPosition, UseWindowScrollResult } from './useWindowScroll'
export { useWindowScroll } from './useWindowScroll'
