// GENERATED by scripts/gen-native-builtin-plugins.ts — do not edit by hand.
// Source of truth: packages/fundamentals/hooks/src/native-plugin.ts (the library owns its lowering).
// Regenerate: bun scripts/gen-native-builtin-plugins.ts   Verify: --check (validate-fast).
// Declaration order is meaningful (Swift lifecycle modifiers emit in registry order).
import type { ServiceSpec } from './plugin'

export const HOOKS_PLUGIN_NAME = '@pyreon/hooks'

export const HOOKS_PLUGIN_MODULES: readonly string[] = ['@pyreon/hooks']

export const HOOKS_SERVICES: Readonly<Record<string, ServiceSpec>> = {
  useShare: {
    legacyKind: 'share',
    swift: 'PyreonShare()',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonShare({id}Ctx) }'],
  },
  useLinking: {
    legacyKind: 'linking',
    swift: 'PyreonLinking()',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonLinking({id}Ctx) }'],
  },
  useHaptics: {
    legacyKind: 'haptics',
    swift: 'PyreonHaptics()',
    kotlin: ['val {id}Haptic = LocalHapticFeedback.current', 'val {id} = remember { PyreonHaptics({id}Haptic) }'],
  },
  useNotifications: {
    legacyKind: 'notifications',
    swift: 'PyreonNotifications()',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonNotifications({id}Ctx) }'],
  },
  useBiometrics: {
    legacyKind: 'biometrics',
    swift: 'PyreonBiometrics()',
    kotlin: ['val {id} = remember { PyreonBiometrics() }'],
  },
  useImagePicker: {
    legacyKind: 'image-picker',
    swift: 'PyreonImagePicker()',
    kotlin: ['val {id} = remember { PyreonImagePicker() }', '{id}.launcher = rememberLauncherForActivityResult(', '    ActivityResultContracts.PickVisualMedia()', '  ) { uri -> {id}.onResult(uri?.toString()) }'],
  },
  useFilePicker: {
    legacyKind: 'file-picker',
    swift: 'PyreonFilePicker()',
    kotlin: ['val {id} = remember { PyreonFilePicker() }', '{id}.launcher = rememberLauncherForActivityResult(', '    ActivityResultContracts.OpenDocument()', '  ) { uri -> {id}.onResult(uri?.toString()) }'],
  },
  useCamera: {
    legacyKind: 'camera',
    swift: 'PyreonCamera(presenter: UIKitCameraPresenter())',
    kotlin: ['val {id} = remember { PyreonCamera() }', '{id}.launch = rememberCameraLauncher { uri -> {id}.onResult(uri) }'],
  },
  useClipboard: {
    legacyKind: 'clipboard',
    swift: 'PyreonClipboard()',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id}Scope = rememberCoroutineScope()', 'val {id} = remember { PyreonClipboard({id}Ctx, {id}Scope) }'],
    accessorReads: ['copied', 'text'],
    destructure: true,
  },
  useBluetooth: {
    legacyKind: 'bluetooth',
    swift: 'PyreonBluetooth(scanner: CoreBluetoothScanner())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonBluetooth(AndroidBluetoothScanner({id}Ctx)) }'],
    accessorReads: ['scanning', 'devices', 'error', 'available'],
    kotlinState: ['scanning', 'devices', 'error'],
  },
  useWakeLock: {
    legacyKind: 'wake-lock',
    swift: 'PyreonWakeLock(controller: UIKitIdleTimer())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonWakeLock(AndroidScreenKeeper({id}Ctx)) }'],
    accessorReads: ['active', 'supported'],
    kotlinState: ['active'],
  },
  useDeviceInfo: {
    legacyKind: 'device-info',
    swift: 'PyreonDeviceInfo(probe: UIKitDeviceProbe())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonDeviceInfo(AndroidDeviceProbe({id}Ctx)) }'],
    accessorReads: ['platform', 'model', 'osVersion', 'isTouch', 'screen'],
  },
  useSafeArea: {
    legacyKind: 'safe-area',
    swift: 'PyreonSafeArea(probe: UIKitSafeAreaProbe())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonSafeArea(AndroidSafeAreaProbe({id}Ctx)) }'],
    callRead: 'insets',
  },
  useScreenOrientation: {
    legacyKind: 'screen-orientation',
    swift: 'PyreonScreenOrientation(probe: UIKitOrientationProbe())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonScreenOrientation(AndroidOrientationProbe({id}Ctx)) }'],
    accessorReads: ['type', 'angle'],
  },
  useDeviceMotion: {
    legacyKind: 'device-motion',
    swift: 'PyreonDeviceMotion(source: CoreMotionSource())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonDeviceMotion(AndroidMotionSource({id}Ctx)) }'],
    accessorReads: ['active', 'supported', 'acceleration', 'rotation'],
    kotlinState: ['active', 'acceleration', 'rotation'],
  },
  useSpeech: {
    legacyKind: 'speech',
    swift: 'PyreonSpeech(synth: AVSpeechSynth())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonSpeech(AndroidSpeechSynth({id}Ctx)) }'],
    accessorReads: ['speaking', 'supported'],
    kotlinState: ['speaking'],
  },
  useAudioRecorder: {
    legacyKind: 'audio-recorder',
    swift: 'PyreonAudioRecorder(engine: AVFoundationRecordingEngine())',
    kotlin: ['val {id}Ctx = LocalContext.current', 'val {id} = remember { PyreonAudioRecorder(AndroidRecordingEngine({id}Ctx)) }'],
    accessorReads: ['recording', 'error', 'supported'],
    kotlinState: ['recording', 'error'],
  },
  useOnline: {
    legacyKind: 'network-status',
    swift: 'PyreonNetworkStatus()',
    kotlin: ['val {id} = rememberPyreonNetworkStatus()'],
    callRead: 'isOnline',
    kotlinState: ['isOnline'],
    lifecycle: 'start-stop',
    destructure: true,
  },
  usePush: {
    legacyKind: 'push',
    swift: 'PyreonPushNotifications()',
    kotlin: ['val {id} = rememberPyreonPushNotifications()'],
    kotlinState: ['token', 'lastNotification', 'notifications', 'isAuthorized', 'error'],
    lifecycle: 'start-stop',
    destructure: true,
    optionalFields: { error: { kind: 'typeRef', name: 'Error', args: [] } },
  },
  useAppState: {
    legacyKind: 'app-state',
    swift: 'PyreonAppState()',
    kotlin: ['val {id} = rememberPyreonAppState()'],
    callRead: 'phase',
    kotlinState: ['phase', 'wasBackgrounded'],
    lifecycle: 'start-stop',
    destructure: true,
  },
  useCrashReporter: {
    legacyKind: 'crash-reporter',
    swift: 'PyreonCrashReporter()',
    kotlin: ['val {id} = rememberPyreonCrashReporter()'],
    kotlinState: ['lastCrash', 'hadCrash'],
    lifecycle: 'start',
    destructure: true,
  },
  useGeolocation: {
    legacyKind: 'geolocation',
    swift: 'PyreonGeolocation()',
    kotlin: ['val {id} = rememberPyreonGeolocation()'],
    kotlinState: ['latitude', 'longitude', 'accuracy', 'isAuthorized', 'error'],
    destructure: true,
    optionalFields: { latitude: { kind: 'number' }, longitude: { kind: 'number' }, accuracy: { kind: 'number' }, error: { kind: 'typeRef', name: 'Error', args: [] } },
  },
  usePayments: {
    legacyKind: 'payments',
    swift: 'PyreonPayments()',
    kotlin: ['val {id} = remember { PyreonPayments() }'],
    kotlinState: ['products', 'ownedProductIds', 'purchasing', 'error'],
    destructure: true,
    optionalFields: { purchasing: { kind: 'string' }, error: { kind: 'typeRef', name: 'Error', args: [] } },
  },
}
