// Token-table emitter — turns a design-system theme IR into per-target
// Swift / Kotlin source. Phase 0 of roadmap PR 7a.
//
// The full @pyreon/ui-theme has complex helpers (breakpoint detection,
// theme augmentation, runtime resolvers). This emitter takes a
// pre-resolved ThemeIR (plain values) and produces the target-language
// constant table that consumer code references as `PyreonTokens.spacing.md`,
// `PyreonTokens.color.primary`, etc.
//
// The TS-source → ThemeIR step (parsing `@pyreon/ui-theme`'s exports)
// lands in a follow-up. For Phase 0 the emitter alone is what matters
// — proves the structural mapping (theme object → Swift struct +
// Kotlin object) before we wire it to real theme files.

export interface ThemeIR {
  /** Top-level groups in the theme (e.g. spacing, color, font). */
  groups: ThemeGroup[]
}

export interface ThemeGroup {
  /** Group name — emitted as a nested struct/object name. Lowercase
   * here; the emitter capitalises for per-target conventions. */
  name: string
  entries: ThemeEntry[]
}

export interface ThemeEntry {
  /** Entry name — emitted as a constant identifier. */
  name: string
  value: ThemeValue
}

export type ThemeValue =
  | { kind: 'number'; value: number }
  | { kind: 'string'; value: string }
  | { kind: 'cgfloat'; value: number }   // Swift's CGFloat — visible distinction at emit
  | { kind: 'dp'; value: number }        // Kotlin's dp — visible distinction at emit

/**
 * Emit `PyreonTokens.swift` from a ThemeIR.
 *
 *   struct PyreonTokens {
 *     struct Spacing {
 *       static let xs: CGFloat = 4
 *       static let sm: CGFloat = 8
 *     }
 *     struct Color {
 *       static let primary: String = "#0066FF"
 *     }
 *   }
 */
export function emitSwiftTokens(theme: ThemeIR): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @pyreon/native-compiler — do not edit.')
  lines.push('import SwiftUI')
  lines.push('')
  lines.push('public enum PyreonTokens {')
  for (const group of theme.groups) {
    lines.push(`  public enum ${capitalize(group.name)} {`)
    for (const entry of group.entries) {
      lines.push(`    public static let ${entry.name}: ${swiftValueType(entry.value)} = ${swiftValueLiteral(entry.value)}`)
    }
    lines.push(`  }`)
  }
  lines.push('}')
  return lines.join('\n')
}

/**
 * Emit `PyreonTokens.kt` from a ThemeIR.
 *
 *   object PyreonTokens {
 *     object Spacing {
 *       val xs = 4.dp
 *       val sm = 8.dp
 *     }
 *     object Color {
 *       val primary = "#0066FF"
 *     }
 *   }
 */
export function emitKotlinTokens(theme: ThemeIR): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @pyreon/native-compiler — do not edit.')
  lines.push('import androidx.compose.ui.unit.dp')
  lines.push('')
  lines.push('object PyreonTokens {')
  for (const group of theme.groups) {
    lines.push(`  object ${capitalize(group.name)} {`)
    for (const entry of group.entries) {
      lines.push(`    val ${entry.name} = ${kotlinValueLiteral(entry.value)}`)
    }
    lines.push(`  }`)
  }
  lines.push('}')
  return lines.join('\n')
}

function swiftValueType(v: ThemeValue): string {
  switch (v.kind) {
    case 'number':
      return 'Int'
    case 'string':
      return 'String'
    case 'cgfloat':
      return 'CGFloat'
    case 'dp':
      // Kotlin's `dp` doesn't exist in Swift — degrade to CGFloat (the
      // equivalent geometric primitive).
      return 'CGFloat'
  }
}

function swiftValueLiteral(v: ThemeValue): string {
  switch (v.kind) {
    case 'number':
      return String(v.value)
    case 'string':
      return JSON.stringify(v.value)
    case 'cgfloat':
      return String(v.value)
    case 'dp':
      return String(v.value)
  }
}

function kotlinValueLiteral(v: ThemeValue): string {
  switch (v.kind) {
    case 'number':
      return String(v.value)
    case 'string':
      return JSON.stringify(v.value)
    case 'cgfloat':
      // Swift's CGFloat doesn't have a Kotlin equivalent in Compose;
      // emit as a plain Float-ish value. Compose's `dp` is the typical
      // target for spacing; the dp kind below covers that explicitly.
      return String(v.value)
    case 'dp':
      return `${v.value}.dp`
  }
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
