/**
 * Atlas core domain model — the framework-agnostic types every other module
 * (auto, graph, verify, ai, ui, plugins) reads from.
 *
 * Atlas inverts Storybook's authoring-first model: the components + their
 * types are the source of truth, and Atlas *derives* a verified, machine-
 * readable catalog. These types describe that derived catalog — the "Catalog
 * Graph" — not hand-written story files.
 */

/**
 * A component reference. Kept structural (not imported from `@pyreon/core`) so
 * the core stays dependency-free and buildable in isolation; it is compatible
 * with `@pyreon/core`'s `ComponentFn`. The `runtime` module refines this when
 * it actually mounts a scenario.
 */
export type ComponentRef = (props: Record<string, unknown>) => unknown

/** The kind of arg control Atlas infers for a single component prop. */
export type ControlKind =
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'color'
  | 'reactive'
  | 'unknown'

/** A single inferred arg control (the derived replacement for `argTypes`). */
export interface PropControl {
  /** prop name */
  name: string
  /** how the UI should render an editor for this prop */
  kind: ControlKind
  /** for `select` — the allowed literal values */
  options?: readonly string[]
  /** the component's default for this prop, when known */
  defaultValue?: unknown
  /** true when the prop is a signal accessor (`() => T`) — a reactive input */
  reactive: boolean
  /** true when the prop has no default and is not optional */
  required: boolean
}

/**
 * A dimension axis (e.g. rocketstyle `state` / `size` / `variant`) with its
 * enumerable values. The variant matrix is the cross-product of the axes.
 */
export interface VariantAxis {
  name: string
  values: readonly string[]
}

/**
 * How a scenario came to exist — its provenance in the pipeline.
 *
 * Only values a producer actually emits belong here. Earlier cuts also listed
 * `manifest` / `example` / `csf` / `ai` — aspiration encoded as a union, the
 * typed-but-unimplemented class. A new source enters this union in the same
 * change that ships its producer.
 */
export type ScenarioSource = 'auto-default' | 'auto-variant' | 'authored'

/**
 * A named, concrete state of a component — the derived replacement for a
 * Storybook "story". Auto-generated by default; AI- or human-authored only to
 * enrich. A scenario that fails verification stays in the catalog but is
 * labeled `[FAIL]` on every surface (JSON, llms text, agent guide), so a
 * consumer can never mistake it for a verified state.
 */
export interface Scenario {
  /** stable slug, unique within the catalog */
  id: string
  /** owning component name */
  component: string
  /** human-facing label */
  name: string
  /** the props this scenario mounts with */
  args: Record<string, unknown>
  /** which variant-axis value each pinned axis is set to (subset of the matrix) */
  variant?: Record<string, string>
  /** provenance */
  source: ScenarioSource
  /**
   * The URL this scenario renders under, when a route axis is in play.
   *
   * Scenario METADATA rather than an arg: it is not a prop, and putting it in
   * `args` would render it as a control the component does not have and let a
   * user "edit" something with no effect.
   */
  route?: string
  /** authored interaction script — replaces the automatic click-walk when set */
  play?: PlayFn
  /** the verify verdict, once the pipeline has run */
  verify?: VerifyVerdict
}

/**
 * What an authored `play` receives: the MOUNTED scenario's root plus a `step`
 * that names each phase — a failure is reported by the step it died in, which
 * is the difference between "play failed" and a fixable finding.
 */
export interface PlayContext {
  /** The container the scenario mounted into — query it like a user's test would. */
  root: Element
  step(name: string, run: () => void | Promise<void>): Promise<void>
}

/**
 * An authored interaction script. When present, verification RUNS it instead
 * of the automatic click-walk — the author has said what "exercised" means for
 * this scenario. A throw (an assertion, a missing element) fails the
 * `interaction` check, naming the step.
 */
export type PlayFn = (ctx: PlayContext) => void | Promise<void>

/** The status of one verify check. */
export type CheckStatus = 'pass' | 'fail' | 'skip'

/**
 * A stable identifier for a CLASS of verify outcome.
 *
 * Prose is what a person reads; a code is what a tool can act on. Without one,
 * an agent handed `"hydrateRoot threw: Cannot read properties of undefined"`
 * can only pattern-match on a sentence that is free to be reworded — so the
 * catalog could say what was wrong and never say what KIND of wrong it was.
 *
 * Grouped by the check that emits it. Codes are permanent once shipped: a
 * consumer branching on `hydrate-threw` must keep working, so a reworded
 * message is a patch and a renamed code is a breaking change.
 *
 * Mirrors `UsageFinding.kind`, which already applies this shape to the usage
 * validator — one convention for "what kind of problem is this".
 */
export type FindingCode =
  // ── interaction ──────────────────────────────────────────────────────────
  /** The component threw while mounted, or during the click-walk. */
  | 'mount-threw'
  /** An authored `play` script failed, naming the step it died in. */
  | 'play-failed'
  /** Nothing interactive to drive — a pass, stated so it is not read as one. */
  | 'nothing-to-drive'
  // ── ssrParity ────────────────────────────────────────────────────────────
  | 'ssr-render-threw'
  | 'hydrate-threw'
  /** The runtime itself reported a hydration mismatch. */
  | 'hydration-mismatch'
  /** Hydrated DOM differs from a fresh client mount — the second oracle. */
  | 'hydrated-dom-differs'
  // ── a11y ─────────────────────────────────────────────────────────────────
  | 'missing-accessible-name'
  // ── leak ─────────────────────────────────────────────────────────────────
  | 'reactive-nodes-retained'
  // ── browser-measured ─────────────────────────────────────────────────────
  | 'coverage-measured'
  | 'coverage-errored'
  | 'snapshot-differs'
  | 'snapshot-failed'
  | 'baseline-created'
  | 'baseline-updated'
  // ── reasons a check did not run ──────────────────────────────────────────
  /** Measurable only in a real browser. */
  | 'browser-only'
  /** No plugin claimed this check. */
  | 'not-run'
  /** No DOM could be created to mount into. */
  | 'no-dom'
  /** The leak check needs a GC hook (`bun`, or `node --expose-gc`). */
  | 'no-gc-hook'
  /** `@pyreon/runtime-server` is not resolvable, so parity cannot be checked. */
  | 'no-ssr-renderer'
  /** Nothing statically nameable to check. */
  | 'nothing-to-check'

/**
 * One thing a check found.
 *
 * `message` states what is wrong; `fix` states what to change, and travels WITH
 * the finding rather than living in a lookup table a consumer has to know to
 * consult. A finding that cannot name a single concrete next step omits `fix`
 * rather than inventing one — a confident wrong instruction costs more than
 * none, the same rule the name suggester applies.
 */
export interface VerifyFinding {
  code: FindingCode
  /** Human/agent-readable statement of what happened. */
  message: string
  /** The one concrete thing to change, when there is one. */
  fix?: string
}

export interface VerifyCheck {
  status: CheckStatus
  /**
   * What this check found, when it is not a clean pass.
   *
   * Structured rather than plain strings (catalog `version: 2`): every
   * consumer that wants to branch on a failure CLASS — an agent deciding what
   * to change, a CI step filtering, a ratchet comparing runs — was previously
   * reduced to matching on a prose sentence.
   */
  findings?: readonly VerifyFinding[]
}

/** A finding, as a one-liner so producers stay readable. */
export function finding(code: FindingCode, message: string, fix?: string): VerifyFinding {
  return fix === undefined ? { code, message } : { code, message, fix }
}

/**
 * The outcome of the verify pipeline for one scenario.
 *
 * `ok` means VERIFIED: at least one check actually ran, and none failed.
 *
 * The distinction is load-bearing and used to be missing. `ok` was "no check
 * failed", and `emptyVerdict()` starts every check at `skip` — so a scenario
 * nothing had examined was `ok: true`, indistinguishable from one that passed
 * every gate. Two of the five checks (`reactivityCoverage`, `snapshot`) are
 * still unimplemented stubs — `a11y` (static name check), `interaction`
 * (real mount) and `leak` (reactive-graph accumulation past GC) run today —
 * so unverified remains a real state: without `checked` the catalog printed
 * `[pass]` and the agent guide offered "correct:" examples on the strength of
 * checks that never ran.
 *
 * Telling an agent something is verified when it was not is worse than saying
 * nothing — it is the same false-green class as a doctor gate that reports 100
 * after scanning zero files. `checked` keeps the two states separable for every
 * consumer, so a renderer never has to infer "did anything happen?" from `ok`.
 */
export interface VerifyVerdict {
  /** verified: `checked > 0` AND no check failed. */
  ok: boolean
  /** how many checks actually ran (non-skip). `0` means UNVERIFIED, not clean. */
  checked: number
  a11y: VerifyCheck
  interaction: VerifyCheck
  reactivityCoverage: VerifyCheck
  leak: VerifyCheck
  snapshot: VerifyCheck
  /**
   * Does this scenario survive `renderToString` + hydrate?
   *
   * Its own check rather than a facet of `interaction`, because it fails for
   * reasons interaction cannot see: a mismatch corrupts the DOM at hydration
   * time, before any interaction happens, and a component that mounts
   * perfectly on the client can still be unusable in an SSR app.
   */
  ssrParity: VerifyCheck
}

/**
 * Every check a verdict carries — the SINGLE owner of that list.
 *
 * Lives beside `VerifyVerdict` because it enumerates exactly its check fields,
 * and every layer above needs it: the registry merges by it, the CLI report
 * tallies by it, and the catalog renderer collects findings by it. A second
 * hand-written list is a silent-hole generator, and this one is not
 * hypothetical — the catalog renderer carried a five-entry copy that was never
 * updated when `ssrParity` landed, so hydration failures were recorded and then
 * dropped from the agent guide. Anything that iterates checks imports this.
 */
export const CHECK_KEYS = [
  'a11y',
  'interaction',
  'reactivityCoverage',
  'leak',
  'snapshot',
  'ssrParity',
] as const

/** One check's name. Derived from the list, so the two can never disagree. */
export type CheckKey = (typeof CHECK_KEYS)[number]

/** Everything Atlas derives about one component. */
export interface ComponentIntelligence {
  /**
   * The component's REAL, importable identifier.
   *
   * Not its identity in a monorepo — see `project` and `componentKey`. Two
   * packages may legitimately both export a `Button`, and both are called
   * `Button` in the code that imports them.
   */
  name: string
  /**
   * Owning project root, set only by a MULTI-ROOT (monorepo) scan.
   *
   * Absent for a single-package scan, which keeps every derived key byte-
   * identical to what it was before multi-root existed.
   */
  project?: string
  /** the component itself, when available (optional so the graph is buildable from metadata alone) */
  component?: ComponentRef
  controls: readonly PropControl[]
  axes: readonly VariantAxis[]
  scenarios: readonly Scenario[]
  tags: readonly string[]
  /** source file path, when known */
  source?: string
  /**
   * What this component's OWN source costs a consumer, minified + gzipped.
   *
   * Present only when `bundleCostPlugin` ran — it is opt-in, because each
   * measurement is a real bundler run. Workspace packages and bare deps are
   * external, so this compares components against each other; it is not the
   * page weight of rendering one.
   */
  bundleCost?: { raw: number; gzip: number }
  /** a one-line summary (from a manifest or generated) */
  summary?: string
}

/** The serialized whole-catalog shape — the machine surface agents consume. */
export interface CatalogGraphData {
  /**
   * Catalog schema version.
   *
   * Bumped 1 → 2 when `VerifyCheck.findings` became structured
   * (`{ code, message, fix? }`) instead of plain strings. A consumer reading a
   * v1 catalog would silently render `[object Object]` for every finding, so
   * the version is the thing that lets it refuse instead.
   */
  version: 2
  components: readonly ComponentIntelligence[]
}
