/**
 * Atlas core domain model — the framework-agnostic types every other module
 * (auto, graph, verify, ai, ui, plugins) reads from.
 *
 * Atlas inverts Storybook's authoring-first model: the components + their
 * types are the source of truth, and Atlas *derives* a verified, machine-
 * readable catalog. These types describe that derived catalog — the "Catalog
 * Graph" — not hand-written story files.
 */

/**
 * A component reference. Kept structural (not imported from `@pyreon/core`) so
 * the core stays dependency-free and buildable in isolation; it is compatible
 * with `@pyreon/core`'s `ComponentFn`. The `runtime` module refines this when
 * it actually mounts a scenario.
 */
export type ComponentRef = (props: Record<string, unknown>) => unknown

/** The kind of arg control Atlas infers for a single component prop. */
export type ControlKind =
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'color'
  | 'reactive'
  | 'unknown'

/** A single inferred arg control (the derived replacement for `argTypes`). */
export interface PropControl {
  /** prop name */
  name: string
  /** how the UI should render an editor for this prop */
  kind: ControlKind
  /** for `select` — the allowed literal values */
  options?: readonly string[]
  /** the component's default for this prop, when known */
  defaultValue?: unknown
  /** true when the prop is a signal accessor (`() => T`) — a reactive input */
  reactive: boolean
  /** true when the prop has no default and is not optional */
  required: boolean
}

/**
 * A dimension axis (e.g. rocketstyle `state` / `size` / `variant`) with its
 * enumerable values. The variant matrix is the cross-product of the axes.
 */
export interface VariantAxis {
  name: string
  values: readonly string[]
}

/**
 * How a scenario came to exist — its provenance in the pipeline.
 *
 * Only values a producer actually emits belong here. Earlier cuts also listed
 * `manifest` / `example` / `csf` / `ai` — aspiration encoded as a union, the
 * typed-but-unimplemented class. A new source enters this union in the same
 * change that ships its producer.
 */
export type ScenarioSource = 'auto-default' | 'auto-variant' | 'authored'

/**
 * A named, concrete state of a component — the derived replacement for a
 * Storybook "story". Auto-generated by default; AI- or human-authored only to
 * enrich. A scenario that fails verification stays in the catalog but is
 * labeled `[FAIL]` on every surface (JSON, llms text, agent guide), so a
 * consumer can never mistake it for a verified state.
 */
export interface Scenario {
  /** stable slug, unique within the catalog */
  id: string
  /** owning component name */
  component: string
  /** human-facing label */
  name: string
  /** the props this scenario mounts with */
  args: Record<string, unknown>
  /** which variant-axis value each pinned axis is set to (subset of the matrix) */
  variant?: Record<string, string>
  /** provenance */
  source: ScenarioSource
  /** the verify verdict, once the pipeline has run */
  verify?: VerifyVerdict
}

/** The status of one verify check. */
export type CheckStatus = 'pass' | 'fail' | 'skip'

export interface VerifyCheck {
  status: CheckStatus
  /** human/agent-readable findings when not a clean pass */
  findings?: readonly string[]
}

/**
 * The outcome of the verify pipeline for one scenario.
 *
 * `ok` means VERIFIED: at least one check actually ran, and none failed.
 *
 * The distinction is load-bearing and used to be missing. `ok` was "no check
 * failed", and `emptyVerdict()` starts every check at `skip` — so a scenario
 * nothing had examined was `ok: true`, indistinguishable from one that passed
 * every gate. Two of the five checks (`reactivityCoverage`, `snapshot`) are
 * still unimplemented stubs — `a11y` (static name check), `interaction`
 * (real mount) and `leak` (reactive-graph accumulation past GC) run today —
 * so unverified remains a real state: without `checked` the catalog printed
 * `[pass]` and the agent guide offered "correct:" examples on the strength of
 * checks that never ran.
 *
 * Telling an agent something is verified when it was not is worse than saying
 * nothing — it is the same false-green class as a doctor gate that reports 100
 * after scanning zero files. `checked` keeps the two states separable for every
 * consumer, so a renderer never has to infer "did anything happen?" from `ok`.
 */
export interface VerifyVerdict {
  /** verified: `checked > 0` AND no check failed. */
  ok: boolean
  /** how many checks actually ran (non-skip). `0` means UNVERIFIED, not clean. */
  checked: number
  a11y: VerifyCheck
  interaction: VerifyCheck
  reactivityCoverage: VerifyCheck
  leak: VerifyCheck
  snapshot: VerifyCheck
}

/** Everything Atlas derives about one component. */
export interface ComponentIntelligence {
  name: string
  /** the component itself, when available (optional so the graph is buildable from metadata alone) */
  component?: ComponentRef
  controls: readonly PropControl[]
  axes: readonly VariantAxis[]
  scenarios: readonly Scenario[]
  tags: readonly string[]
  /** source file path, when known */
  source?: string
  /** a one-line summary (from a manifest or generated) */
  summary?: string
}

/** The serialized whole-catalog shape — the machine surface agents consume. */
export interface CatalogGraphData {
  version: 1
  components: readonly ComponentIntelligence[]
}
