/**
 * Atlas core domain model — the framework-agnostic types every other module
 * (auto, graph, verify, ai, ui, plugins) reads from.
 *
 * Atlas inverts Storybook's authoring-first model: the components + their
 * types are the source of truth, and Atlas *derives* a verified, machine-
 * readable catalog. These types describe that derived catalog — the "Catalog
 * Graph" — not hand-written story files.
 */

/**
 * A component reference. Kept structural (not imported from `@pyreon/core`) so
 * the core stays dependency-free and buildable in isolation; it is compatible
 * with `@pyreon/core`'s `ComponentFn`. The `runtime` module refines this when
 * it actually mounts a scenario.
 */
export type ComponentRef = (props: Record<string, unknown>) => unknown

/** The kind of arg control Atlas infers for a single component prop. */
export type ControlKind =
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'color'
  | 'reactive'
  | 'unknown'

/** A single inferred arg control (the derived replacement for `argTypes`). */
export interface PropControl {
  /** prop name */
  name: string
  /** how the UI should render an editor for this prop */
  kind: ControlKind
  /** for `select` — the allowed literal values */
  options?: readonly string[]
  /** the component's default for this prop, when known */
  defaultValue?: unknown
  /** true when the prop is a signal accessor (`() => T`) — a reactive input */
  reactive: boolean
  /** true when the prop has no default and is not optional */
  required: boolean
}

/**
 * A dimension axis (e.g. rocketstyle `state` / `size` / `variant`) with its
 * enumerable values. The variant matrix is the cross-product of the axes.
 */
export interface VariantAxis {
  name: string
  values: readonly string[]
}

/** How a scenario came to exist — its provenance in the pipeline. */
export type ScenarioSource =
  | 'auto-default'
  | 'auto-variant'
  | 'manifest'
  | 'example'
  | 'csf'
  | 'ai'
  | 'authored'

/**
 * A named, concrete state of a component — the derived replacement for a
 * Storybook "story". Auto-generated by default; AI- or human-authored only to
 * enrich. A scenario that does not verify never enters the published catalog.
 */
export interface Scenario {
  /** stable slug, unique within the catalog */
  id: string
  /** owning component name */
  component: string
  /** human-facing label */
  name: string
  /** the props this scenario mounts with */
  args: Record<string, unknown>
  /** which variant-axis value each pinned axis is set to (subset of the matrix) */
  variant?: Record<string, string>
  /** provenance */
  source: ScenarioSource
  /** the verify verdict, once the pipeline has run */
  verify?: VerifyVerdict
}

/**
 * Per-binding reactivity verdict, mirrored from the compiler's Reactivity Lens
 * (`analyzeReactivity`). The `verify`/`auto` modules populate this; the core
 * only models it.
 */
export type ReactivityKind = 'live' | 'static' | 'live-prop' | 'live-attr' | 'hoisted'

export interface ReactivityBinding {
  /** the source expression the verdict is about */
  expr: string
  kind: ReactivityKind
  /** 1-indexed source line, when known */
  line?: number
}

/** The status of one verify check. */
export type CheckStatus = 'pass' | 'fail' | 'skip'

export interface VerifyCheck {
  status: CheckStatus
  /** human/agent-readable findings when not a clean pass */
  findings?: readonly string[]
}

/**
 * The outcome of the verify pipeline for one scenario. `ok` is the AND of every
 * non-skipped check — a scenario is only trustworthy (for humans and agents)
 * when it passes.
 */
export interface VerifyVerdict {
  ok: boolean
  a11y: VerifyCheck
  interaction: VerifyCheck
  reactivityCoverage: VerifyCheck
  leak: VerifyCheck
  snapshot: VerifyCheck
}

/** Everything Atlas derives about one component. */
export interface ComponentIntelligence {
  name: string
  /** the component itself, when available (optional so the graph is buildable from metadata alone) */
  component?: ComponentRef
  controls: readonly PropControl[]
  axes: readonly VariantAxis[]
  reactivity: readonly ReactivityBinding[]
  scenarios: readonly Scenario[]
  tags: readonly string[]
  /** source file path, when known */
  source?: string
  /** a one-line summary (from a manifest or generated) */
  summary?: string
}

/** The serialized whole-catalog shape — the machine surface agents consume. */
export interface CatalogGraphData {
  version: 1
  components: readonly ComponentIntelligence[]
}
