// Generated by docs/scripts/gen-package-catalog.ts. Do not edit.
export const PACKAGE_GROUPS = [
  {
    "category": "core",
    "packages": [
      "@pyreon/compiler",
      "@pyreon/core",
      "@pyreon/head",
      "@pyreon/primitives",
      "@pyreon/reactivity",
      "@pyreon/router",
      "@pyreon/runtime-dom",
      "@pyreon/runtime-server",
      "@pyreon/server",
      "@pyreon/sized-map"
    ]
  },
  {
    "category": "fundamentals",
    "packages": [
      "@pyreon/a11y",
      "@pyreon/charts",
      "@pyreon/code",
      "@pyreon/dnd",
      "@pyreon/document",
      "@pyreon/feature",
      "@pyreon/flow",
      "@pyreon/form",
      "@pyreon/hooks",
      "@pyreon/hotkeys",
      "@pyreon/http",
      "@pyreon/i18n",
      "@pyreon/machine",
      "@pyreon/permissions",
      "@pyreon/query",
      "@pyreon/rich-text",
      "@pyreon/rx",
      "@pyreon/state-tree",
      "@pyreon/storage",
      "@pyreon/store",
      "@pyreon/sync",
      "@pyreon/table",
      "@pyreon/toast",
      "@pyreon/url-state",
      "@pyreon/validate",
      "@pyreon/validation",
      "@pyreon/virtual"
    ]
  },
  {
    "category": "native",
    "packages": [
      "@pyreon/native-cli",
      "@pyreon/native-compiler",
      "@pyreon/native-router-kotlin",
      "@pyreon/native-router-swift",
      "@pyreon/native-runtime-kotlin",
      "@pyreon/native-runtime-swift"
    ]
  },
  {
    "category": "tools",
    "packages": [
      "@pyreon/atlas",
      "@pyreon/cli",
      "@pyreon/config",
      "@pyreon/lathe",
      "@pyreon/lint",
      "@pyreon/loom",
      "@pyreon/mcp",
      "@pyreon/preact-compat",
      "@pyreon/react-compat",
      "@pyreon/solid-compat",
      "@pyreon/storybook",
      "@pyreon/svelte-compat",
      "@pyreon/testing",
      "@pyreon/typescript",
      "@pyreon/vite-plugin",
      "@pyreon/vue-compat"
    ]
  },
  {
    "category": "ui-system",
    "packages": [
      "@pyreon/attrs",
      "@pyreon/connector-document",
      "@pyreon/coolgrid",
      "@pyreon/document-primitives",
      "@pyreon/elements",
      "@pyreon/kinetic",
      "@pyreon/kinetic-presets",
      "@pyreon/rocketstyle",
      "@pyreon/styler",
      "@pyreon/ui-core",
      "@pyreon/unistyle"
    ]
  },
  {
    "category": "zero",
    "packages": [
      "@pyreon/create-multiplatform",
      "@pyreon/create-zero",
      "@pyreon/meta",
      "@pyreon/zero",
      "@pyreon/zero-cli",
      "@pyreon/zero-content"
    ]
  }
] as const

export const PACKAGE_COUNT = PACKAGE_GROUPS.reduce((count, group) => count + group.packages.length, 0)
