// GENERATED by docs/scripts/gen-reference.ts — do not edit.
// Auto-generated API-reference sidebar groups (Reference tier). Regenerate
// with `bun docs/scripts/gen-reference.ts`.
import type { SidebarGroup } from './sidebar-config'

export const REFERENCE_GROUPS: SidebarGroup[] = [
  {
    "text": "API Reference — Core & Data",
    "collapsed": true,
    "items": [
      {
        "text": "compiler",
        "slug": "reference/compiler"
      },
      {
        "text": "core",
        "slug": "reference/core"
      },
      {
        "text": "document",
        "slug": "reference/document"
      },
      {
        "text": "feature",
        "slug": "reference/feature"
      },
      {
        "text": "form",
        "slug": "reference/form"
      },
      {
        "text": "hooks",
        "slug": "reference/hooks"
      },
      {
        "text": "hotkeys",
        "slug": "reference/hotkeys"
      },
      {
        "text": "i18n",
        "slug": "reference/i18n"
      },
      {
        "text": "machine",
        "slug": "reference/machine"
      },
      {
        "text": "permissions",
        "slug": "reference/permissions"
      },
      {
        "text": "query",
        "slug": "reference/query"
      },
      {
        "text": "reactivity",
        "slug": "reference/reactivity"
      },
      {
        "text": "rx",
        "slug": "reference/rx"
      },
      {
        "text": "state-tree",
        "slug": "reference/state-tree"
      },
      {
        "text": "storage",
        "slug": "reference/storage"
      },
      {
        "text": "store",
        "slug": "reference/store"
      },
      {
        "text": "sync",
        "slug": "reference/sync"
      },
      {
        "text": "table",
        "slug": "reference/table"
      },
      {
        "text": "url-state",
        "slug": "reference/url-state"
      },
      {
        "text": "validate",
        "slug": "reference/validate"
      },
      {
        "text": "validation",
        "slug": "reference/validation"
      },
      {
        "text": "virtual",
        "slug": "reference/virtual"
      }
    ],
    "tier": "API Reference"
  },
  {
    "text": "API Reference — UI & Browser",
    "collapsed": true,
    "items": [
      {
        "text": "a11y",
        "slug": "reference/a11y"
      },
      {
        "text": "charts",
        "slug": "reference/charts"
      },
      {
        "text": "code",
        "slug": "reference/code"
      },
      {
        "text": "document-primitives",
        "slug": "reference/document-primitives"
      },
      {
        "text": "elements",
        "slug": "reference/elements"
      },
      {
        "text": "flow",
        "slug": "reference/flow"
      },
      {
        "text": "head",
        "slug": "reference/head"
      },
      {
        "text": "primitives",
        "slug": "reference/primitives"
      },
      {
        "text": "rich-text",
        "slug": "reference/rich-text"
      },
      {
        "text": "router",
        "slug": "reference/router"
      },
      {
        "text": "runtime-dom",
        "slug": "reference/runtime-dom"
      },
      {
        "text": "styler",
        "slug": "reference/styler"
      },
      {
        "text": "toast",
        "slug": "reference/toast"
      },
      {
        "text": "ui-core",
        "slug": "reference/ui-core"
      },
      {
        "text": "unistyle",
        "slug": "reference/unistyle"
      }
    ]
  },
  {
    "text": "API Reference — Server & Tooling",
    "collapsed": true,
    "items": [
      {
        "text": "lint",
        "slug": "reference/lint"
      },
      {
        "text": "mcp",
        "slug": "reference/mcp"
      },
      {
        "text": "runtime-server",
        "slug": "reference/runtime-server"
      },
      {
        "text": "server",
        "slug": "reference/server"
      },
      {
        "text": "zero",
        "slug": "reference/zero"
      },
      {
        "text": "zero-content",
        "slug": "reference/zero-content"
      }
    ]
  }
]
