// GENERATED by docs/scripts/gen-troubleshooting.ts — do not edit.
// Regenerate with `bun docs/scripts/gen-troubleshooting.ts`.
import type { SidebarGroup } from './sidebar-config'

export const TROUBLESHOOTING_GROUPS: SidebarGroup[] = [
  {
    "text": "Troubleshooting",
    "tier": "Troubleshooting",
    "collapsed": true,
    "items": [
      {
        "text": "Overview",
        "slug": "troubleshooting"
      },
      {
        "text": "Reactivity Mistakes",
        "slug": "troubleshooting/reactivity"
      },
      {
        "text": "JSX Mistakes",
        "slug": "troubleshooting/jsx"
      },
      {
        "text": "Context & Provider Mistakes",
        "slug": "troubleshooting/context"
      },
      {
        "text": "Architecture Mistakes",
        "slug": "troubleshooting/architecture"
      },
      {
        "text": "Islands Mistakes",
        "slug": "troubleshooting/islands"
      },
      {
        "text": "SSR-rendering Mistakes",
        "slug": "troubleshooting/ssr"
      },
      {
        "text": "SSG / e2e Test-Server Mistakes",
        "slug": "troubleshooting/ssg"
      },
      {
        "text": "Testing Mistakes",
        "slug": "troubleshooting/testing"
      },
      {
        "text": "Lifecycle & Cleanup Mistakes",
        "slug": "troubleshooting/lifecycle"
      },
      {
        "text": "Build Pipeline Mistakes",
        "slug": "troubleshooting/build"
      },
      {
        "text": "CI / Build Gate Mistakes",
        "slug": "troubleshooting/ci"
      },
      {
        "text": "Best-Practice Mistakes (opt-in `@pyreon/lint` rules)",
        "slug": "troubleshooting/best-practices"
      },
      {
        "text": "Library API-Shape Mistakes",
        "slug": "troubleshooting/library-api"
      },
      {
        "text": "Documentation Mistakes",
        "slug": "troubleshooting/documentation"
      }
    ]
  }
]
