[build]
  command = "bun run build"
  publish = "dist"

[functions]
  directory = "dist/.netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false
