// Tests for the token-table emitter (roadmap PR 7a).
//
// Snapshot the Swift + Kotlin output for a representative theme. These
// snapshots LOCK the emit shape — when the structural mapping changes
// intentionally, regenerate via `vitest -u`.

import { describe, expect, it } from 'vitest'
import { emitKotlinTokens, emitSwiftTokens } from '../emit-tokens'
import type { ThemeIR } from '../emit-tokens'

// Canonical fixture theme — covers the three common token kinds:
//   - spacing: dp/CGFloat
//   - color:   hex string
//   - radius:  CGFloat
//
// Real apps will have larger theme objects; the structural mapping
// is the same.
const FIXTURE_THEME: ThemeIR = {
  groups: [
    {
      name: 'spacing',
      entries: [
        { name: 'xs', value: { kind: 'dp', value: 4 } },
        { name: 'sm', value: { kind: 'dp', value: 8 } },
        { name: 'md', value: { kind: 'dp', value: 16 } },
        { name: 'lg', value: { kind: 'dp', value: 24 } },
      ],
    },
    {
      name: 'color',
      entries: [
        { name: 'primary', value: { kind: 'string', value: '#0066FF' } },
        { name: 'background', value: { kind: 'string', value: '#FFFFFF' } },
        { name: 'text', value: { kind: 'string', value: '#1A1A1A' } },
      ],
    },
    {
      name: 'radius',
      entries: [
        { name: 'sm', value: { kind: 'cgfloat', value: 4 } },
        { name: 'md', value: { kind: 'cgfloat', value: 8 } },
      ],
    },
  ],
}

describe('emit-tokens — Swift output', () => {
  it('emits the canonical PyreonTokens struct', () => {
    expect(emitSwiftTokens(FIXTURE_THEME)).toMatchInlineSnapshot(`
      "// Auto-generated by @pyreon/native-compiler — do not edit.
      import SwiftUI

      public enum PyreonTokens {
        public enum Spacing {
          public static let xs: CGFloat = 4
          public static let sm: CGFloat = 8
          public static let md: CGFloat = 16
          public static let lg: CGFloat = 24
        }
        public enum Color {
          public static let primary: String = "#0066FF"
          public static let background: String = "#FFFFFF"
          public static let text: String = "#1A1A1A"
        }
        public enum Radius {
          public static let sm: CGFloat = 4
          public static let md: CGFloat = 8
        }
      }"
    `)
  })
})

describe('emit-tokens — Kotlin output', () => {
  it('emits the canonical PyreonTokens object with dp suffix', () => {
    expect(emitKotlinTokens(FIXTURE_THEME)).toMatchInlineSnapshot(`
      "// Auto-generated by @pyreon/native-compiler — do not edit.
      import androidx.compose.ui.unit.dp

      object PyreonTokens {
        object Spacing {
          val xs = 4.dp
          val sm = 8.dp
          val md = 16.dp
          val lg = 24.dp
        }
        object Color {
          val primary = "#0066FF"
          val background = "#FFFFFF"
          val text = "#1A1A1A"
        }
        object Radius {
          val sm = 4
          val md = 8
        }
      }"
    `)
  })
})

describe('emit-tokens — empty theme', () => {
  it('Swift: empty enum compiles', () => {
    expect(emitSwiftTokens({ groups: [] })).toMatchInlineSnapshot(`
      "// Auto-generated by @pyreon/native-compiler — do not edit.
      import SwiftUI

      public enum PyreonTokens {
      }"
    `)
  })
  it('Kotlin: empty object compiles', () => {
    expect(emitKotlinTokens({ groups: [] })).toMatchInlineSnapshot(`
      "// Auto-generated by @pyreon/native-compiler — do not edit.
      import androidx.compose.ui.unit.dp

      object PyreonTokens {
      }"
    `)
  })
})
