// `@pyreon/flow`'s `createFlow` lowers to the @Observable/`remember`
// PyreonFlowState port. Unlike `createTableState` (which wraps an external
// reactive data source), `createFlow` OWNS its data — nodes/edges are
// captured as LITERAL config at declaration time, so the Swift emit needs
// no `.onAppear` wiring dance (fully self-contained @State initializer,
// closer to `PyreonMachine`'s shape than the table's).
//
// Verified END-TO-END beyond these string assertions: the ACTUAL emit
// type-checks against the real SwiftUI SDK + the real @Observable port on
// macOS (see PyreonFlowState.swift + PyreonFlowStateTests.swift, a real
// executable proving the behavior, not just the types), and both targets
// validate against the compiler stubs here.

import { describe, expect, it } from 'vitest'
import { transform } from '../index'
import {
  isKotlincAvailable,
  isSwiftcAvailable,
  validateKotlin,
  validateSwiftWithStubs,
} from '../validate'

const P = '@pyreon/primitives'
const workflowFlow = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text, Button } from '${P}'
export function WorkflowFlow() {
  const flow = createFlow({
    nodes: [
      { id: '1', position: { x: 0, y: 0 }, data: { label: 'Start' } },
      { id: '2', position: { x: 200, y: 100 }, data: { label: 'End' } },
    ],
    edges: [{ id: 'e1', source: '1', target: '2', animated: true }],
  })
  return (
    <Stack>
      <Text>{flow.nodes().length}</Text>
      <Text>{flow.zoom()}</Text>
      <Button onPress={() => flow.addNode({ id: '3', position: { x: 100, y: 200 }, data: { label: 'New' } })}>Add</Button>
      <Button onPress={() => flow.selectNode('1')}>Select</Button>
      <Text>{flow.selectedNodes().length}</Text>
    </Stack>
  )
}
`

describe('createFlow — Swift lowering', () => {
  const r = transform(workflowFlow, { target: 'swift' })

  it('emits a self-seeding @State PyreonFlowState, row struct synthesized from `data`', () => {
    // The row struct name is the shared `synthLiteralStructName` registry's
    // generated name (`__ObjN`) — the SAME one every OTHER object literal in
    // the file resolves through, which is the point (see the row-type
    // resolution comment in emit-swift.ts): it must be the identical name
    // each node's `data: {...}` literal below ALSO resolves to.
    expect(r.code).toMatch(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)
    const structName = r.code.match(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)?.[1]
    expect(structName).toBeDefined()
    expect(r.code).toContain(`PyreonFlowState<${structName}>(nodes: [`)
    expect(r.code).toContain(
      `PyreonFlowNode(id: "1", position: PyreonXYPosition(x: 0, y: 0), data: ${structName}(label: "Start"))`,
    )
    expect(r.code).toContain(
      `PyreonFlowNode(id: "2", position: PyreonXYPosition(x: 200, y: 100), data: ${structName}(label: "End"))`,
    )
    expect(r.code).toContain('PyreonFlowEdge(id: "e1", source: "1", target: "2", animated: true)')
  })

  it('does NOT wire an .onAppear data source (createFlow owns its data, unlike table)', () => {
    expect(r.code).not.toContain('.onAppear { flow.setData')
  })

  it('nodes()/edges()/viewport()/zoom() drop parens (property reads)', () => {
    expect(r.code).toContain('flow.nodes.count')
    expect(r.code).toContain('"\\(flow.zoom)"')
  })

  it('addNode()/selectNode() stay methods — and addNode\'s object-literal argument resolves to a REAL PyreonFlowNode, not a synthesized lookalike struct', () => {
    // This is the load-bearing assertion for the swiftFlowNodeLiteral
    // rewrite: without it, `addNode({...})`'s literal argument synthesizes
    // its OWN unrelated `__ObjN` struct (same field names as PyreonFlowNode,
    // different NOMINAL type) — Swift's type system is nominal, so that
    // fails to typecheck even though the shapes match. `PyreonFlowNode(` is
    // the discriminator; the generic path would emit a bare `__ObjN(`.
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id: "3", position: PyreonXYPosition\(x: 100, y: 200\), data: __Obj\d+\(label: "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('selectedNodes() stays a method call (matches the web call syntax, no rewrite)', () => {
    expect(r.code).toContain('flow.selectedNodes().count')
  })

  it('the recognizer itself does not decline this shape (no createFlow-specific warning)', () => {
    // NOTE: the package-level blanket "@pyreon/flow is WEB-ONLY" warning
    // still fires here — it is derived from the manifest's `multiplatform`
    // declaration (`WEB_ONLY_PACKAGES`, regenerated by
    // check-multiplatform-tier.ts --write-table), which this PR's compiler
    // work does not yet touch. That is a separate, tracked follow-up (adding
    // a `nativeFrontend` entry to flow's manifest); this test only asserts
    // the RECOGNIZER accepted the shape, which is what it can prove today.
    expect((r.warnings ?? []).some((w) => w.includes('createFlow declaration'))).toBe(false)
  })

  it('the emit type-checks against the Swift stubs', () => {
    const v = validateSwiftWithStubs(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('createFlow — Kotlin lowering', () => {
  const r = transform(workflowFlow, { target: 'kotlin' })

  it('emits a remembered PyreonFlowState with literal node/edge config, Int position literals coerced to Double', () => {
    expect(r.code).toContain('remember { PyreonFlowState<')
    expect(r.code).toContain('nodes = listOf(')
    // Kotlin refuses a bare Int literal where PyreonXYPosition wants Double —
    // `0` must emit as `0.0` (see the ktChartDouble coercion in emit-kotlin.ts).
    expect(r.code).toContain('PyreonFlowNode(id = "1", position = PyreonXYPosition(0.0, 0.0), data = ')
    expect(r.code).toContain('PyreonFlowEdge(id = "e1", source = "1", target = "2", animated = true)')
  })

  it('use-sites: nodes/zoom are property reads (via the TS-compat `.length` extension); addNode resolves a REAL PyreonFlowNode', () => {
    // `.length` (not `.size`) is deliberate — `flow.nodes()` reads as a JS
    // array on web, so the SAME cross-target `.length` extension every other
    // Kotlin-emitted array read uses applies here too (it is `flow.nodes`
    // that drops the parens; `.length` is unrelated to this rewrite).
    expect(r.code).toContain('flow.nodes.length')
    expect(r.code).toContain('${flow.zoom}')
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id = "3", position = PyreonXYPosition\(100\.0, 200\.0\), data = __Obj\d+\(label = "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('the emit type-checks against the Kotlin stubs', () => {
    const v = validateKotlin(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('createFlow — v1 decline shapes (loud warning, not silent drop)', () => {
  it('a non-literal nodes source declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const seed = getSeedNodes()
        const flow = createFlow({ nodes: seed, edges: [] })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })

  it('nodes whose data field sets DIFFER decline (one row struct cannot represent both)', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [
            { id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } },
            { id: '2', position: { x: 0, y: 0 }, data: { count: 1 } },
          ],
          edges: [],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect((r.warnings ?? []).some((w) => w.includes('SAME field set'))).toBe(true)
  })

  it('an edge missing an explicit id declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
          edges: [{ source: '1', target: '2' }],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })

  // `createFlow` takes 17 config keys. The reader took two. The other fifteen
  // lowered to NOTHING and said nothing, so `createFlow({ …, minZoom: 0.5 })`
  // clamped zoom to 2x on web and 4x natively from the same source line —
  // compiles, runs, silently wrong on one target.
  describe('config keys beyond nodes/edges', () => {
    const cfg = (extra: string) => `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
          edges: [],
          ${extra}
        })
        return <Text>{flow.zoom()}</Text>
      }
    `

    it('minZoom/maxZoom THREAD THROUGH — the runtimes always took them', () => {
      const src = cfg('minZoom: 0.5, maxZoom: 2,')
      expect(transform(src, { target: 'swift' }).code).toContain('minZoom: 0.5, maxZoom: 2')
      expect(transform(src, { target: 'kotlin' }).code).toContain('minZoom = 0.5, maxZoom = 2.0')
    })

    it('Kotlin renders them as DOUBLE literals — Int does not widen at a call site', () => {
      // `maxZoom: 2` emitting `maxZoom = 2` is "argument type mismatch: actual
      // type is 'Int', but 'Double' was expected". Swift takes the same source
      // fine, which is how a bug like this stays hidden until a real compile.
      const code = transform(cfg('maxZoom: 2,'), { target: 'kotlin' }).code
      expect(code).toContain('maxZoom = 2.0')
      expect(code).not.toContain('maxZoom = 2)')
    })

    it('an UNLOWERED key warns by NAME on both targets', () => {
      const src = cfg('fitView: true, snapToGrid: true,')
      for (const target of ['swift', 'kotlin'] as const) {
        const w = (transform(src, { target }).warnings ?? []).join(' ')
        expect(w).toContain('`fitView`')
        expect(w).toContain('`snapToGrid`')
        expect(w).toContain('behaves differently on web')
      }
    })

    it('a NON-LITERAL minZoom is reported, not silently defaulted', () => {
      const src = `
        import { createFlow } from '@pyreon/flow'
        import { Text } from '${P}'
        export function X() {
          const lo = 0.5
          const flow = createFlow({
            nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
            edges: [],
            minZoom: lo,
          })
          return <Text>{flow.zoom()}</Text>
        }
      `
      expect((transform(src, { target: 'swift' }).warnings ?? []).join(' ')).toContain(
        'minZoom (not a numeric literal)',
      )
    })

    it('a config with ONLY nodes/edges stays silent and byte-identical', () => {
      // The control. A warning that fires unconditionally is worth nothing.
      const src = cfg('')
      for (const target of ['swift', 'kotlin'] as const) {
        const r = transform(src, { target })
        expect((r.warnings ?? []).join(' ')).not.toContain('NOT lowered natively')
        expect(r.code).not.toContain('minZoom')
        expect(r.code).not.toContain('maxZoom')
      }
    })

    it.skipIf(!isSwiftcAvailable())('the threaded Swift emit typechecks', () => {
      const res = validateSwiftWithStubs(
        transform(cfg('minZoom: 0.5, maxZoom: 2,'), { target: 'swift' }).code,
      )
      expect(res.ok, res.error ?? '').toBe(true)
    })

    it.skipIf(!isKotlincAvailable())('the threaded Kotlin emit typechecks', () => {
      const res = validateKotlin(
        transform(cfg('minZoom: 0.5, maxZoom: 2,'), { target: 'kotlin' }).code,
      )
      expect(res.ok, res.error ?? '').toBe(true)
    })
  })
})


// ── Nothing silent inside the boundary (the flow audit's compiler half) ──
// The import-level boundary (`<Flow>`, layout, chrome) already warned by name.
// The layer INSIDE it did not: unported FlowInstance members emitted verbatim
// with 0 warnings (dying at xcodebuild), `fitView()` compiled and did nothing,
// node/edge fields beyond the six the native types carry vanished at
// declaration AND call site, the Swift emit passed `additive`/`padding`
// positionally (an iOS-only build break), and the Swift stub was narrower
// than the runtime (rejecting valid reads). Every one of those is now either
// a named warning or a correct emit, on both targets.
describe('createFlow — nothing silent inside the boundary', () => {
  const base = (body: string, jsx = '<Text>{flow.nodes().length}</Text>') => `
import { createFlow } from '@pyreon/flow'
import { Stack, Text, Button } from '${P}'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
    edges: [{ id: 'e1', source: '1', target: '1' }],
  })
  ${body}
  return (<Stack>${jsx}</Stack>)
}
`
  const warningsOf = (src: string, target: 'swift' | 'kotlin') => (transform(src, { target }).warnings ?? []).join('\n')

  for (const target of ['swift', 'kotlin'] as const) {
    it(`[${target}] an unported FlowInstance member warns BY NAME instead of dying at the native build`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.undo()}>Undo</Button>'), target)
      expect(w).toContain('`undo` is NOT ported')
      expect(w).toContain('fails at the native BUILD')
    })
    it(`[${target}] a signal WRITE on a flow property warns (the native collections are read-only)`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.nodes.set([])}>Clear</Button>'), target)
      expect(w).toContain('`nodes.set(...)` writes the `nodes` signal directly')
    })
    it(`[${target}] fitView() warns that no native host measures containerSize yet`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.fitView()}>Fit</Button>'), target)
      expect(w).toContain('`fitView()` compiles natively but does NOTHING from shared source')
    })
    it(`[${target}] a ported member emits with NO member warning (the control)`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.zoomIn()}>Zoom</Button>'), target)
      expect(w).not.toContain('is NOT ported')
      expect(w).not.toContain('does NOTHING')
    })
    it(`[${target}] node/edge fields the native types do not carry warn BY NAME at the DECLARATION`, () => {
      const src = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text } from '${P}'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' }, parentId: 'root', draggable: false }],
    edges: [{ id: 'e1', source: '1', target: '1', markerEnd: 'arrow', sourceHandle: 'out' }],
  })
  return (<Stack><Text>{flow.nodes().length}</Text></Stack>)
}
`
      const w = warningsOf(src, target)
      expect(w).toContain('node fields `parentId`, `draggable` are NOT carried')
      expect(w).toContain('edge fields `markerEnd`, `sourceHandle` are NOT carried')
    })
    it(`[${target}] a declaration-time NON-literal edge label/type is named, not silently dropped`, () => {
      const src = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text } from '${P}'
const LBL = 'wire'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
    edges: [{ id: 'e1', source: '1', target: '1', label: LBL }],
  })
  return (<Stack><Text>{flow.nodes().length}</Text></Stack>)
}
`
      expect(warningsOf(src, target)).toContain('`label (not a string literal)`')
    })
    it(`[${target}] call-site addNode/addEdge literals with extra fields warn BY NAME`, () => {
      const w = warningsOf(base('', `<Button onPress={() => { flow.addNode({ id: '2', position: { x: 1, y: 1 }, data: { label: 'B' }, hidden: true }); flow.addEdge({ id: 'e2', source: '1', target: '2', waypoints: [] }) }}>Add</Button>`), target)
      expect(w).toContain('addNode(...): node field `hidden` is NOT carried')
      expect(w).toContain('addEdge(...): edge field `waypoints` is NOT carried')
    })
  }

  describe('Swift argument labels + stub fidelity', () => {
    const src = base('', `<Button onPress={() => { flow.selectNode('1', true); flow.selectEdge('e1', true); flow.fitView(undefined, 0.2); flow.fitView(['1'], 0.3) }}>Go</Button><Text>{flow.getNode('1')?.position.x}</Text><Text>{flow.getNode('1')?.width}</Text><Text>{flow.edges()[0].type}</Text>`)
    const r = transform(src, { target: 'swift' })
    it('emits the labeled forms the runtime requires', () => {
      expect(r.code).toContain('flow.selectNode("1", additive: true)')
      expect(r.code).toContain('flow.selectEdge("e1", additive: true)')
      expect(r.code).toContain('flow.fitView(nil, padding: 0.2)')
      expect(r.code).toContain('padding: 0.3)')
    })
    it('the labeled emit AND the valid reads typecheck against a stub that mirrors the runtime', () => {
      // The v1 stub had no stored `x`/`y`, no node `width`/`type`, and an
      // edge with no stored properties at all — every read below is valid
      // against PyreonFlowState.swift and was REJECTED by the gate.
      const v = validateSwiftWithStubs(r.code)
      expect(v.ok, v.error ?? '').toBe(true)
    })
  })
})
