// `@pyreon/flow`'s `createFlow` lowers to the @Observable/`remember`
// PyreonFlowState port. Unlike `createTableState` (which wraps an external
// reactive data source), `createFlow` OWNS its data — nodes/edges are
// captured as LITERAL config at declaration time, so the Swift emit needs
// no `.onAppear` wiring dance (fully self-contained @State initializer,
// closer to `PyreonMachine`'s shape than the table's).
//
// Verified END-TO-END beyond these string assertions: the ACTUAL emit
// type-checks against the real SwiftUI SDK + the real @Observable port on
// macOS (see PyreonFlowState.swift + PyreonFlowStateTests.swift, a real
// executable proving the behavior, not just the types), and both targets
// validate against the compiler stubs here.

import { describe, expect, it } from 'vitest'
import { transform } from '../index'
import {
  isKotlincAvailable,
  isSwiftcAvailable,
  validateKotlin,
  validateSwiftWithStubs,
} from '../validate'

const P = '@pyreon/primitives'
const workflowFlow = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text, Button } from '${P}'
export function WorkflowFlow() {
  const flow = createFlow({
    nodes: [
      { id: '1', position: { x: 0, y: 0 }, data: { label: 'Start' } },
      { id: '2', position: { x: 200, y: 100 }, data: { label: 'End' } },
    ],
    edges: [{ id: 'e1', source: '1', target: '2', animated: true }],
  })
  return (
    <Stack>
      <Text>{flow.nodes().length}</Text>
      <Text>{flow.zoom()}</Text>
      <Button onPress={() => flow.addNode({ id: '3', position: { x: 100, y: 200 }, data: { label: 'New' } })}>Add</Button>
      <Button onPress={() => flow.selectNode('1')}>Select</Button>
      <Text>{flow.selectedNodes().length}</Text>
    </Stack>
  )
}
`

describe('createFlow — Swift lowering', () => {
  const r = transform(workflowFlow, { target: 'swift' })

  it('emits a self-seeding @State PyreonFlowState, row struct synthesized from `data`', () => {
    // The row struct name is the shared `synthLiteralStructName` registry's
    // generated name (`__ObjN`) — the SAME one every OTHER object literal in
    // the file resolves through, which is the point (see the row-type
    // resolution comment in emit-swift.ts): it must be the identical name
    // each node's `data: {...}` literal below ALSO resolves to.
    expect(r.code).toMatch(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)
    const structName = r.code.match(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)?.[1]
    expect(structName).toBeDefined()
    expect(r.code).toContain(`PyreonFlowState<${structName}>(nodes: [`)
    expect(r.code).toContain(
      `PyreonFlowNode(id: "1", position: PyreonXYPosition(x: 0, y: 0), data: ${structName}(label: "Start"))`,
    )
    expect(r.code).toContain(
      `PyreonFlowNode(id: "2", position: PyreonXYPosition(x: 200, y: 100), data: ${structName}(label: "End"))`,
    )
    expect(r.code).toContain('PyreonFlowEdge(id: "e1", source: "1", target: "2", animated: true)')
  })

  it('does NOT wire an .onAppear data source (createFlow owns its data, unlike table)', () => {
    expect(r.code).not.toContain('.onAppear { flow.setData')
  })

  it('nodes()/edges()/viewport()/zoom() drop parens (property reads)', () => {
    expect(r.code).toContain('flow.nodes.count')
    expect(r.code).toContain('"\\(flow.zoom)"')
  })

  it('addNode()/selectNode() stay methods — and addNode\'s object-literal argument resolves to a REAL PyreonFlowNode, not a synthesized lookalike struct', () => {
    // This is the load-bearing assertion for the swiftFlowNodeLiteral
    // rewrite: without it, `addNode({...})`'s literal argument synthesizes
    // its OWN unrelated `__ObjN` struct (same field names as PyreonFlowNode,
    // different NOMINAL type) — Swift's type system is nominal, so that
    // fails to typecheck even though the shapes match. `PyreonFlowNode(` is
    // the discriminator; the generic path would emit a bare `__ObjN(`.
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id: "3", position: PyreonXYPosition\(x: 100, y: 200\), data: __Obj\d+\(label: "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('selectedNodes() stays a method call (matches the web call syntax, no rewrite)', () => {
    expect(r.code).toContain('flow.selectedNodes().count')
  })

  it('the recognizer itself does not decline this shape (no createFlow-specific warning)', () => {
    // NOTE: the package-level blanket "@pyreon/flow is WEB-ONLY" warning
    // still fires here — it is derived from the manifest's `multiplatform`
    // declaration (`WEB_ONLY_PACKAGES`, regenerated by
    // check-multiplatform-tier.ts --write-table), which this PR's compiler
    // work does not yet touch. That is a separate, tracked follow-up (adding
    // a `nativeFrontend` entry to flow's manifest); this test only asserts
    // the RECOGNIZER accepted the shape, which is what it can prove today.
    expect((r.warnings ?? []).some((w) => w.includes('createFlow declaration'))).toBe(false)
  })

  it('the emit type-checks against the Swift stubs', () => {
    const v = validateSwiftWithStubs(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('createFlow — Kotlin lowering', () => {
  const r = transform(workflowFlow, { target: 'kotlin' })

  it('emits a remembered PyreonFlowState with literal node/edge config, Int position literals coerced to Double', () => {
    expect(r.code).toContain('remember { PyreonFlowState<')
    expect(r.code).toContain('nodes = listOf(')
    // Kotlin refuses a bare Int literal where PyreonXYPosition wants Double —
    // `0` must emit as `0.0` (see the ktChartDouble coercion in emit-kotlin.ts).
    expect(r.code).toContain('PyreonFlowNode(id = "1", position = PyreonXYPosition(0.0, 0.0), data = ')
    expect(r.code).toContain('PyreonFlowEdge(id = "e1", source = "1", target = "2", animated = true)')
  })

  it('use-sites: nodes/zoom are property reads (via the TS-compat `.length` extension); addNode resolves a REAL PyreonFlowNode', () => {
    // `.length` (not `.size`) is deliberate — `flow.nodes()` reads as a JS
    // array on web, so the SAME cross-target `.length` extension every other
    // Kotlin-emitted array read uses applies here too (it is `flow.nodes`
    // that drops the parens; `.length` is unrelated to this rewrite).
    expect(r.code).toContain('flow.nodes.length')
    expect(r.code).toContain('${flow.zoom}')
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id = "3", position = PyreonXYPosition\(100\.0, 200\.0\), data = __Obj\d+\(label = "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('the emit type-checks against the Kotlin stubs', () => {
    const v = validateKotlin(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('<Flow> native host lowering', () => {
  const source = `
    import { createFlow, Flow } from '@pyreon/flow'
    export function App() {
      const flow = createFlow({
        nodes: [{ id: 'a', position: { x: 0, y: 0 }, data: { label: 'Start' } }],
        edges: [],
      })
      return <Flow instance={flow} />
    }
  `

  it('emits the SwiftUI host instead of an unresolved web component', () => {
    const result = transform(source, { target: 'swift' })
    expect(result.code).toContain('PyreonFlowView(state: flow) { pyreonNode in')
    expect(result.code).toContain('Text(pyreonNode.id)')
    expect(result.warnings.some((warning) => warning.includes('Flow (from @pyreon/flow)'))).toBe(false)
    if (isSwiftcAvailable()) expect(validateSwiftWithStubs(result.code).ok).toBe(true)
  })

  it('extracts Background chrome into the SwiftUI and Compose host configuration', () => {
    const withBackground = source.replace(
      "import { createFlow, Flow }",
      "import { createFlow, Flow, Background }",
    ).replace('<Flow instance={flow} />', '<Flow instance={flow}><Background variant="cross" gap={24} size={2} color="#abc" /></Flow>')
    const swift = transform(withBackground, { target: 'swift' })
    const kotlin = transform(withBackground, { target: 'kotlin' })
    expect(swift.code).toContain('background: PyreonFlowBackgroundStyle(variant: .cross, gap: 24, size: 2, color: "#abc")')
    expect(kotlin.code).toContain('background = PyreonFlowBackgroundStyle(variant = PyreonFlowBackgroundVariant.Cross, gap = 24.0, size = 2.0, color = "#abc")')
    expect(swift.warnings.some((warning) => warning.includes('Background (from @pyreon/flow)'))).toBe(false)
    expect(kotlin.warnings.some((warning) => warning.includes('Background (from @pyreon/flow)'))).toBe(false)
    if (isSwiftcAvailable()) expect(validateSwiftWithStubs(swift.code).ok).toBe(true)
    if (isKotlincAvailable()) expect(validateKotlin(kotlin.code).ok).toBe(true)
  })

  it('extracts functional Controls configuration on both targets', () => {
    const withControls = source.replace(
      "import { createFlow, Flow }",
      "import { createFlow, Flow, Controls }",
    ).replace('<Flow instance={flow} />', '<Flow instance={flow}><Controls showZoomOut={false} showLock={true} position="top-right" /></Flow>')
    const swift = transform(withControls, { target: 'swift' })
    const kotlin = transform(withControls, { target: 'kotlin' })
    expect(swift.code).toContain('controls: PyreonFlowControlsStyle(showZoomIn: true, showZoomOut: false, showFitView: true, showLock: true, position: .topRight)')
    expect(kotlin.code).toContain('controls = PyreonFlowControlsStyle(showZoomIn = true, showZoomOut = false, showFitView = true, showLock = true, position = PyreonFlowControlsPosition.TopRight)')
    expect(swift.warnings.some((warning) => warning.includes('Controls (from @pyreon/flow)'))).toBe(false)
    expect(kotlin.warnings.some((warning) => warning.includes('Controls (from @pyreon/flow)'))).toBe(false)
    if (isSwiftcAvailable()) expect(validateSwiftWithStubs(swift.code).ok).toBe(true)
    if (isKotlincAvailable()) expect(validateKotlin(kotlin.code).ok).toBe(true)
  })

  it('extracts interactive MiniMap configuration on both targets', () => {
    const withMiniMap = source.replace(
      "import { createFlow, Flow }",
      "import { createFlow, Flow, MiniMap }",
    ).replace('<Flow instance={flow} />', '<Flow instance={flow}><MiniMap nodeColor="#123456" maskColor="#abcdef" width={180} height={120} pannable={false} /></Flow>')
    const swift = transform(withMiniMap, { target: 'swift' })
    const kotlin = transform(withMiniMap, { target: 'kotlin' })
    expect(swift.code).toContain('miniMap: PyreonFlowMiniMapStyle(nodeColor: "#123456", maskColor: "#abcdef", width: 180, height: 120, pannable: false, zoomable: true)')
    expect(kotlin.code).toContain('miniMap = PyreonFlowMiniMapStyle(nodeColor = "#123456", maskColor = "#abcdef", width = 180.0, height = 120.0, pannable = false, zoomable = true)')
    expect(swift.warnings.some((warning) => warning.includes('MiniMap (from @pyreon/flow)'))).toBe(false)
    expect(kotlin.warnings.some((warning) => warning.includes('MiniMap (from @pyreon/flow)'))).toBe(false)
    if (isSwiftcAvailable()) expect(validateSwiftWithStubs(swift.code).ok).toBe(true)
    if (isKotlincAvailable()) expect(validateKotlin(kotlin.code).ok).toBe(true)
  })

  it('emits the Compose host instead of an unresolved web component', () => {
    const result = transform(source, { target: 'kotlin' })
    expect(result.code).toContain('PyreonFlowView(state = flow) { pyreonNode ->')
    expect(result.code).toContain('Text(text = pyreonNode.id)')
    expect(result.warnings.some((warning) => warning.includes('Flow (from @pyreon/flow)'))).toBe(false)
    if (isKotlincAvailable()) expect(validateKotlin(result.code).ok).toBe(true)
  })
})

describe('createFlow connection validation lowering', () => {
  const source = `
    import { createFlow } from '@pyreon/flow'
    export function App() {
      const flow = createFlow({
        nodes: [
          { id: 'api', type: 'api', position: { x: 0, y: 0 }, data: { label: 'API' } },
          { id: 'db', type: 'database', position: { x: 100, y: 0 }, data: { label: 'DB' } },
        ],
        edges: [],
        connectionRules: { api: { outputs: ['database'] } },
        isValidConnection: (connection) => connection.source !== connection.target,
      })
      return null
    }
  `

  it('emits literal rules and callback for Swift and Kotlin', () => {
    const swift = transform(source, { target: 'swift' })
    const kotlin = transform(source, { target: 'kotlin' })
    expect(swift.code).toContain('connectionRules: ["api": ["database"]]')
    expect(swift.code).toContain('isValidConnection: { connection in connection.source != connection.target }')
    expect(kotlin.code).toContain('connectionRules = mapOf("api" to listOf("database"))')
    expect(kotlin.code).toContain('connectionValidator = { connection -> connection.source != connection.target }')
    if (isSwiftcAvailable()) expect(validateSwiftWithStubs(swift.code).ok).toBe(true)
    if (isKotlincAvailable()) expect(validateKotlin(kotlin.code).ok).toBe(true)
  })
})

describe('createFlow — v1 decline shapes (loud warning, not silent drop)', () => {
  it('a non-literal nodes source declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const seed = getSeedNodes()
        const flow = createFlow({ nodes: seed, edges: [] })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })

  it('nodes whose data field sets DIFFER decline (one row struct cannot represent both)', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [
            { id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } },
            { id: '2', position: { x: 0, y: 0 }, data: { count: 1 } },
          ],
          edges: [],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect((r.warnings ?? []).some((w) => w.includes('SAME field set'))).toBe(true)
  })

  it('an edge missing an explicit id declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
          edges: [{ source: '1', target: '2' }],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })

  // `createFlow` takes 17 config keys. The reader took two. The other fifteen
  // lowered to NOTHING and said nothing, so `createFlow({ …, minZoom: 0.5 })`
  // clamped zoom to 2x on web and 4x natively from the same source line —
  // compiles, runs, silently wrong on one target.
  describe('config keys beyond nodes/edges', () => {
    const cfg = (extra: string) => `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
          edges: [],
          ${extra}
        })
        return <Text>{flow.zoom()}</Text>
      }
    `

    it('minZoom/maxZoom THREAD THROUGH — the runtimes always took them', () => {
      const src = cfg('minZoom: 0.5, maxZoom: 2,')
      expect(transform(src, { target: 'swift' }).code).toContain('minZoom: 0.5, maxZoom: 2')
      expect(transform(src, { target: 'kotlin' }).code).toContain('minZoom = 0.5, maxZoom = 2.0')
    })

    it('Kotlin renders them as DOUBLE literals — Int does not widen at a call site', () => {
      // `maxZoom: 2` emitting `maxZoom = 2` is "argument type mismatch: actual
      // type is 'Int', but 'Double' was expected". Swift takes the same source
      // fine, which is how a bug like this stays hidden until a real compile.
      const code = transform(cfg('maxZoom: 2,'), { target: 'kotlin' }).code
      expect(code).toContain('maxZoom = 2.0')
      expect(code).not.toContain('maxZoom = 2)')
    })

    it('an UNLOWERED key warns by NAME on both targets', () => {
      const src = cfg('fitView: true, snapToGrid: true,')
      for (const target of ['swift', 'kotlin'] as const) {
        const w = (transform(src, { target }).warnings ?? []).join(' ')
        expect(w).toContain('`fitView`')
        expect(w).not.toContain('`snapToGrid`')
        expect(w).toContain('behaves differently on web')
      }
    })

    it('grid snapping and node extent config cross on both targets', () => {
      const src = cfg('snapToGrid: true, snapGrid: 10, nodeExtent: [[0, 5], [200, 300]],')
      const swift = transform(src, { target: 'swift' })
      expect(swift.code).toContain('snapToGrid: true, snapGrid: 10, nodeExtent: PyreonFlowNodeExtent(minX: 0, minY: 5, maxX: 200, maxY: 300)')
      expect((swift.warnings ?? []).join(' ')).not.toContain('NOT lowered natively')
      expect(validateSwiftWithStubs(swift.code).ok).toBe(true)
      const kotlin = transform(src, { target: 'kotlin' })
      expect(kotlin.code).toContain('snapToGrid = true, snapGrid = 10.0, nodeExtent = PyreonFlowNodeExtent(0.0, 5.0, 200.0, 300.0)')
      expect((kotlin.warnings ?? []).join(' ')).not.toContain('NOT lowered natively')
      expect(validateKotlin(kotlin.code).ok).toBe(true)
    })

    it('a NON-LITERAL minZoom is reported, not silently defaulted', () => {
      const src = `
        import { createFlow } from '@pyreon/flow'
        import { Text } from '${P}'
        export function X() {
          const lo = 0.5
          const flow = createFlow({
            nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
            edges: [],
            minZoom: lo,
          })
          return <Text>{flow.zoom()}</Text>
        }
      `
      expect((transform(src, { target: 'swift' }).warnings ?? []).join(' ')).toContain(
        'minZoom (not a numeric literal)',
      )
    })

    it('a config with ONLY nodes/edges stays silent and byte-identical', () => {
      // The control. A warning that fires unconditionally is worth nothing.
      const src = cfg('')
      for (const target of ['swift', 'kotlin'] as const) {
        const r = transform(src, { target })
        expect((r.warnings ?? []).join(' ')).not.toContain('NOT lowered natively')
        expect(r.code).not.toContain('minZoom')
        expect(r.code).not.toContain('maxZoom')
      }
    })

    it.skipIf(!isSwiftcAvailable())('the threaded Swift emit typechecks', () => {
      const res = validateSwiftWithStubs(
        transform(cfg('minZoom: 0.5, maxZoom: 2,'), { target: 'swift' }).code,
      )
      expect(res.ok, res.error ?? '').toBe(true)
    })

    it.skipIf(!isKotlincAvailable())('the threaded Kotlin emit typechecks', () => {
      const res = validateKotlin(
        transform(cfg('minZoom: 0.5, maxZoom: 2,'), { target: 'kotlin' }).code,
      )
      expect(res.ok, res.error ?? '').toBe(true)
    })
  })
})


// ── Nothing silent inside the boundary (the flow audit's compiler half) ──
// The import-level boundary (`<Flow>`, layout, chrome) already warned by name.
// The layer INSIDE it did not: unported FlowInstance members emitted verbatim
// with 0 warnings (dying at xcodebuild), `fitView()` compiled and did nothing,
// node/edge fields beyond the six the native types carry vanished at
// declaration AND call site, the Swift emit passed `additive`/`padding`
// positionally (an iOS-only build break), and the Swift stub was narrower
// than the runtime (rejecting valid reads). Every one of those is now either
// a named warning or a correct emit, on both targets.
describe('createFlow — nothing silent inside the boundary', () => {
  const base = (body: string, jsx = '<Text>{flow.nodes().length}</Text>') => `
import { createFlow } from '@pyreon/flow'
import { Stack, Text, Button } from '${P}'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
    edges: [{ id: 'e1', source: '1', target: '1' }],
  })
  ${body}
  return (<Stack>${jsx}</Stack>)
}
`
  const warningsOf = (src: string, target: 'swift' | 'kotlin') => (transform(src, { target }).warnings ?? []).join('\n')

  for (const target of ['swift', 'kotlin'] as const) {
    it(`[${target}] an unported FlowInstance member warns BY NAME instead of dying at the native build`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.undo()}>Undo</Button>'), target)
      expect(w).toContain('`undo` is NOT ported')
      expect(w).toContain('fails at the native BUILD')
    })
    it(`[${target}] a signal WRITE on a flow property warns (the native collections are read-only)`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.nodes.set([])}>Clear</Button>'), target)
      expect(w).toContain('`nodes.set(...)` writes the `nodes` signal directly')
    })
    it(`[${target}] fitView() warns that no native host measures containerSize yet`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.fitView()}>Fit</Button>'), target)
      expect(w).toContain('`fitView()` compiles natively but does NOTHING from shared source')
    })
    it(`[${target}] a ported member emits with NO member warning (the control)`, () => {
      const w = warningsOf(base('', '<Button onPress={() => flow.zoomIn()}>Zoom</Button>'), target)
      expect(w).not.toContain('is NOT ported')
      expect(w).not.toContain('does NOTHING')
    })
    it(`[${target}] bulk, coordinate, visibility and group methods lower without silent member gaps`, () => {
      const src = base('', `<Button onPress={() => { flow.selectNodes(['1'], true); flow.moveSelectedNodes(2, 3); flow.removeEdges(['e1']); flow.removeNodes(['missing']); flow.focusNode('1', 2); flow.panTo({ x: 4, y: 5 }) }}>Act</Button><Text>{flow.getNodes().length}</Text><Text>{flow.getEdges().length}</Text><Text>{flow.getViewport().zoom}</Text><Text>{flow.screenToFlowPosition({ x: 10, y: 20 }).x}</Text><Text>{flow.flowToScreenPosition({ x: 1, y: 2 }).y}</Text><Text>{flow.isNodeVisible('1')}</Text><Text>{flow.getChildNodes('root').length}</Text><Text>{flow.getAbsolutePosition('1').x}</Text>`)
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      for (const member of ['selectNodes', 'moveSelectedNodes', 'removeEdges', 'removeNodes', 'focusNode', 'panTo', 'getNodes', 'getEdges', 'getViewport', 'screenToFlowPosition', 'flowToScreenPosition', 'isNodeVisible', 'getChildNodes', 'getAbsolutePosition']) {
        expect(w).not.toContain(`\`${member}\` is NOT ported`)
      }
      if (target === 'swift') {
        expect(result.code).toContain('flow.selectNodes(["1"], additive: true)')
        expect(result.code).toContain('flow.panTo(PyreonXYPosition(x: 4, y: 5))')
        expect(validateSwiftWithStubs(result.code).ok).toBe(true)
      } else {
        expect(result.code).toContain('flow.moveSelectedNodes(2.0, 3.0)')
        expect(result.code).toContain('flow.focusNode("1", 2.0)')
        expect(result.code).toContain('flow.panTo(PyreonXYPosition(4.0, 5.0))')
        expect(validateKotlin(result.code).ok).toBe(true)
      }
    })
    it(`[${target}] carried node/edge fields emit, while genuinely unsupported fields still warn BY NAME`, () => {
      const src = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text } from '${P}'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' }, parentId: 'root', draggable: false, selectable: true, connectable: false, focusable: true, ariaLabel: 'Start node', hidden: false, deletable: true, expandParent: true, group: true, sourceHandles: [{ id: 'out', type: 'source', position: 'right' }], targetHandles: [{ type: 'target', position: 'left' }], style: {} }],
    edges: [{ id: 'e1', source: '1', target: '1', markerEnd: 'arrow', sourceHandle: 'out', targetHandle: 'in', focusable: true, ariaLabel: 'Loop', hidden: false, deletable: true, reconnectable: false, interactionWidth: 24 }],
  })
  return (<Stack><Text>{flow.nodes().length}</Text></Stack>)
}
`
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      expect(w).toContain('node field `style` is NOT carried')
      expect(w).toContain('edge field `markerEnd` is NOT carried')
      for (const field of ['parentId', 'draggable', 'selectable', 'connectable', 'focusable', 'ariaLabel', 'hidden', 'deletable', 'expandParent', 'group', 'sourceHandles', 'targetHandles', 'sourceHandle', 'targetHandle', 'reconnectable', 'interactionWidth']) {
        expect(w).not.toContain(`field \`${field}\` is NOT carried`)
      }
      const assignment = target === 'swift' ? ':' : ' ='
      expect(result.code).toContain(`parentId${assignment} "root"`)
      expect(result.code).toContain(`draggable${assignment} false`)
      expect(result.code).toContain(`sourceHandle${assignment} "out"`)
      expect(result.code).toContain(`targetHandle${assignment} "in"`)
      expect(result.code).toContain(`ariaLabel${assignment} "Loop"`)
      expect(result.code).toContain(`interactionWidth${assignment} ${target === 'swift' ? '24' : '24.0'}`)
      expect(result.code).toContain(target === 'swift' ? 'sourceHandles: [PyreonFlowHandleConfig(id: "out", type: "source", position: .right)]' : 'sourceHandles = listOf(PyreonFlowHandleConfig(id = "out", type = "source", position = PyreonFlowPosition.Right))')
    })
    it(`[${target}] a declaration-time NON-literal edge label/type is named, not silently dropped`, () => {
      const src = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text } from '${P}'
const LBL = 'wire'
export function C() {
  const flow = createFlow({
    nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
    edges: [{ id: 'e1', source: '1', target: '1', label: LBL }],
  })
  return (<Stack><Text>{flow.nodes().length}</Text></Stack>)
}
`
      expect(warningsOf(src, target)).toContain('`label (not a string literal)`')
    })
    it(`[${target}] call-site addNode/addEdge literals with extra fields warn BY NAME`, () => {
      const w = warningsOf(base('', `<Button onPress={() => { flow.addNode({ id: '2', position: { x: 1, y: 1 }, data: { label: 'B' }, hidden: true, sourceHandles: [{ id: 'out', type: 'source', position: 'right' }], style: {} }); flow.addEdge({ id: 'e2', source: '1', target: '2', sourceHandle: 'out', waypoints: [], markerEnd: 'arrow' }) }}>Add</Button>`), target)
      expect(w).toContain('addNode(...): node field `style` is NOT carried')
      expect(w).not.toContain('node field `hidden` is NOT carried')
      expect(w).not.toContain('node field `sourceHandles` is NOT carried')
      expect(w).toContain('addEdge(...): edge field `markerEnd` is NOT carried')
      expect(w).not.toContain('edge field `waypoints` is NOT carried')
      expect(w).not.toContain('edge field `sourceHandle` is NOT carried')
    })
    it(`[${target}] waypoint editing and reconnect lower to native values and typecheck`, () => {
      const src = base('', `<Button onPress={() => { flow.addEdge({ id: 'e2', source: '1', target: '1', waypoints: [{ x: 4, y: 5 }] }); flow.addEdgeWaypoint('e1', { x: 1, y: 2 }, -1); flow.updateEdgeWaypoint('e1', 0, { x: 3, y: 4 }); flow.removeEdgeWaypoint('e1', -1); flow.reconnectEdge('e1', { target: '2', targetHandle: 'in' }) }}>Edit</Button>`)
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      for (const member of ['addEdgeWaypoint', 'updateEdgeWaypoint', 'removeEdgeWaypoint', 'reconnectEdge']) {
        expect(w).not.toContain(`\`${member}\` is NOT ported`)
      }
      expect(w).not.toContain('edge field `waypoints` is NOT carried')
      if (target === 'swift') {
        expect(result.code).toContain('waypoints: [PyreonXYPosition(x: 4, y: 5)]')
        expect(result.code).toContain('flow.addEdgeWaypoint("e1", PyreonXYPosition(x: 1, y: 2), -1)')
        expect(result.code).toContain('flow.reconnectEdge("e1", target: "2", targetHandle: "in")')
        expect(validateSwiftWithStubs(result.code).ok).toBe(true)
      } else {
        expect(result.code).toContain('waypoints = listOf(PyreonXYPosition(4.0, 5.0))')
        expect(result.code).toContain('flow.addEdgeWaypoint("e1", PyreonXYPosition(1.0, 2.0), -1)')
        expect(result.code).toContain('flow.reconnectEdge("e1", target = "2", targetHandle = "in")')
        expect(validateKotlin(result.code).ok).toBe(true)
      }
    })
    it(`[${target}] partial viewport writes and centering lower without losing omitted fields`, () => {
      const src = base('', `<Button onPress={() => { flow.setViewport({ x: 10, zoom: 2 }); flow.setCenter(30, 40, { zoom: 3 }) }}>View</Button>`)
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      expect(w).not.toContain('`setViewport` is NOT ported')
      expect(w).not.toContain('`setCenter` is NOT ported')
      if (target === 'swift') {
        expect(result.code).toContain('flow.setViewport(x: 10, zoom: 2)')
        expect(result.code).toContain('flow.setCenter(30, 40, zoom: 3)')
        expect(validateSwiftWithStubs(result.code).ok).toBe(true)
      } else {
        expect(result.code).toContain('flow.setViewport(x = 10.0, zoom = 2.0)')
        expect(result.code).toContain('flow.setCenter(30.0, 40.0, zoom = 3.0)')
        expect(validateKotlin(result.code).ok).toBe(true)
      }
    })
    it(`[${target}] literal bulk node and edge replacement lowers to nominal native model types`, () => {
      const src = base('', `<Button onPress={() => { flow.addNodes([{ id: '2', position: { x: 10, y: 20 }, data: { label: 'B' } }]); flow.addEdges([{ id: 'e2', source: '1', target: '2' }]); flow.setNodes([{ id: '2', position: { x: 30, y: 40 }, data: { label: 'C' } }]); flow.setEdges([{ id: 'e3', source: '2', target: '2' }]) }}>Bulk</Button>`)
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      for (const member of ['addNodes', 'addEdges', 'setNodes', 'setEdges']) expect(w).not.toContain(`\`${member}\` is NOT ported`)
      if (target === 'swift') {
        expect(result.code).toMatch(/flow\.addNodes\(\[PyreonFlowNode\(id: "2"/)
        expect(result.code).toContain('flow.setEdges([PyreonFlowEdge(id: "e3", source: "2", target: "2")])')
        expect(validateSwiftWithStubs(result.code).ok).toBe(true)
      } else {
        expect(result.code).toMatch(/flow\.addNodes\(listOf\(PyreonFlowNode\(id = "2"/)
        expect(result.code).toContain('flow.setEdges(listOf(PyreonFlowEdge(id = "e3", source = "2", target = "2")))')
        expect(validateKotlin(result.code).ok).toBe(true)
      }
    })
    it(`[${target}] node extent setup, clearing and clamping lower with typed positions`, () => {
      const src = base('', `<Button onPress={() => { flow.setNodeExtent([[0, 10], [200, 300]]); flow.clampToExtent({ x: 500, y: -2 }, 20, 30); flow.setNodeExtent(null) }}>Bounds</Button>`)
      const result = transform(src, { target })
      const w = (result.warnings ?? []).join('\n')
      expect(w).not.toContain('`setNodeExtent` is NOT ported')
      expect(w).not.toContain('`clampToExtent` is NOT ported')
      if (target === 'swift') {
        expect(result.code).toContain('flow.setNodeExtent(minX: 0, minY: 10, maxX: 200, maxY: 300)')
        expect(result.code).toContain('flow.clampToExtent(PyreonXYPosition(x: 500, y: -2), 20, 30)')
        expect(result.code).toContain('flow.clearNodeExtent()')
        expect(validateSwiftWithStubs(result.code).ok).toBe(true)
      } else {
        expect(result.code).toContain('flow.setNodeExtent(minX = 0.0, minY = 10.0, maxX = 200.0, maxY = 300.0)')
        expect(result.code).toContain('flow.clampToExtent(PyreonXYPosition(500.0, -2.0), 20.0, 30.0)')
        expect(result.code).toContain('flow.clearNodeExtent()')
        expect(validateKotlin(result.code).ok).toBe(true)
      }
    })
  }

  describe('Swift argument labels + stub fidelity', () => {
    const src = base('', `<Button onPress={() => { flow.selectNode('1', true); flow.selectEdge('e1', true); flow.fitView(undefined, 0.2); flow.fitView(['1'], 0.3) }}>Go</Button><Text>{flow.getNode('1')?.position.x}</Text><Text>{flow.getNode('1')?.width}</Text><Text>{flow.edges()[0].type}</Text>`)
    const r = transform(src, { target: 'swift' })
    it('emits the labeled forms the runtime requires', () => {
      expect(r.code).toContain('flow.selectNode("1", additive: true)')
      expect(r.code).toContain('flow.selectEdge("e1", additive: true)')
      expect(r.code).toContain('flow.fitView(nil, padding: 0.2)')
      expect(r.code).toContain('padding: 0.3)')
    })
    it('the labeled emit AND the valid reads typecheck against a stub that mirrors the runtime', () => {
      // The v1 stub had no stored `x`/`y`, no node `width`/`type`, and an
      // edge with no stored properties at all — every read below is valid
      // against PyreonFlowState.swift and was REJECTED by the gate.
      const v = validateSwiftWithStubs(r.code)
      expect(v.ok, v.error ?? '').toBe(true)
    })
  })
})
