// `@pyreon/flow`'s `createFlow` lowers to the @Observable/`remember`
// PyreonFlowState port. Unlike `createTableState` (which wraps an external
// reactive data source), `createFlow` OWNS its data — nodes/edges are
// captured as LITERAL config at declaration time, so the Swift emit needs
// no `.onAppear` wiring dance (fully self-contained @State initializer,
// closer to `PyreonMachine`'s shape than the table's).
//
// Verified END-TO-END beyond these string assertions: the ACTUAL emit
// type-checks against the real SwiftUI SDK + the real @Observable port on
// macOS (see PyreonFlowState.swift + PyreonFlowStateTests.swift, a real
// executable proving the behavior, not just the types), and both targets
// validate against the compiler stubs here.

import { describe, expect, it } from 'vitest'
import { transform } from '../index'
import { validateKotlin, validateSwiftWithStubs } from '../validate'

const P = '@pyreon/primitives'
const workflowFlow = `
import { createFlow } from '@pyreon/flow'
import { Stack, Text, Button } from '${P}'
export function WorkflowFlow() {
  const flow = createFlow({
    nodes: [
      { id: '1', position: { x: 0, y: 0 }, data: { label: 'Start' } },
      { id: '2', position: { x: 200, y: 100 }, data: { label: 'End' } },
    ],
    edges: [{ id: 'e1', source: '1', target: '2', animated: true }],
  })
  return (
    <Stack>
      <Text>{flow.nodes().length}</Text>
      <Text>{flow.zoom()}</Text>
      <Button onPress={() => flow.addNode({ id: '3', position: { x: 100, y: 200 }, data: { label: 'New' } })}>Add</Button>
      <Button onPress={() => flow.selectNode('1')}>Select</Button>
      <Text>{flow.selectedNodes().length}</Text>
    </Stack>
  )
}
`

describe('createFlow — Swift lowering', () => {
  const r = transform(workflowFlow, { target: 'swift' })

  it('emits a self-seeding @State PyreonFlowState, row struct synthesized from `data`', () => {
    // The row struct name is the shared `synthLiteralStructName` registry's
    // generated name (`__ObjN`) — the SAME one every OTHER object literal in
    // the file resolves through, which is the point (see the row-type
    // resolution comment in emit-swift.ts): it must be the identical name
    // each node's `data: {...}` literal below ALSO resolves to.
    expect(r.code).toMatch(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)
    const structName = r.code.match(/struct (__Obj\d+): Codable \{\s*var label: String\s*\}/)?.[1]
    expect(structName).toBeDefined()
    expect(r.code).toContain(`PyreonFlowState<${structName}>(nodes: [`)
    expect(r.code).toContain(
      `PyreonFlowNode(id: "1", position: PyreonXYPosition(x: 0, y: 0), data: ${structName}(label: "Start"))`,
    )
    expect(r.code).toContain(
      `PyreonFlowNode(id: "2", position: PyreonXYPosition(x: 200, y: 100), data: ${structName}(label: "End"))`,
    )
    expect(r.code).toContain('PyreonFlowEdge(id: "e1", source: "1", target: "2", animated: true)')
  })

  it('does NOT wire an .onAppear data source (createFlow owns its data, unlike table)', () => {
    expect(r.code).not.toContain('.onAppear { flow.setData')
  })

  it('nodes()/edges()/viewport()/zoom() drop parens (property reads)', () => {
    expect(r.code).toContain('flow.nodes.count')
    expect(r.code).toContain('"\\(flow.zoom)"')
  })

  it('addNode()/selectNode() stay methods — and addNode\'s object-literal argument resolves to a REAL PyreonFlowNode, not a synthesized lookalike struct', () => {
    // This is the load-bearing assertion for the swiftFlowNodeLiteral
    // rewrite: without it, `addNode({...})`'s literal argument synthesizes
    // its OWN unrelated `__ObjN` struct (same field names as PyreonFlowNode,
    // different NOMINAL type) — Swift's type system is nominal, so that
    // fails to typecheck even though the shapes match. `PyreonFlowNode(` is
    // the discriminator; the generic path would emit a bare `__ObjN(`.
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id: "3", position: PyreonXYPosition\(x: 100, y: 200\), data: __Obj\d+\(label: "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('selectedNodes() stays a method call (matches the web call syntax, no rewrite)', () => {
    expect(r.code).toContain('flow.selectedNodes().count')
  })

  it('the recognizer itself does not decline this shape (no createFlow-specific warning)', () => {
    // NOTE: the package-level blanket "@pyreon/flow is WEB-ONLY" warning
    // still fires here — it is derived from the manifest's `multiplatform`
    // declaration (`WEB_ONLY_PACKAGES`, regenerated by
    // check-multiplatform-tier.ts --write-table), which this PR's compiler
    // work does not yet touch. That is a separate, tracked follow-up (adding
    // a `nativeFrontend` entry to flow's manifest); this test only asserts
    // the RECOGNIZER accepted the shape, which is what it can prove today.
    expect((r.warnings ?? []).some((w) => w.includes('createFlow declaration'))).toBe(false)
  })

  it('the emit type-checks against the Swift stubs', () => {
    const v = validateSwiftWithStubs(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('createFlow — Kotlin lowering', () => {
  const r = transform(workflowFlow, { target: 'kotlin' })

  it('emits a remembered PyreonFlowState with literal node/edge config, Int position literals coerced to Double', () => {
    expect(r.code).toContain('remember { PyreonFlowState<')
    expect(r.code).toContain('nodes = listOf(')
    // Kotlin refuses a bare Int literal where PyreonXYPosition wants Double —
    // `0` must emit as `0.0` (see the ktChartDouble coercion in emit-kotlin.ts).
    expect(r.code).toContain('PyreonFlowNode(id = "1", position = PyreonXYPosition(0.0, 0.0), data = ')
    expect(r.code).toContain('PyreonFlowEdge(id = "e1", source = "1", target = "2", animated = true)')
  })

  it('use-sites: nodes/zoom are property reads (via the TS-compat `.length` extension); addNode resolves a REAL PyreonFlowNode', () => {
    // `.length` (not `.size`) is deliberate — `flow.nodes()` reads as a JS
    // array on web, so the SAME cross-target `.length` extension every other
    // Kotlin-emitted array read uses applies here too (it is `flow.nodes`
    // that drops the parens; `.length` is unrelated to this rewrite).
    expect(r.code).toContain('flow.nodes.length')
    expect(r.code).toContain('${flow.zoom}')
    expect(r.code).toMatch(/flow\.addNode\(PyreonFlowNode\(id = "3", position = PyreonXYPosition\(100\.0, 200\.0\), data = __Obj\d+\(label = "New"\)\)\)/)
    expect(r.code).toContain('flow.selectNode("1")')
  })

  it('the emit type-checks against the Kotlin stubs', () => {
    const v = validateKotlin(r.code)
    expect(v.ok, v.error ?? '').toBe(true)
  })
})

describe('createFlow — v1 decline shapes (loud warning, not silent drop)', () => {
  it('a non-literal nodes source declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const seed = getSeedNodes()
        const flow = createFlow({ nodes: seed, edges: [] })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })

  it('nodes whose data field sets DIFFER decline (one row struct cannot represent both)', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [
            { id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } },
            { id: '2', position: { x: 0, y: 0 }, data: { count: 1 } },
          ],
          edges: [],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect((r.warnings ?? []).some((w) => w.includes('SAME field set'))).toBe(true)
  })

  it('an edge missing an explicit id declines with a named reason', () => {
    const src = `
      import { createFlow } from '@pyreon/flow'
      import { Text } from '${P}'
      export function X() {
        const flow = createFlow({
          nodes: [{ id: '1', position: { x: 0, y: 0 }, data: { label: 'A' } }],
          edges: [{ source: '1', target: '2' }],
        })
        return <Text>{flow.nodes().length}</Text>
      }
    `
    const r = transform(src, { target: 'swift' })
    expect(r.warnings ?? []).toEqual(
      expect.arrayContaining([expect.stringContaining('createFlow declaration `flow`')]),
    )
  })
})
