import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  createServeHandler,
  loadRedirects,
  matchRedirect,
  parseRedirects,
} from '../../../../../scripts/serve-ssg'

/**
 * Tests for the `_redirects` support added to `scripts/serve-ssg.ts`.
 *
 * **Why this matters**: `ssg-plugin.ts` emits `dist/_redirects` when
 * loaders throw `redirect()` (PR B of the SSG roadmap). Real static
 * hosts (Netlify, Cloudflare Pages) apply these. Pre-fix the
 * `serve-ssg.ts` script — used by the `ssg-i18n` e2e gate and any
 * future SSG-runtime gate — didn't read either file, so apps with
 * auth-gate redirects under SSG silently produced wrong results
 * locally (404 instead of the 301/302/307 redirect that production
 * would emit). This was a divergence between local-preview behaviour
 * and production-host behaviour that the SSG roadmap's "honest
 * preview shape" pillar was supposed to close.
 *
 * Format source-of-truth: `packages/zero/zero/src/ssg-plugin.ts:
 * renderNetlifyRedirects` — comment header line + one rule per line
 * (`<from> <to> <status>` space-separated).
 */

function makeRoot(redirectsContent?: string): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), 'pyreon-serve-ssg-')))
  if (redirectsContent !== undefined) {
    writeFileSync(join(dir, '_redirects'), redirectsContent)
  }
  return dir
}

describe('parseRedirects', () => {
  it('parses Pyreon-emitted format (header comment + rule lines)', () => {
    const content = [
      '# Auto-generated by @pyreon/zero SSG. Do not edit.',
      '/login /signin 302',
      '/old /new 301',
    ].join('\n')
    expect(parseRedirects(content)).toEqual([
      { from: '/login', to: '/signin', status: 302 },
      { from: '/old', to: '/new', status: 301 },
    ])
  })

  it('defaults status to 301 when column 3 is missing', () => {
    expect(parseRedirects('/from /to')).toEqual([
      { from: '/from', to: '/to', status: 301 },
    ])
  })

  it('tolerates blank lines and inline whitespace', () => {
    const content = [
      '',
      '# comment',
      '   ',
      '/a  /b  301',
      '',
      '/c /d 302',
    ].join('\n')
    expect(parseRedirects(content)).toEqual([
      { from: '/a', to: '/b', status: 301 },
      { from: '/c', to: '/d', status: 302 },
    ])
  })

  it('rejects rules with malformed status (out of 3xx range)', () => {
    // Defensive: a hand-edited manifest with `404` or `200` should not
    // become a "redirect to error page" redirect. Drop the rule
    // entirely; let the file-serving path 404 normally if the URL is
    // really unmatched.
    expect(parseRedirects('/a /b 404')).toEqual([])
    expect(parseRedirects('/a /b 200')).toEqual([])
    expect(parseRedirects('/a /b abc')).toEqual([])
  })

  it('skips rules missing a destination column', () => {
    expect(parseRedirects('/from')).toEqual([])
  })

  it('returns empty array for empty input', () => {
    expect(parseRedirects('')).toEqual([])
  })
})

describe('loadRedirects', () => {
  it('returns [] when _redirects does not exist', () => {
    const root = makeRoot()
    try {
      expect(loadRedirects(root)).toEqual([])
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('reads + parses _redirects from <root>/_redirects', () => {
    const root = makeRoot('/old /new 301\n')
    try {
      expect(loadRedirects(root)).toEqual([
        { from: '/old', to: '/new', status: 301 },
      ])
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})

describe('matchRedirect', () => {
  const rules = [
    { from: '/old', to: '/new', status: 301 },
    { from: '/login', to: '/signin', status: 302 },
  ] as const

  it('returns the matching rule by exact pathname', () => {
    expect(matchRedirect('/old', rules)).toEqual(rules[0])
    expect(matchRedirect('/login', rules)).toEqual(rules[1])
  })

  it('returns null when no rule matches', () => {
    expect(matchRedirect('/about', rules)).toBeNull()
    expect(matchRedirect('/', rules)).toBeNull()
  })

  it('returns first match when duplicates exist (Netlify semantics)', () => {
    const withDup = [
      { from: '/dup', to: '/first', status: 301 },
      { from: '/dup', to: '/second', status: 302 },
    ]
    expect(matchRedirect('/dup', withDup)).toEqual(withDup[0])
  })
})

describe('createServeHandler — redirect short-circuit', () => {
  it('returns 301/302/etc with Location header when rule matches', async () => {
    const root = makeRoot('/old /new 301\n')
    try {
      const handler = createServeHandler(root, loadRedirects(root))
      const res = await handler(new Request('http://localhost/old'))
      expect(res.status).toBe(301)
      expect(res.headers.get('location')).toBe('/new')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('honors per-rule status (302 != default 301)', async () => {
    const root = makeRoot('/login /signin 302\n')
    try {
      const handler = createServeHandler(root, loadRedirects(root))
      const res = await handler(new Request('http://localhost/login'))
      expect(res.status).toBe(302)
      expect(res.headers.get('location')).toBe('/signin')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('falls through to file serving when no redirect matches', async () => {
    const root = makeRoot('/old /new 301\n')
    // Add an index.html so the directory rewrite has something to
    // serve. We don't assert on the body — just that we got past the
    // redirect check (status 200 OR 404, NOT 3xx).
    writeFileSync(join(root, 'index.html'), '<!doctype html><title>x</title>')
    try {
      const handler = createServeHandler(root, loadRedirects(root))
      const res = await handler(new Request('http://localhost/'))
      expect(res.status).toBe(200)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('redirect check runs BEFORE directory rewriting', async () => {
    // If directory rewriting fired first, `/old` would resolve to
    // `<root>/old/index.html` (file lookup → 404). With redirects
    // checked first, the rule wins regardless of whether the dir
    // exists. Lock this ordering — Netlify / Cloudflare both apply
    // redirects before serving any file.
    const root = makeRoot('/old /new 301\n')
    try {
      const handler = createServeHandler(root, loadRedirects(root))
      const res = await handler(new Request('http://localhost/old'))
      expect(res.status).toBe(301)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('no _redirects file → server runs unchanged (no redirect path executed)', async () => {
    const root = makeRoot() // no _redirects
    writeFileSync(join(root, 'index.html'), '<!doctype html><title>x</title>')
    try {
      const handler = createServeHandler(root, loadRedirects(root))
      const res = await handler(new Request('http://localhost/'))
      // Confirms file path serves and we never hit 3xx.
      expect(res.status).toBe(200)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})

// `ssg.format: 'file' | 'both'` writes a `dist/<route>.html` sibling so
// hosts that don't auto-rewrite slash-less URLs serve `/resume` directly
// (no 301 → `/resume/`). serve-ssg models that host: prefer the `.html`
// sibling over the directory rewrite. This block locks that preference so
// the SSG e2e gates exercise the real no-redirect behaviour.
describe('createServeHandler — file-form (.html) sibling preference', () => {
  it('serves <route>.html directly for a slash-less URL (no redirect, no rewrite)', async () => {
    const root = makeRoot()
    writeFileSync(join(root, 'resume.html'), '<!doctype html><title>FILE-FORM</title>')
    try {
      const handler = createServeHandler(root, [])
      const res = await handler(new Request('http://localhost/resume'))
      expect(res.status).toBe(200)
      expect(await res.text()).toContain('FILE-FORM')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it("prefers <route>.html over <route>/index.html when BOTH exist ('both' format)", async () => {
    const root = makeRoot()
    writeFileSync(join(root, 'resume.html'), '<!doctype html><title>FILE-FORM</title>')
    mkdirSync(join(root, 'resume'))
    writeFileSync(join(root, 'resume', 'index.html'), '<!doctype html><title>DIR-FORM</title>')
    try {
      const handler = createServeHandler(root, [])
      // Slash-less → file form (the no-301 win).
      const slashless = await handler(new Request('http://localhost/resume'))
      expect(await slashless.text()).toContain('FILE-FORM')
      // Trailing-slash → directory form still works (links/sitemap shape).
      const slashed = await handler(new Request('http://localhost/resume/'))
      expect(await slashed.text()).toContain('DIR-FORM')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it("'directory'-only build (no sibling) → directory rewrite, unchanged", async () => {
    const root = makeRoot()
    mkdirSync(join(root, 'resume'))
    writeFileSync(join(root, 'resume', 'index.html'), '<!doctype html><title>DIR-FORM</title>')
    try {
      const handler = createServeHandler(root, [])
      const res = await handler(new Request('http://localhost/resume'))
      expect(res.status).toBe(200)
      expect(await res.text()).toContain('DIR-FORM')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('nested route file form (/blog/post → blog/post.html)', async () => {
    const root = makeRoot()
    mkdirSync(join(root, 'blog'))
    writeFileSync(join(root, 'blog', 'post.html'), '<!doctype html><title>NESTED-FILE</title>')
    try {
      const handler = createServeHandler(root, [])
      const res = await handler(new Request('http://localhost/blog/post'))
      expect(res.status).toBe(200)
      expect(await res.text()).toContain('NESTED-FILE')
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})
