/**
 * Generate the native chart engine — the committed SwiftUI/Compose twin of
 * `@pyreon/charts`' pure geometry engine.
 *
 * Reads the ten engine sources, strips their module plumbing, runs the REAL
 * PMTC transform for both targets, and post-processes the emit into
 * runtime-owned files:
 *
 *   packages/native/runtime-swift/Sources/PyreonRuntime/PyreonChartEngine.swift
 *   packages/native/runtime-kotlin/src/main/kotlin/com/pyreon/runtime/PyreonChartEngine.kt
 *
 * The three draw-list types (`Pt` / `Rect` / `DrawCmd`) are OWNED by the
 * hand-written PyreonChartCanvas files — the generator strips the synthesized
 * declarations and renames every reference to the runtime names
 * (`PyreonChartPt` / `PyreonChartRect` / `PyreonDrawCmd`), so one type serves
 * the geometry and the renderer.
 *
 * ZERO WARNINGS is a hard precondition: a warning here is a construct the
 * compiler silently could not lower, i.e. a gutted function shipped into the
 * runtime — the exact class the descending-loop / logTicks PRs closed. The
 * builder THROWS rather than writing partial output.
 *
 * Determinism: pure function of the engine sources + compiler — an unchanged
 * input regenerates byte-identically (locked by the drift test:
 * src/tests/native-chart-engine-generated.test.ts).
 *
 * Regenerate: bun packages/native/compiler/scripts/gen-chart-engine.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { transform } from '../src/index'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '../../../..')

/** Engine modules, in dependency order (types first — the strip targets). */
export const ENGINE_FILES = [
  'types',
  'format',
  'scale',
  'scale-extra',
  'curve',
  'arc',
  'radar',
  'layout',
  'stack',
  'render',
  'candlestick',
  'heat',
] as const

const RENAMES: ReadonlyArray<readonly [string, string]> = [
  ['Pt', 'PyreonChartPt'],
  ['Rect', 'PyreonChartRect'],
  ['DrawCmd', 'PyreonDrawCmd'],
]

const HEADER = (lang: string) =>
  `// GENERATED by packages/native/compiler/scripts/gen-chart-engine.ts — do not edit.\n` +
  `// Source: packages/fundamentals/charts/src/engine/*.ts (${ENGINE_FILES.length} modules)\n` +
  `// Regenerate: bun packages/native/compiler/scripts/gen-chart-engine.ts\n` +
  `// Pt/Rect/DrawCmd live in PyreonChartCanvas.${lang} (runtime-owned); every\n` +
  `// reference here is renamed to the PyreonChart* runtime types.\n`

/** Concatenate the engine sources with module plumbing stripped. */
export function bundleEngineSource(repoRoot: string = REPO): string {
  const dir = join(repoRoot, 'packages/fundamentals/charts/src/engine')
  let src = ''
  for (const f of ENGINE_FILES) {
    let t = readFileSync(join(dir, `${f}.ts`), 'utf8')
    t = t.replace(/^import[^\n]*\n/gm, '').replace(/^export /gm, '')
    src += `// ---- ${f}.ts ----\n${t}\n`
  }
  return src
}

function renameTypes(code: string): string {
  let out = code
  for (const [from, to] of RENAMES) out = out.replace(new RegExp(`\\b${from}\\b`, 'g'), to)
  return out
}

/** Strip the synthesized Pt/Rect/DrawCmd struct blocks from the Swift emit. */
function stripSwiftStructs(code: string): string {
  let out = code
  for (const name of ['Pt', 'Rect', 'DrawCmd']) {
    // Flat data structs — fields only, no nested braces.
    const re = new RegExp(`struct ${name}(?::[^\\{]*)? \\{[^}]*\\}\\n*`, 'g')
    const before = out
    out = out.replace(re, '')
    if (out === before) throw new Error(`[gen-chart-engine] Swift struct ${name} not found to strip`)
  }
  return out
}

/** Strip the synthesized data classes + @Serializable lines from Kotlin. */
function stripKotlinDecls(code: string): string {
  let out = code
  for (const name of ['Pt', 'Rect', 'DrawCmd']) {
    const re = new RegExp(`^data class ${name}\\([^\\n]*\\)\\n`, 'm')
    const before = out
    out = out.replace(re, '')
    if (out === before) throw new Error(`[gen-chart-engine] Kotlin data class ${name} not found to strip`)
  }
  // The engine is consumed in-process — no serialization dependency.
  out = out.replace(/^@Serializable\n/gm, '')
  return out
}

interface SwiftField {
  name: string
  type: string
  def: string | null
}

/**
 * Publicize the Swift emit for cross-module use. The runtime is an SPM
 * module; PMTC-lowered app code constructs `ChartSpec` and calls
 * `renderChart` from the APP module, and Swift's memberwise init is
 * internal even on a public struct — so every remaining struct gets
 * `public` fields plus an explicit public memberwise init (declaration
 * order, defaults preserved).
 */
function publicizeSwift(code: string): string {
  const lines = code.split('\n')
  const out: string[] = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]!
    const structHead = line.match(/^struct (\w+)((?::| \{).*)$/)
    if (structHead) {
      out.push(`public struct ${structHead[1]}${structHead[2]}`)
      i++
      const fields: SwiftField[] = []
      while (i < lines.length && lines[i] !== '}') {
        // A Swift-keyword field name arrives BACKTICK-ESCAPED from `swiftIdent`
        // (`open` on Ohlc). A `\w+`-only name group silently fails to match it,
        // which cost two defects at once: the field stayed INTERNAL on a public
        // struct, and — because it never reached `fields` — it was omitted from
        // the synthesized memberwise init, so the struct failed to compile with
        // "return from initializer without initializing all stored properties".
        const f = lines[i]!.match(/^(\s+)var (`\w+`|\w+): ([^=]+?)(?: = (.+))?$/)
        if (f) {
          fields.push({ name: f[2]!, type: f[3]!.trim(), def: f[4] ?? null })
          out.push(`${f[1]}public var ${f[2]}: ${f[3]!.trim()}${f[4] ? ` = ${f[4]}` : ''}`)
        } else {
          out.push(lines[i]!)
        }
        i++
      }
      // Explicit public memberwise init before the closing brace.
      if (fields.length > 0) {
        const params = fields
          .map((f) => `${f.name}: ${f.type}${f.def ? ` = ${f.def}` : ''}`)
          .join(', ')
        out.push(`  public init(${params}) {`)
        for (const f of fields) out.push(`    self.${f.name} = ${f.name}`)
        out.push('  }')
      }
      out.push('}')
      i++
      continue
    }
    out.push(
      line
        .replace(/^func /, 'public func ')
        .replace(/^let /, 'public let ')
        .replace(/^enum /, 'public enum '),
    )
    i++
  }
  return out.join('\n')
}

export function buildChartEngine(repoRoot: string = REPO): { swift: string; kotlin: string } {
  const src = bundleEngineSource(repoRoot)
  const outputs: Record<'swift' | 'kotlin', string> = { swift: '', kotlin: '' }
  for (const target of ['swift', 'kotlin'] as const) {
    const r = transform(src, { target })
    if (r.warnings.length > 0) {
      throw new Error(
        `[gen-chart-engine] ${target} emit has ${r.warnings.length} warning(s) — a warning here is a silently-gutted function. First: ${JSON.stringify(r.warnings[0]).slice(0, 300)}`,
      )
    }
    outputs[target] = r.code
  }
  const swift =
    HEADER('swift') + '\nimport Foundation\n\n' + publicizeSwift(renameTypes(stripSwiftStructs(outputs.swift))).trimEnd() + '\n'
  const kotlin =
    HEADER('kt') + 'package com.pyreon.runtime\n\n' + renameTypes(stripKotlinDecls(outputs.kotlin)).trimEnd() + '\n'
  return { swift, kotlin }
}

const SWIFT_OUT = 'packages/native/runtime-swift/Sources/PyreonRuntime/PyreonChartEngine.swift'
const KOTLIN_OUT = 'packages/native/runtime-kotlin/src/main/kotlin/com/pyreon/runtime/PyreonChartEngine.kt'

if (import.meta.main) {
  const { swift, kotlin } = buildChartEngine()
  writeFileSync(join(REPO, SWIFT_OUT), swift)
  writeFileSync(join(REPO, KOTLIN_OUT), kotlin)
  console.log(`[gen-chart-engine] wrote ${SWIFT_OUT} (${swift.length} bytes)`)
  console.log(`[gen-chart-engine] wrote ${KOTLIN_OUT} (${kotlin.length} bytes)`)
}
