import path from 'node:path'
import { emitRuntimeSlugHelper } from './_shared/derive-slug'
import type { ContentConfig } from './types'

// ─── virtual:zero-content/collections module renderer ──────────────────────
//
// Emitted body imports `_setRegistry` from the runtime and registers a
// per-collection metadata bundle. Each collection's loader map uses
// `import.meta.glob` to lazy-load every entry — Vite splits each
// markdown module into a per-route chunk so cold pages don't pull
// content data into the initial bundle.
//
// We rely on Vite's resolution of `import.meta.glob` at consumer build
// time: the path string in the emitted source is a relative path from
// the virtual module's "logical" location (we use the project root for
// stability) to the collection's content dir.

export interface RenderVirtualCollectionsArgs {
  config: ContentConfig
  /** Vite root, used to compute the import.meta.glob path. */
  root: string
}

/**
 * Render the virtual `:zero-content/collections` module body. Pure —
 * the Vite plugin's `load` hook returns this string.
 *
 * @internal exported for testing
 */
export function renderVirtualCollections(
  args: RenderVirtualCollectionsArgs,
): string {
  const collectionEntries = Object.entries(args.config.collections)
  if (collectionEntries.length === 0) {
    return `// Auto-generated by @pyreon/zero-content. No collections defined.
import { _setRegistry } from '@pyreon/zero-content'
_setRegistry({})
`
  }
  const lines: string[] = []
  for (const [name, def] of collectionEntries) {
    const collectionDir = def.path ?? `src/content/${name}`
    // Glob is relative to the importing module. Use absolute path
    // resolved against root so the user's `path` override works
    // regardless of where the virtual module is "located".
    const absDir = path.isAbsolute(collectionDir)
      ? collectionDir
      : path.join(args.root, collectionDir)
    const globPath = '/' + path.relative(args.root, absDir).split(path.sep).join('/') + '/**/*.{md,mdx}'
    lines.push(
      `const __${name}_modules = import.meta.glob(${JSON.stringify(globPath)})`,
    )
  }

  const registryLines: string[] = []
  for (const [name, def] of collectionEntries) {
    const collectionDir = def.path ?? `src/content/${name}`
    const absDir = path.isAbsolute(collectionDir)
      ? collectionDir
      : path.join(args.root, collectionDir)
    const relAbsDir = '/' + path.relative(args.root, absDir).split(path.sep).join('/')
    // Slug derivation matches `deriveSlug` in parse.ts: strip ext + `/index`
    registryLines.push(
      `  ${JSON.stringify(name)}: {
    name: ${JSON.stringify(name)},
    type: ${JSON.stringify(def.type)},
    loaders: Object.fromEntries(
      Object.entries(__${name}_modules).map(([file, loader]) => [
        __zcSlug(file, ${JSON.stringify(relAbsDir)}),
        loader,
      ]),
    ),
  }`,
    )
  }

  return `// Auto-generated by @pyreon/zero-content. Do not edit.
import { _setRegistry } from '@pyreon/zero-content'

${lines.join('\n')}

${emitRuntimeSlugHelper()}

_setRegistry({
${registryLines.join(',\n')}
})

export {}
`
}
