import matter from 'gray-matter'
import remarkDirective from 'remark-directive'
import remarkFrontmatter from 'remark-frontmatter'
import remarkGfm from 'remark-gfm'
import remarkParse from 'remark-parse'
import { unified } from 'unified'
import type { Root } from 'mdast'
import { emitJsx, type EmitOptions } from './emit-jsx'
import { remarkCallout } from './remark-plugins/callout'
import { remarkCodeGroup } from './remark-plugins/codegroup'
import { highlightCode, type HighlighterOptions } from './highlighter'
import type { Heading } from '../types'

// ─── Markdown → Pyreon TSX pipeline ────────────────────────────────────────
//
// One-shot transformer used by the Vite plugin's `transform` hook.
//
// Pipeline:
//   1. gray-matter splits frontmatter (YAML) from the body
//   2. unified + remark-parse + remark-frontmatter parses body → mdast
//   3. emitJsx walks the mdast → Pyreon JSX string + heading list
//   4. wrap into a complete .tsx module shape
//
// PR 2 will plug in remark-gfm + remark-shiki + the custom callout/
// codegroup remark plugins. PR 3 adds remark-mdx for JSX-in-markdown.

export interface CompileResult {
  /** The full `.tsx` module source. */
  code: string
  /** Frontmatter as parsed from YAML. Zod validation happens in PR 4. */
  frontmatter: Record<string, unknown>
  /** Headings list (for the page's `headings` export, drives TOC). */
  headings: Heading[]
  /** Derived slug from the file path. */
  slug: string
}

export interface CompileOptions {
  /**
   * Disable Shiki code highlighting. Useful for tests + situations
   * where highlighting would be redundant (e.g. previewing raw
   * markdown). Default: enabled.
   */
  highlight?: boolean
  /** Shiki theme + language config. */
  highlighter?: HighlighterOptions
}

/**
 * Compile a markdown source string + file id into a Pyreon `.tsx`
 * module. The `id` is the absolute file path Vite passes to
 * `transform`; we use it to derive a stable slug.
 */
export async function compileMarkdown(
  source: string,
  id: string,
  options: CompileOptions = {},
): Promise<CompileResult> {
  // 1. Split frontmatter (uses gray-matter directly — remark-frontmatter
  //    keeps the YAML in the mdast tree but doesn't parse it; gray-matter
  //    parses it as JS values).
  const parsed = matter(source)
  const body = parsed.content
  const frontmatter = parsed.data as Record<string, unknown>

  // 2. Build the unified pipeline. Order matters:
  //      parse → frontmatter → gfm → directive → custom (callout/codegroup)
  //    `parse` produces mdast; the rest are transformers that walk it.
  const processor = unified()
    .use(remarkParse)
    .use(remarkFrontmatter, ['yaml'])
    .use(remarkGfm)
    .use(remarkDirective)
    .use(remarkCallout)
    .use(remarkCodeGroup)

  // `parse` (sync) → `run` (async; lets remark plugins return promises
  // for future Shiki-as-remark-plugin moves). Currently all our plugins
  // are sync so the await is cheap.
  const raw = processor.parse(body) as Root
  const tree = (await processor.run(raw)) as Root

  // 3. Build emit options (Shiki highlight callback if enabled).
  const emitOpts: EmitOptions = {}
  if (options.highlight !== false) {
    emitOpts.highlight = (code, lang) => highlightCode(code, lang, options.highlighter)
  }

  // 4. Walk → JSX string + heading capture.
  const { body: jsxBody, headings } = await emitJsx(tree, emitOpts)

  // 4. Derive a stable slug. The file `id` is the absolute path Vite
  //    passes; pick whatever comes after `/content/` (the documented
  //    convention) or fall back to the filename stem.
  const slug = deriveSlug(id)

  // 5. Wrap into a complete TSX module. The module exports:
  //      - `default` — the page component
  //      - `frontmatter` — parsed YAML, typed by zod at PR 4
  //      - `headings` — for the TOC
  //      - `slug` — for the catch-all route
  const code = renderTsxModule({
    body: jsxBody,
    frontmatter,
    headings,
    slug,
  })

  return { code, frontmatter, headings, slug }
}

function renderTsxModule(opts: {
  body: string
  frontmatter: Record<string, unknown>
  headings: Heading[]
  slug: string
}): string {
  const fm = JSON.stringify(opts.frontmatter, null, 2)
  const hd = JSON.stringify(opts.headings, null, 2)
  const sg = JSON.stringify(opts.slug)
  return `// Generated by @pyreon/zero-content. Do not edit.
export const frontmatter = ${fm}
export const headings = ${hd}
export const slug = ${sg}

export default function ContentPage() {
  return (
    <article class="content">
${indent(opts.body, '      ')}
    </article>
  )
}
`
}

/**
 * Derive a slug from an absolute file path. Strips the leading path
 * up to and including a `/content/` segment when present; falls back
 * to the basename. Strips the `.md` / `.mdx` extension.
 *
 * Examples:
 *   /abs/project/src/content/docs/zero.md  → docs/zero
 *   /abs/project/src/content/index.md       → index
 *   /abs/project/random.md                   → random
 *
 * Implemented with string ops rather than a `/[/]content[/](.+?)\\.(md|mdx)$/i`
 * regex so adversarial paths with many `/content/` segments can't trigger
 * polynomial backtracking (ReDoS). All work is O(n) length walks.
 *
 * @internal exported for testing
 */
export function deriveSlug(absPath: string): string {
  const normalized = absPath.split('\\').join('/')
  const stripped = stripMdExtension(normalized)
  if (stripped === null) {
    // No `.md` / `.mdx` extension — fall back to the basename verbatim.
    return basename(normalized)
  }
  // Look for the FIRST `/content/` segment (case-insensitive) and trim
  // everything up to + including it. `lastIndexOf` would be safer against
  // accidental `/content/` in user directories, but the convention is
  // `src/content/...` so the first match is correct.
  const lower = stripped.toLowerCase()
  const marker = '/content/'
  const idx = lower.indexOf(marker)
  if (idx >= 0) {
    let body = stripped.slice(idx + marker.length)
    // Strip a trailing `/index` (so `docs/index.md` → `docs`) or a bare
    // `index` (so `content/index.md` → '').
    if (body.endsWith('/index')) body = body.slice(0, -'/index'.length)
    else if (body === 'index') body = ''
    return body
  }
  return basename(stripped)
}

/** Last path segment of `/foo/bar` → `bar`. Empty input → empty. */
function basename(path: string): string {
  const idx = path.lastIndexOf('/')
  return idx >= 0 ? path.slice(idx + 1) : path
}

/**
 * Strip a `.md` / `.mdx` suffix (case-insensitive). Returns the path
 * without the extension when one matched; `null` when no match.
 */
function stripMdExtension(path: string): string | null {
  const dotIdx = path.lastIndexOf('.')
  if (dotIdx < 0) return null
  const ext = path.slice(dotIdx + 1).toLowerCase()
  if (ext === 'md' || ext === 'mdx') return path.slice(0, dotIdx)
  return null
}

/**
 * Indent every line of `text` by `prefix`. Used to pretty-print JSX
 * inside the wrapping `<article>`.
 */
function indent(text: string, prefix: string): string {
  if (!text) return ''
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? line : prefix + line))
    .join('\n')
}
