import matter from 'gray-matter'
import remarkFrontmatter from 'remark-frontmatter'
import remarkParse from 'remark-parse'
import { unified } from 'unified'
import type { Root } from 'mdast'
import { emitJsx } from './emit-jsx'
import type { Heading } from '../types'

// ─── Markdown → Pyreon TSX pipeline ────────────────────────────────────────
//
// One-shot transformer used by the Vite plugin's `transform` hook.
//
// Pipeline:
//   1. gray-matter splits frontmatter (YAML) from the body
//   2. unified + remark-parse + remark-frontmatter parses body → mdast
//   3. emitJsx walks the mdast → Pyreon JSX string + heading list
//   4. wrap into a complete .tsx module shape
//
// PR 2 will plug in remark-gfm + remark-shiki + the custom callout/
// codegroup remark plugins. PR 3 adds remark-mdx for JSX-in-markdown.

export interface CompileResult {
  /** The full `.tsx` module source. */
  code: string
  /** Frontmatter as parsed from YAML. Zod validation happens in PR 4. */
  frontmatter: Record<string, unknown>
  /** Headings list (for the page's `headings` export, drives TOC). */
  headings: Heading[]
  /** Derived slug from the file path. */
  slug: string
}

/**
 * Compile a markdown source string + file id into a Pyreon `.tsx`
 * module. The `id` is the absolute file path Vite passes to
 * `transform`; we use it to derive a stable slug.
 */
export function compileMarkdown(source: string, id: string): CompileResult {
  // 1. Split frontmatter (uses gray-matter directly — remark-frontmatter
  //    keeps the YAML in the mdast tree but doesn't parse it; gray-matter
  //    parses it as JS values).
  const parsed = matter(source)
  const body = parsed.content
  const frontmatter = parsed.data as Record<string, unknown>

  // 2. Parse the body to mdast. remark-frontmatter is included so any
  //    leftover frontmatter inside the body (rare) doesn't pollute
  //    the tree as a paragraph.
  const processor = unified().use(remarkParse).use(remarkFrontmatter, ['yaml'])
  const tree = processor.parse(body) as Root

  // 3. Walk → JSX string + heading capture.
  const { body: jsxBody, headings } = emitJsx(tree)

  // 4. Derive a stable slug. The file `id` is the absolute path Vite
  //    passes; pick whatever comes after `/content/` (the documented
  //    convention) or fall back to the filename stem.
  const slug = deriveSlug(id)

  // 5. Wrap into a complete TSX module. The module exports:
  //      - `default` — the page component
  //      - `frontmatter` — parsed YAML, typed by zod at PR 4
  //      - `headings` — for the TOC
  //      - `slug` — for the catch-all route
  const code = renderTsxModule({
    body: jsxBody,
    frontmatter,
    headings,
    slug,
  })

  return { code, frontmatter, headings, slug }
}

function renderTsxModule(opts: {
  body: string
  frontmatter: Record<string, unknown>
  headings: Heading[]
  slug: string
}): string {
  const fm = JSON.stringify(opts.frontmatter, null, 2)
  const hd = JSON.stringify(opts.headings, null, 2)
  const sg = JSON.stringify(opts.slug)
  return `// Generated by @pyreon/zero-content. Do not edit.
export const frontmatter = ${fm}
export const headings = ${hd}
export const slug = ${sg}

export default function ContentPage() {
  return (
    <article class="content">
${indent(opts.body, '      ')}
    </article>
  )
}
`
}

/**
 * Derive a slug from an absolute file path. Strips the leading path
 * up to and including a `/content/` segment when present; falls back
 * to the basename. Strips the `.md` / `.mdx` extension.
 *
 * Examples:
 *   /abs/project/src/content/docs/zero.md  → docs/zero
 *   /abs/project/src/content/index.md       → index
 *   /abs/project/random.md                   → random
 *
 * @internal exported for testing
 */
export function deriveSlug(absPath: string): string {
  const normalized = absPath.replace(/\\/g, '/')
  const contentSegment = normalized.match(/[/]content[/](.+?)\.(md|mdx)$/i)
  if (contentSegment) {
    return contentSegment[1]!.replace(/[/]?index$/, '')
  }
  const basename = normalized.split('/').pop() ?? ''
  return basename.replace(/\.(md|mdx)$/i, '')
}

/**
 * Indent every line of `text` by `prefix`. Used to pretty-print JSX
 * inside the wrapping `<article>`.
 */
function indent(text: string, prefix: string): string {
  if (!text) return ''
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? line : prefix + line))
    .join('\n')
}
