import { existsSync, readdirSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'
import type { Plugin } from 'vite'

import type { IconMode } from './icon'

// ─── iconsPlugin — folder → strictly-typed icon set ─────────────────────────
//
// Point it at a folder of `*.svg` files; it writes a generated `icons.gen.tsx`
// that exports a strictly-typed `<Icon name="…" />`. Add an svg → the `name`
// union widens; remove one → a now-invalid `name` fails typecheck. The
// generated file calls `createNamedIcon(REGISTRY)` so `keyof typeof REGISTRY`
// IS the type surface (autocomplete + real go-to-definition, zero per-app
// wiring — same one-touch shape as fs-router / islands auto-registry).
//
// Two render modes (per the colorful-vs-system split):
//   • mode: 'inline' (default) — system icons. Each svg inlined as raw markup;
//     `currentColor`-themeable, recolor via CSS `color`.
//   • mode: 'image'            — colorful / brand icons. Each svg emitted as a
//     static asset, rendered `<img>`. NO mutation, original colors preserved.
//
//   import { iconsPlugin } from '@pyreon/zero/server'
//   iconsPlugin({ dir: './src/icons' })            // → src/icons.gen.tsx
//   // app:
//   import { Icon } from './icons.gen'
//   <span style="width:2rem"><Icon name="check-circle" /></span>

export interface IconsPluginConfig {
  /** Folder of `*.svg` files to scan (relative to project root or absolute). */
  dir: string
  /**
   * Where to write the generated `.tsx`. Default: `icons.gen.tsx` next to
   * `dir` (e.g. `dir: src/icons` → `src/icons.gen.tsx`). Recommend
   * gitignoring it — it's a build artifact.
   */
  out?: string
  /**
   * `'inline'` (default — system icons, `currentColor`-themeable) or
   * `'image'` (colorful / brand icons, rendered `<img>`, no mutation).
   */
  mode?: IconMode
}

/** Filename stem → registry key. `Check-Circle.svg` → `check-circle`. */
export function iconNameFromFile(file: string): string {
  return basename(file, '.svg')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
}

/** Registry key → safe JS import binding. `check-circle` → `checkCircle`. */
function bindingFromName(name: string): string {
  const camel = name.replace(/[-/](.)/g, (_, c: string) => c.toUpperCase())
  const safe = camel.replace(/[^A-Za-z0-9_$]/g, '_')
  return /^[A-Za-z_$]/.test(safe) ? safe : `_${safe}`
}

/** List the `*.svg` filenames in `dir` (sorted, stable). Empty if missing. */
export function scanIconDir(dir: string): string[] {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort()
}

/**
 * Render the generated `.tsx` source for a set of svg filenames. Pure —
 * unit-tested directly; the plugin only adds fs + watch around it.
 */
export function generateIconSetSource(
  files: string[],
  opts: { mode: IconMode; importDir: string },
): string {
  const query = opts.mode === 'image' ? '' : '?raw'
  const seen = new Map<string, string>() // binding → name (collision guard)
  const entries: { key: string; binding: string; file: string }[] = []
  for (const file of files) {
    const key = iconNameFromFile(file)
    let binding = bindingFromName(key)
    while (seen.has(binding)) binding = `${binding}_`
    seen.set(binding, key)
    entries.push({ key, binding, file })
  }

  const header = [
    '// AUTO-GENERATED by @pyreon/zero iconsPlugin — do not edit.',
    `// Add / remove .svg files in ${opts.importDir} and this regenerates.`,
    '/// <reference types="vite/client" />',
    "import { createNamedIcon } from '@pyreon/zero'",
  ]
  const imports = entries.map(
    (e) => `import ${e.binding} from '${opts.importDir}/${e.file}${query}'`,
  )
  const registry = [
    'const REGISTRY = {',
    ...entries.map((e) => `  ${JSON.stringify(e.key)}: ${e.binding},`),
    '} as const',
  ]
  const tail = [
    'export type IconName = keyof typeof REGISTRY',
    `export const Icon = createNamedIcon(REGISTRY${
      opts.mode === 'image' ? ", { mode: 'image' }" : ''
    })`,
    '',
  ]
  return [...header, '', ...imports, '', ...registry, '', ...tail].join('\n')
}

function resolveOut(cfg: IconsPluginConfig, root: string): string {
  const dir = join(root, cfg.dir)
  const out = cfg.out
    ? join(root, cfg.out)
    : join(dirname(dir), `${basename(dir)}.gen.tsx`)
  return out
}

/**
 * Vite plugin: scan `dir` for `*.svg`, write a strictly-typed
 * `icons.gen.tsx`, regenerate on add / unlink in dev.
 */
export function iconsPlugin(cfg: IconsPluginConfig): Plugin {
  let root = process.cwd()
  const mode: IconMode = cfg.mode ?? 'inline'

  async function regenerate(): Promise<void> {
    const dir = join(root, cfg.dir)
    const out = resolveOut(cfg, root)
    // Import paths in the generated file are relative to the file's dir.
    const importDir = relative(dirname(out), dir).split('\\').join('/')
    const prefixed = importDir.startsWith('.') ? importDir : `./${importDir}`
    const source = generateIconSetSource(scanIconDir(dir), {
      mode,
      importDir: prefixed,
    })
    // Idempotent — never rewrite identical content (avoids an HMR loop).
    const current = existsSync(out) ? await readFile(out, 'utf8') : null
    if (current !== source) await writeFile(out, source, 'utf8')
  }

  return {
    name: 'pyreon:zero-icons',
    async configResolved(resolved) {
      root = resolved.root
      await regenerate()
    },
    async buildStart() {
      await regenerate()
    },
    configureServer(server) {
      const dir = join(root, cfg.dir)
      server.watcher.add(dir)
      const onChange = (file: string): void => {
        if (file.toLowerCase().endsWith('.svg') && file.startsWith(dir)) {
          void regenerate()
        }
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
