/**
 * Client-side service-worker registration for `zero({ pwa })`.
 * Client-safe: no Node imports, no-op on the server and in development.
 */

declare const __ZERO_BASE__: string

/** Options for {@link registerServiceWorker}. */
export interface RegisterServiceWorkerOptions {
  /**
   * Worker URL. Default: `<base>sw.js` (what `zero({ pwa })` generates).
   */
  url?: string
  /** Registration scope. Default: the app base. */
  scope?: string
  /**
   * A new worker finished installing and is WAITING (only happens when
   * `pwa.skipWaiting` is off, the default). Call `activate()` to switch —
   * the page reloads once the new worker takes control. Not calling it
   * keeps the current version until every tab closes.
   */
  onUpdate?: (activate: () => void) => void
}

function appBase(): string {
  const b = typeof __ZERO_BASE__ !== 'undefined' && __ZERO_BASE__ ? __ZERO_BASE__ : '/'
  return b.endsWith('/') ? b : `${b}/`
}

/**
 * Register the service worker generated by `zero({ pwa })`.
 *
 * Resolves `null` (and registers nothing) during SSR, in development (a
 * caching worker in dev serves stale modules and fights HMR), and in
 * browsers without service-worker support.
 *
 * @example
 * ```ts
 * // src/entry-client.ts
 * import { registerServiceWorker } from '@pyreon/zero'
 *
 * registerServiceWorker({
 *   onUpdate: (activate) => {
 *     if (confirm('A new version is available. Reload?')) activate()
 *   },
 * })
 * ```
 */
export async function registerServiceWorker(
  options: RegisterServiceWorkerOptions = {},
): Promise<ServiceWorkerRegistration | null> {
  if (process.env.NODE_ENV !== 'production') return null
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return null

  const base = appBase()
  const container = navigator.serviceWorker
  const registration = await container.register(options.url ?? `${base}sw.js`, {
    scope: options.scope ?? base,
    // Always revalidate the worker script itself against the network.
    updateViaCache: 'none',
  })

  const onUpdate = options.onUpdate
  if (onUpdate) {
    const offer = (worker: ServiceWorker): void => {
      onUpdate(() => {
        container.addEventListener('controllerchange', () => location.reload(), { once: true })
        worker.postMessage({ type: 'SKIP_WAITING' })
      })
    }
    // Only an UPDATE (an existing controller) is offered — a first install
    // has nothing to replace.
    if (registration.waiting && container.controller) offer(registration.waiting)
    registration.addEventListener('updatefound', () => {
      const installing = registration.installing
      if (!installing) return
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed' && container.controller) offer(installing)
      })
    })
  }
  return registration
}
