/**
 * Typed route paths — build-time codegen + the type registry it augments.
 *
 * Closes the "`<Link href>` is just `string`" DX gap: a generated `.d.ts`
 * augments `RegisteredRoutes` with every route path + its params, so `href` /
 * `navigate` autocomplete valid paths and reject typos at compile time — the
 * TanStack-Router / SvelteKit / Next-typed-routes bar, via the standard
 * module-augmentation-of-a-registry-interface pattern.
 *
 * Two halves:
 *   - the TYPES (`RegisteredRoutes` / `RoutePath` / `RouteParams`) — shipped here,
 *     empty by default so an app with no generated file falls back to `string`
 *     (never breaks existing code);
 *   - the CODEGEN (`generateRouteTypes`) — a pure function the vite plugin runs
 *     over the fs-router paths to emit the augmenting `.d.ts`.
 */

/**
 * The route registry. Empty by default; the generated `.d.ts`
 * (`@pyreon/zero`'s plugin writes it) augments this with one entry per route,
 * mapping the route path to its params shape:
 *
 * ```ts
 * declare module '@pyreon/zero' {
 *   interface RegisteredRoutes {
 *     '/': Record<string, never>
 *     '/posts/:id': { id: string }
 *   }
 * }
 * ```
 */
// oxlint-disable-next-line no-empty-interface -- augmentation target; empty by design
export interface RegisteredRoutes {}

/**
 * The union of registered route paths — or `string` when no routes have been
 * generated yet (so typing stays permissive in a fresh project / before the
 * first build).
 */
export type RoutePath = keyof RegisteredRoutes extends never
  ? string
  : keyof RegisteredRoutes & string

/** The params shape for a given route path (`{}` when unknown). */
export type RouteParams<P extends RoutePath> = P extends keyof RegisteredRoutes
  ? RegisteredRoutes[P]
  : Record<string, string>

/**
 * A route path that autocompletes the registered routes but still accepts any
 * string — so `href`/`to` get IDE completion + typo-rejection on known routes
 * WITHOUT breaking dynamic / runtime-constructed paths. This is the type to use
 * on `LinkProps.href` etc.
 */
export type RouteHref = RoutePath | (string & {})

// ─── Codegen ─────────────────────────────────────────────────────────────────

/**
 * Extract the param names from a route path. `:id` → `id`; the catch-all
 * `:slug*` → `slug`. Returns the names in path order (deduped).
 */
export function extractRouteParams(path: string): string[] {
  const names: string[] = []
  const seen = new Set<string>()
  for (const seg of path.split('/')) {
    if (seg.startsWith(':')) {
      const name = seg.slice(1).replace(/\*$/, '') // strip the catch-all marker
      if (name && !seen.has(name)) {
        seen.add(name)
        names.push(name)
      }
    }
  }
  return names
}

/**
 * Emit the `.d.ts` that augments `RegisteredRoutes` from a list of route paths
 * (the fs-router's `urlPath`s, e.g. `/`, `/about`, `/posts/:id`, `/blog/:slug*`).
 * Pure — the vite plugin writes the returned source to a generated file the
 * app's tsconfig includes.
 */
export function generateRouteTypes(
  routePaths: readonly string[],
  opts: { module?: string } = {},
): string {
  const module = opts.module ?? '@pyreon/zero'
  const unique = [...new Set(routePaths)].sort()
  const entries = unique
    .map((p) => {
      const params = extractRouteParams(p)
      const shape =
        params.length === 0
          ? 'Record<string, never>'
          : `{ ${params.map((k) => `${k}: string`).join('; ')} }`
      return `    ${JSON.stringify(p)}: ${shape}`
    })
    .join('\n')
  return [
    `// Auto-generated by @pyreon/zero (typed routes). Do not edit.`,
    `declare module ${JSON.stringify(module)} {`,
    `  interface RegisteredRoutes {`,
    entries,
    `  }`,
    `}`,
    `export {}`,
    ``,
  ].join('\n')
}
