import { expect, test } from '@playwright/test'

/**
 * The generated client, exercised end-to-end.
 *
 * Every request this app makes is issued by code `lathe generate` produced from
 * `openapi.yaml`. The app declares no URL, no method, no query key and no
 * response type — so a failure here means the GENERATOR is wrong, which is the
 * only reason this gate exists.
 *
 * Real HTTP against Vite dev middleware rather than a mock transport: a mock
 * would prove the components render while saying nothing about whether the
 * generated URL, method or decode are correct, which is the whole product.
 */
test.describe('lathe / bookshelf', () => {
  test('renders a list fetched through a generated query hook', async ({ page }) => {
    const errors: string[] = []
    page.on('console', (m) => {
      if (m.type() === 'error') errors.push(m.text())
    })
    page.on('pageerror', (e) => errors.push(e.message))

    await page.goto('/')
    await expect(page.getByTestId('book-list')).toBeVisible()

    // Two books, from the spec-shaped endpoint the generator wired up.
    const items = page.getByTestId('book-item')
    await expect(items).toHaveCount(2)
    await expect(page.getByTestId('books-error')).toHaveCount(0)
    await expect(items.first()).toContainText('The Left Hand of Darkness')

    // Fields decode with their spec types: `status` is an enum, `pages` an
    // integer. A response typed `unknown` would render an empty string here.
    await expect(page.getByTestId('book-status').first()).toHaveText('available')
    await expect(page.getByTestId('book-pages').first()).toHaveText('304')

    expect(errors).toEqual([])
  })

  test('a second tag gets its own generated module and its own query', async ({ page }) => {
    // Proves the per-tag split wires up independently — a single-tag spec would
    // pass a naive version of this suite while the grouping was broken.
    await page.goto('/')
    await expect(page.getByTestId('author-item')).toHaveCount(2)
    await expect(page.getByTestId('author-list')).toContainText('Ursula K. Le Guin')
  })

  test('a path-parameter query refetches when its accessor changes', async ({ page }) => {
    // The reactive half of the contract. The generated hook takes an ACCESSOR,
    // so writing the signal must move the query key and issue a NEW request —
    // a hook that captured its arguments once would show the first title
    // forever, and the list assertions above would not notice.
    await page.goto('/')
    await expect(page.getByTestId('detail-empty')).toBeVisible()

    const requests: string[] = []
    page.on('request', (r) => {
      if (r.url().includes('/v1/books/')) requests.push(r.url())
    })

    await page.getByTestId('book-6f1c2b7e-0000-4000-8000-000000000001').click()
    await expect(page.getByTestId('detail-title')).toHaveText('The Left Hand of Darkness')

    await page.getByTestId('book-6f1c2b7e-0000-4000-8000-000000000002').click()
    await expect(page.getByTestId('detail-title')).toHaveText('Piranesi')

    // Two distinct ids were fetched: the accessor really is re-read.
    expect(new Set(requests).size).toBe(2)
  })

  test('a mutation invalidates through a key derived from the endpoint', async ({ page }) => {
    // The whole loop: a generated mutation posts, and a generated query key
    // invalidates the list so it refetches. Nothing in the app writes a URL, a
    // method or a cache key -- a hand-written `['GET', '/books']` would drift
    // from the endpoint the moment the path changed, with nothing to catch it.
    await page.goto('/')
    await expect(page.getByTestId('book-item')).toHaveCount(2)

    await page.getByTestId('add-book').click()

    await expect(page.getByTestId('book-item')).toHaveCount(3)
    await expect(page.getByTestId('book-list')).toContainText('Added by the generated mutation')
  })

  test('the committed generated output is not stale', async ({ page }) => {
    // A generated client that has drifted from its spec is worse than no
    // client, because it still looks authoritative. `lathe check` is the CI
    // half of that contract; this asserts the app under test is running
    // against output the current spec actually produces.
    await page.goto('/')
    const banner = await page.evaluate(async () => {
      const res = await fetch('/src/gen/client.ts')
      return res.ok ? await res.text() : ''
    })
    expect(banner).toContain('@generated by @pyreon/lathe')
    expect(banner).toContain('http://localhost:5199/v1')
  })
})
