/**
 * Deployment-adapter application. Per-adapter files (vercel.json,
 * wrangler.toml, Dockerfile, ...) live in
 * `templates/_shared/_adapters/<adapter>/` as REAL files — the scaffolder
 * copies the overlay. Netlify's `netlify.toml` is the exception: its
 * correct content depends on the RENDER MODE (SSR modes deploy the
 * adapter-staged `dist/publish` + `dist/netlify/functions`; SSG/SPA
 * deploy the `dist` root), so it's generated by `generateNetlifyToml`
 * instead of copied. Each adapter still declares its vite-side factory
 * (used by `generateViteConfig`), README badge markdown, and env-var
 * keys here.
 *
 * CONTRACT: every deploy path written here (and in the overlay files)
 * must match the `@pyreon/zero` adapters' output-path constants
 * (`*_ADAPTER_OUTPUT` in `zero/src/adapters/contract.ts`). Locked by
 * `tests/adapter-contract.test.ts`, which imports those constants and
 * runs each `apply()` — the scaffolder deliberately does NOT carry
 * `@pyreon/zero` as a runtime dependency, so the literals live here and
 * the test is the drift gate.
 */

import { writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { copyOverlay } from './template-engine'
import type { AdapterId, ProjectConfig, RenderMode } from './templates'

const SHARED_ADAPTERS_ROOT = resolve(
  import.meta.dirname,
  '..',
  'templates',
  '_shared',
  '_adapters',
)

export interface AdapterGen {
  id: AdapterId
  /** Source-side import name from `@pyreon/zero/server`. */
  viteFactory: string | null
  /** Write all platform-specific files into `targetDir`. */
  apply(config: ProjectConfig): Promise<void>
  /** README badge markdown — empty string if the adapter has no one-click. */
  badge(config: ProjectConfig): string
  /** Env-var keys the user needs to set in the platform's dashboard. */
  envKeys(config: ProjectConfig): string[]
}

function overlayApply(adapter: AdapterId) {
  return async (config: ProjectConfig): Promise<void> => {
    const overlayDir = join(SHARED_ADAPTERS_ROOT, adapter)
    // Most adapters have no placeholders; cloudflare's wrangler.toml uses
    // {{slug}}. Pass the slug always — unused placeholders no-op.
    await copyOverlay(overlayDir, config.targetDir, { slug: slug(config.name) })
  }
}

const vercel: AdapterGen = {
  id: 'vercel',
  viteFactory: 'vercelAdapter',
  apply: overlayApply('vercel'),
  badge() {
    return '[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=)'
  },
  envKeys() {
    return []
  },
}

const cloudflare: AdapterGen = {
  id: 'cloudflare',
  viteFactory: 'cloudflareAdapter',
  apply: overlayApply('cloudflare'),
  badge() {
    return '[![Deploy to Cloudflare](https://deploy.workers.cloudflare.com/button)](https://deploy.workers.cloudflare.com/?url=)'
  },
  envKeys() {
    return []
  },
}

/**
 * Render the root `netlify.toml` for a project's render mode.
 *
 * Netlify reads THIS file (the repo root) for builds — the
 * `dist/netlify.toml` the netlify ADAPTER writes is relative to `dist`
 * and only applies to direct `netlify deploy --dir` flows. The paths
 * here are the adapter's staged output, `dist/`-prefixed:
 *
 *   - SSR/ISR: client → `dist/publish`, function `ssr.mjs` →
 *     `dist/netlify/functions` (see `NETLIFY_ADAPTER_OUTPUT` in
 *     `@pyreon/zero`), redirect everything to `/.netlify/functions/ssr`
 *     (static files still win — `force` defaults to false, and the
 *     function declares `preferStatic`).
 *   - SSG: the prerendered site IS `dist` (per-route HTML + the
 *     ssgPlugin's `_redirects`); no functions.
 *   - SPA: `dist` + the standard SPA fallback rewrite.
 *
 * Exported for the adapter-contract test.
 */
export function generateNetlifyToml(renderMode: RenderMode): string {
  const header = `# Generated by create-pyreon-app for mode "${renderMode}".
# Paths follow @pyreon/zero's netlify adapter output contract
# (NETLIFY_ADAPTER_OUTPUT) — locked by create-zero's adapter-contract test.
`
  const assetHeaders = `[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
`
  if (renderMode === 'ssg') {
    return `${header}[build]
  command = "bun run build"
  publish = "dist"

${assetHeaders}`
  }
  if (renderMode === 'spa') {
    return `${header}[build]
  command = "bun run build"
  publish = "dist"

${assetHeaders}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`
  }
  // ssr-stream | ssr-string | isr — the netlify adapter stages the
  // deployable tree during `bun run build` (zero's ssr-plugin post-step).
  return `${header}[build]
  command = "bun run build"
  publish = "dist/publish"

[functions]
  directory = "dist/netlify/functions"
  node_bundler = "esbuild"

${assetHeaders}
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
`
}

const netlify: AdapterGen = {
  id: 'netlify',
  viteFactory: 'netlifyAdapter',
  async apply(config: ProjectConfig): Promise<void> {
    await writeFile(
      join(config.targetDir, 'netlify.toml'),
      generateNetlifyToml(config.renderMode),
    )
  },
  badge() {
    return '[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=)'
  },
  envKeys() {
    return []
  },
}

/**
 * node/bun apply — the overlay is an SSR-runner Dockerfile whose
 * `CMD` runs the adapter-emitted entry (`dist/index.js` / `dist/index.ts`).
 * That entry only exists when the adapter RUNS, which it does for SSR/ISR
 * builds but NOT for `spa` mode (SPA ships a static client bundle only — no
 * `adapter.build()` call, no server entry). So for `spa` we DON'T copy the
 * Dockerfile overlay: a container CMD'ing a file that was never emitted
 * would crash at startup, which is worse than shipping no Dockerfile. A SPA
 * is static — deploy it to any static host, or use the `static` adapter.
 * The adapter-contract test locks both branches (Dockerfile present + runs
 * the emitted runner for SSR; absent for SPA).
 */
function serverRunnerApply(adapter: 'node' | 'bun') {
  const copy = overlayApply(adapter)
  return async (config: ProjectConfig): Promise<void> => {
    if (config.renderMode === 'spa') return
    await copy(config)
  }
}

const node: AdapterGen = {
  id: 'node',
  viteFactory: 'nodeAdapter',
  apply: serverRunnerApply('node'),
  badge() {
    return ''
  },
  envKeys() {
    return ['PORT']
  },
}

const bun: AdapterGen = {
  id: 'bun',
  viteFactory: 'bunAdapter',
  apply: serverRunnerApply('bun'),
  badge() {
    return ''
  },
  envKeys() {
    return ['PORT']
  },
}

const staticAdapter: AdapterGen = {
  id: 'static',
  viteFactory: null,
  async apply() {
    // Intentional no-op: `dist/` after `bun run build` is the entire site.
    // No platform files to copy.
  },
  badge() {
    return ''
  },
  envKeys() {
    return []
  },
}

export const ADAPTERS: Record<AdapterId, AdapterGen> = {
  vercel,
  cloudflare,
  netlify,
  node,
  bun,
  static: staticAdapter,
}

export function adapterFor(id: AdapterId): AdapterGen {
  return ADAPTERS[id]
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '')
}
