/**
 * `atlas init` — write the config the workspace already implies.
 *
 * ── Why a command, when detection is automatic ────────────────────────────
 *
 * Auto-detection (see `autoDetectProjects`) makes a monorepo work with no
 * config at all. This exists for the moment after that: the detected list is a
 * GUESS, and the first thing anyone wants to do is adjust it — rename a group,
 * drop the internal package, pin an order. Editing a guess requires the guess
 * to be written down.
 *
 * It is also the honest answer to "what did it decide?". A detection you cannot
 * see is a detection you cannot argue with, and a wrong one is then very hard
 * to explain.
 *
 * ── What it deliberately does NOT do ──────────────────────────────────────
 *
 * It writes no story files, and there is no `--generate-stories`. A per
 * component file restating props the component already declares is the thing
 * Atlas exists not to need: it drifts the moment the component changes, and
 * nothing tells you. Scenarios are derived. The only file worth writing is this
 * one, and only for what derivation cannot know.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'
import { detectProjects, projectNameFor, type DetectedProject } from '../discover/workspace'
import { discoverComponents } from '../discover'

/** Filenames `loadAtlasConfig` accepts, in the order it tries them. */
const CONFIG_CANDIDATES = [
  'pyreon.config.ts',
  'pyreon.config.tsx',
  'pyreon.config.mjs',
  'pyreon.config.js',
  'atlas.config.tsx',
  'atlas.config.ts',
  'atlas.config.mjs',
  'atlas.config.js',
]

export interface InitOptions {
  /** Project root (default `.`). */
  cwd?: string
  /** Directory within each package to scan (default `src`). */
  dir?: string
  /** Overwrite an existing config. */
  force?: boolean
  /** Print what would be written without writing it. */
  dryRun?: boolean
  /** Site title; defaults to the root package name, title-cased. */
  title?: string
  /** Injected for tests. */
  detect?: typeof detectProjects
  /** Injected for tests. */
  hasComponents?: (dir: string) => boolean
  /** Reads the root package.json name. Injected for tests. */
  readRootName?: (root: string) => string
}

export type InitResult =
  | { kind: 'written'; path: string; source: string; projects: readonly DetectedProject[]; title: string }
  | { kind: 'dry-run'; path: string; source: string; projects: readonly DetectedProject[]; title: string }
  /** A config already exists and `--force` was not passed. */
  | { kind: 'exists'; path: string }
  /** Nothing to write about — no workspace packages and no local components. */
  | { kind: 'nothing-found'; searched: string }

/** The config file already present, if any. */
export function findExistingConfig(root: string): string | undefined {
  return CONFIG_CANDIDATES.map((name) => join(root, name)).find((file) => existsSync(file))
}

// A static import, NOT `require`: this package is `type: module`, so `require`
// is undefined in any real ESM consumer — the failure would be a hard
// ReferenceError the moment someone ran `atlas init` outside a bundler.
const readName = (root: string): string => {
  try {
    const parsed = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { name?: unknown }
    return typeof parsed.name === 'string' ? parsed.name : ''
  } catch {
    return ''
  }
}

/**
 * Render the config.
 *
 * Emitted as source a person will edit, not as minimal JSON: the comments are
 * the point. Someone opening this file wants to know where the list came from
 * and that changing it is expected, which a bare array does not say.
 */
export function renderConfig(title: string, projects: readonly DetectedProject[]): string {
  const lines: string[] = [
    '/**',
    ' * Pyreon configuration — one file, a section per package.',
    ' *',
    ' * Generated by `atlas init` from this workspace. Everything here is a',
    ' * starting point — edit freely; nothing regenerates it.',
    ' *',
    ' * Components, their controls and their scenarios are DERIVED from your',
    ' * source, so there are no story files to write or keep in sync. This file',
    ' * is only for what derivation cannot know.',
    ' */',
    'export default {',
    '  atlas: {',
    `    title: ${JSON.stringify(title)},`,
    '',
  ]

  if (projects.length > 0) {
    lines.push(
      '    // Scanned into one catalog, each package filed under its own name.',
      '    // Two packages may both export a `Button`: they stay distinct as',
      '    // `Core/Button` and `Admin/Button`.',
      '    projects: [',
    )
    for (const project of projects) {
      const from = project.packageName ? `  // ${project.packageName}` : ''
      lines.push(
        `      { name: ${JSON.stringify(project.name)}, dir: ${JSON.stringify(project.dir)} },${from}`,
      )
    }
    lines.push('    ],', '')
  }

  lines.push(
    '    // Wraps every rendered scenario — your theme, router, i18n, query client.',
    '    // Uncomment and point at your real providers.',
    '    // wrapper: ({ children }) => <AppProviders>{children}</AppProviders>,',
    '',
    '    // Per-component presentation. Display only: the real component name is',
    '    // never overridden, because it is what you import.',
    '    // pages: { Button: { title: "Button (CTA)", group: "Actions", order: 1 } },',
    '',
    '    // Named states derivation cannot infer ("logged in, cart empty").',
    '    // Enrichment on top of the derived set, never a replacement for it.',
    '    // scenarios: { Button: [{ name: "Loading", args: { loading: true } }] },',
    '  },',
    '}',
    '',
  )
  return lines.join('\n')
}

/**
 * Detect the workspace's packages and write `pyreon.config.ts`.
 *
 * Refuses to overwrite without `--force`. That file is hand-edited the moment
 * it exists — a wrapper, a theme, authored scenarios — and clobbering it to
 * refresh a list of directories would be a spectacularly bad trade.
 */
export function runInit(options: InitOptions = {}): InitResult {
  const root = resolve(options.cwd ?? '.')
  const dir = options.dir ?? 'src'

  const existing = findExistingConfig(root)
  if (existing && !options.force) return { kind: 'exists', path: existing }

  const detect = options.detect ?? detectProjects
  const projects = detect(root, {
    dir,
    ...(options.hasComponents ? { hasComponents: options.hasComponents } : {}),
  })

  if (projects.length === 0) {
    // Not a monorepo — is there anything to document here at all?
    const probe =
      // COMPONENTS, not files — a package of `.ts` utilities has files but
      // nothing to document, and counting files would call that a hit.
      options.hasComponents ?? ((d: string) => discoverComponents({ cwd: d, dir: '.' }).length > 0)
    if (!probe(join(root, dir))) return { kind: 'nothing-found', searched: join(root, dir) }
  }

  const rootName = (options.readRootName ?? readName)(root)
  const title = options.title ?? projectNameFor(rootName, basename(root))
  const source = renderConfig(title, projects)
  // Written as `.ts`, never `.tsx`: the config is imported by whatever runtime
  // `atlas scan` runs under, so the project's JSX configuration is not
  // necessarily in effect — the same reason the workshop's own config is `.ts`.
  const path = existing ?? join(root, 'pyreon.config.ts')

  if (options.dryRun) return { kind: 'dry-run', path, source, projects, title }
  writeFileSync(path, source, 'utf8')
  return { kind: 'written', path, source, projects, title }
}
