// @ts-nocheck — PMTC handles typing; multi-child JSX + the generated host
// literals are noisy under plain tsc (same rationale as native-analytics).
//
// EXHAUSTIVE MULTIPLATFORM VIZ — ONE `.tsx` -> web + iOS + Android.
//
// The proof that `@pyreon/charts` + `@pyreon/flow` + `@pyreon/code` +
// `@pyreon/rich-text` — web-only-rich UI that CANNOT compile to
// SwiftUI/Compose — nonetheless work on every target via the `<WebView>` bridge
// and the reusable HOSTS from each package's `/webview` subpath. `<WebView>`
// compiles to a WKWebView (iOS), an Android WebView, and an `<iframe srcdoc>`
// (web) — SAME bridge everywhere:
//
//   - FORWARD: `data={option()/graph()/{value}/{content}}` pushes live signal
//     data INTO the page (`window.__pyreonData` + a `pyreondata` event) with NO
//     reload; the chart / diagram / editor re-renders in place.
//   - REVERSE: tapping a chart bar / flow node, or editing the code / rich-text
//     editor, calls `window.pyreonPostMessage` -> the `onMessage` closure,
//     driving the native `selected` label / source signals.
//
// FROM ONE SOURCE: 21 ECharts chart types + a FLOW pipeline diagram + a REAL
// CodeMirror code editor + a REAL TipTap WYSIWYG. Data is a signal; bump it and
// every surface follows; edit an editor and the native source signal follows.
//
// THE HOSTS. `CHART_HOST` / `FLOW_HOST` / `CODE_HOST` / `RICHTEXT_HOST` below
// are GENERATED by each package's host builder (regenerate: `bun
// scripts/gen-hosts.ts`). They are LOCAL consts because PMTC const-ref
// resolution inlines a local literal into the native `PyreonWebView(html:)`
// call (an imported const stays an unresolved reference). CHART_HOST uses the
// ECharts CDN (small, dev/web); a shipping native app passes its BUNDLED
// echarts to `buildChartHostHtml({ echartsScript })` for an offline,
// App-Store-safe page. FLOW_HOST is fully self-contained. CODE_HOST /
// RICHTEXT_HOST load the app-bundled editor globals (`window.CM` / `window.TT`)
// via `<script src="./assets/{cm,tt}.js">` — produce those with `bun
// scripts/gen-editors.ts` (a shipping app inlines the bundle via the
// `codemirrorScript` / `tiptapScript` option instead — offline, App-Store-safe).

import { Stack, Text, Heading, WebView } from '@pyreon/primitives'
import { signal } from '@pyreon/reactivity'

const CHART_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-chart{height:100%;width:100%}</style></head><body><div id=\"pyreon-chart\"></div><script src=\"https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js\"></script><script>\n(function () {\n  try {\n  if (typeof echarts === 'undefined') { window.__pyreonChartError = 'echarts undefined'; return; }\n  var el = document.getElementById('pyreon-chart');\n  var chart = echarts.init(el, null, { renderer: 'canvas' });\n\n  var lastSig = null, rafId = 0;\n  function seriesSig(opt) {\n    var s = opt.series;\n    if (Object.prototype.toString.call(s) === '[object Array]') {\n      var out = s.length + '|';\n      for (var i = 0; i < s.length; i++) out += (s[i] && s[i].type) + ',';\n      return out;\n    }\n    if (s && typeof s === 'object') return '1|' + s.type;\n    return '0|';\n  }\n  function doApply() {\n    rafId = 0;\n    var opt = window.__pyreonData;\n    // The bridge may deliver the option as an already-parsed object (web:\n    // contentWindow.__pyreonData = value) or, defensively, as a JSON string.\n    if (typeof opt === 'string') { try { opt = JSON.parse(opt); } catch (e) { return; } }\n    if (!opt || typeof opt !== 'object') return;\n    var sig = seriesSig(opt);\n    // PERF: same series structure → MERGE (ECharts diffs + animates the data\n    // change — far cheaper than a teardown+rebuild); structure CHANGED (series\n    // added/removed/retyped) → full replace (notMerge) for correctness.\n    chart.setOption(opt, sig !== lastSig);\n    lastSig = sig;\n  }\n  // PERF: coalesce a burst of pushes (a signal updating several times before a\n  // frame) into ONE setOption per frame — aligns work to the display and never\n  // renders a value the user won't see.\n  function apply() {\n    if (rafId) return;\n    if (typeof requestAnimationFrame === 'function') rafId = requestAnimationFrame(doApply);\n    else doApply();\n  }\n\n  chart.on('click', function (p) {\n    if (typeof window.pyreonPostMessage !== 'function') return;\n    // Serialize only the JSON-safe fields — the raw event carries engine refs.\n    var payload = {\n      seriesName: p && p.seriesName,\n      seriesIndex: p && p.seriesIndex,\n      name: p && p.name,\n      dataIndex: p && p.dataIndex,\n      value: p && p.value,\n      componentType: p && p.componentType\n    };\n    try { window.pyreonPostMessage(JSON.stringify(payload)); } catch (e) {}\n  });\n\n  window.addEventListener('pyreondata', apply);\n  window.addEventListener('resize', function () { chart.resize(); });\n  // Observe the container's OWN size — a native host (or an iframe) sizing the\n  // page AFTER load doesn't fire a window 'resize' inside it, so without this\n  // a chart inited at 0-size (common: the host lays out after the page boots)\n  // would never render. Covers device rotation + layout changes too.\n  if (typeof ResizeObserver !== 'undefined') {\n    new ResizeObserver(function () { chart.resize(); }).observe(el);\n  }\n  apply();\n  } catch (e) { window.__pyreonChartError = String(e && e.stack || e); }\n})();</script></body></html>"

const FLOW_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-flow{height:100%;width:100%}</style></head><body><div id=\"pyreon-flow\"></div><script>\n(function () {\n  try {\n  var NS = 'http://www.w3.org/2000/svg';\n  var NODE_W = 150, NODE_H = 44;\n  var root = document.getElementById('pyreon-flow');\n  var svg = document.createElementNS(NS, 'svg');\n  svg.setAttribute('width', '100%'); svg.setAttribute('height', '100%');\n  svg.style.touchAction = 'none';\n  var defs = document.createElementNS(NS, 'defs');\n  defs.innerHTML = '<marker id=\"pf-arrow\" viewBox=\"0 0 10 10\" refX=\"9\" refY=\"5\" markerWidth=\"7\" markerHeight=\"7\" orient=\"auto-start-reverse\"><path d=\"M0,0 L10,5 L0,10 z\" fill=\"#98a2b3\"/><\\/marker>';\n  svg.appendChild(defs);\n  var g = document.createElementNS(NS, 'g');\n  svg.appendChild(g); root.appendChild(svg);\n\n  var vp = { x: 0, y: 0, k: 1 }, fitted = false;\n  function applyVp() { g.setAttribute('transform', 'translate(' + vp.x + ',' + vp.y + ') scale(' + vp.k + ')'); }\n\n  // getBezierPath: dist * 0.25 control offset, source Bottom / target Top.\n  function bezier(sx, sy, tx, ty) {\n    var dx = Math.abs(tx - sx), dy = Math.abs(ty - sy);\n    var off = Math.sqrt(dx * dx + dy * dy) * 0.25;\n    return 'M' + sx + ',' + sy + ' C' + sx + ',' + (sy + off) + ' ' + tx + ',' + (ty - off) + ' ' + tx + ',' + ty;\n  }\n\n  function labelOf(n) {\n    var d = n.data;\n    if (d == null) return n.id;\n    if (typeof d === 'object') return d.label != null ? d.label : n.id;\n    return d;\n  }\n\n  function fit(nodes) {\n    if (fitted || !nodes.length) return;\n    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;\n    nodes.forEach(function (n) {\n      var w = n.width || NODE_W, h = n.height || NODE_H;\n      minX = Math.min(minX, n.position.x); minY = Math.min(minY, n.position.y);\n      maxX = Math.max(maxX, n.position.x + w); maxY = Math.max(maxY, n.position.y + h);\n    });\n    var vw = root.clientWidth || 1, vh = root.clientHeight || 1;\n    var gw = Math.max(1, maxX - minX), gh = Math.max(1, maxY - minY);\n    var pad = 24;\n    vp.k = Math.max(0.2, Math.min(1.5, Math.min((vw - pad * 2) / gw, (vh - pad * 2) / gh)));\n    vp.x = pad - minX * vp.k + Math.max(0, (vw - pad * 2 - gw * vp.k) / 2);\n    vp.y = pad - minY * vp.k + Math.max(0, (vh - pad * 2 - gh * vp.k) / 2);\n    fitted = true; applyVp();\n  }\n\n  function render() {\n    var d = window.__pyreonData;\n    if (typeof d === 'string') { try { d = JSON.parse(d); } catch (e) { return; } }\n    d = d || {}; var nodes = d.nodes || [], edges = d.edges || [];\n    while (g.firstChild) g.removeChild(g.firstChild);\n    var byId = {}; nodes.forEach(function (n) { byId[n.id] = n; });\n    edges.forEach(function (e) {\n      var s = byId[e.source], t = byId[e.target]; if (!s || !t) return;\n      var sw = s.width || NODE_W, sh = s.height || NODE_H, tw = t.width || NODE_W, th = t.height || NODE_H;\n      var p = document.createElementNS(NS, 'path');\n      p.setAttribute('d', bezier(s.position.x + sw / 2, s.position.y + sh, t.position.x + tw / 2, t.position.y));\n      p.setAttribute('fill', 'none'); p.setAttribute('stroke', '#98a2b3'); p.setAttribute('stroke-width', '1.5');\n      p.setAttribute('marker-end', 'url(#pf-arrow)'); g.appendChild(p);\n    });\n    nodes.forEach(function (n) {\n      var w = n.width || NODE_W, h = n.height || NODE_H;\n      var grp = document.createElementNS(NS, 'g');\n      grp.setAttribute('transform', 'translate(' + n.position.x + ',' + n.position.y + ')');\n      grp.style.cursor = 'pointer'; grp.setAttribute('data-node-id', n.id);\n      var r = document.createElementNS(NS, 'rect');\n      r.setAttribute('width', w); r.setAttribute('height', h); r.setAttribute('rx', '8');\n      r.setAttribute('fill', '#ffffff'); r.setAttribute('stroke', '#c9ced6'); r.setAttribute('stroke-width', '1');\n      grp.appendChild(r);\n      var tx = document.createElementNS(NS, 'text');\n      tx.setAttribute('x', w / 2); tx.setAttribute('y', h / 2);\n      tx.setAttribute('text-anchor', 'middle'); tx.setAttribute('dominant-baseline', 'central');\n      tx.setAttribute('font-family', 'system-ui, sans-serif'); tx.setAttribute('font-size', '13'); tx.setAttribute('fill', '#1f2933');\n      tx.textContent = String(labelOf(n)); grp.appendChild(tx);\n      grp.addEventListener('click', function () {\n        if (typeof window.pyreonPostMessage === 'function') {\n          try { window.pyreonPostMessage(JSON.stringify({ id: n.id, data: n.data })); } catch (e) {}\n        }\n      });\n      g.appendChild(grp);\n    });\n    fit(nodes);\n  }\n\n  // Pan (pointer) — bails on a node so taps aren't swallowed.\n  var panning = false, moved = false, last = null;\n  svg.addEventListener('pointerdown', function (e) {\n    if (e.target.closest && e.target.closest('[data-node-id]')) return;\n    panning = true; moved = false; last = { x: e.clientX, y: e.clientY };\n  });\n  window.addEventListener('pointermove', function (e) {\n    if (!panning) return; moved = true;\n    vp.x += e.clientX - last.x; vp.y += e.clientY - last.y; last = { x: e.clientX, y: e.clientY }; applyVp();\n  });\n  window.addEventListener('pointerup', function () { panning = false; });\n  // Zoom (wheel / trackpad-pinch).\n  svg.addEventListener('wheel', function (e) {\n    e.preventDefault();\n    vp.k = Math.max(0.2, Math.min(4, vp.k * (e.deltaY < 0 ? 1.1 : 0.9))); applyVp();\n  }, { passive: false });\n\n  // PERF: the renderer rebuilds the whole node/edge SVG, so coalesce a burst of\n  // pushes (or a resize storm) into ONE rebuild per frame.\n  var rafId = 0;\n  function schedule() {\n    if (rafId) return;\n    if (typeof requestAnimationFrame === 'function') rafId = requestAnimationFrame(function () { rafId = 0; render(); });\n    else render();\n  }\n  window.addEventListener('pyreondata', schedule);\n  if (typeof ResizeObserver !== 'undefined') new ResizeObserver(function () { fitted = false; schedule(); }).observe(root);\n  applyVp(); render();\n  } catch (e) { window.__pyreonFlowError = String(e && e.stack || e); }\n})();</script></body></html>"

const CODE_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-code,.cm-editor{height:100%;width:100%}</style></head><body><div id=\"pyreon-code\"></div><script src=\"./assets/cm.js\"></script><script>\n(function () {\n  // Wait for window.CM — the app's bundled CodeMirror may load async (an\n  // external <script src>, or injected by the native host after page load).\n  var tries = 0;\n  function waitCM() {\n    if (window.CM) { boot(); return; }\n    if (++tries > 800) { window.__pyreonCodeError = 'window.CM not provided (timed out)'; return; }\n    setTimeout(waitCM, 10);\n  }\n  function boot() {\n  try {\n  var CM = window.CM;\n  var el = document.getElementById('pyreon-code');\n  var cur = { value: '', language: '', readOnly: false };\n  var langComp = new CM.Compartment();\n  var roComp = new CM.Compartment();\n  var view = new CM.EditorView({\n    parent: el,\n    state: CM.EditorState.create({\n      doc: '',\n      extensions: [\n        CM.basicSetup,\n        langComp.of([]),\n        roComp.of(CM.EditorState.readOnly.of(false)),\n        CM.EditorView.updateListener.of(function (u) {\n          if (!u.docChanged) return;\n          var v = u.state.doc.toString();\n          // Loop guard: skip the echo of a value WE pushed (cur.value set\n          // BEFORE dispatch below).\n          if (v === cur.value) return;\n          cur.value = v;\n          if (typeof window.pyreonPostMessage === 'function') {\n            try { window.pyreonPostMessage(JSON.stringify({ value: v })); } catch (e) {}\n          }\n        }),\n      ],\n    }),\n  });\n  function apply() {\n    var d = window.__pyreonData;\n    if (typeof d === 'string') { try { d = JSON.parse(d); } catch (e) { return; } }\n    if (!d || typeof d !== 'object') return;\n    if (typeof d.value === 'string' && d.value !== cur.value) {\n      cur.value = d.value;\n      view.dispatch({ changes: { from: 0, to: view.state.doc.length, insert: d.value } });\n    }\n    if (d.readOnly !== undefined && !!d.readOnly !== cur.readOnly) {\n      cur.readOnly = !!d.readOnly;\n      view.dispatch({ effects: roComp.reconfigure(CM.EditorState.readOnly.of(cur.readOnly)) });\n    }\n    if (d.language !== undefined && d.language !== cur.language && typeof CM.languageFor === 'function') {\n      cur.language = d.language;\n      view.dispatch({ effects: langComp.reconfigure(CM.languageFor(d.language) || []) });\n    }\n  }\n  window.addEventListener('pyreondata', apply);\n  apply();\n  } catch (e) { window.__pyreonCodeError = String(e && e.stack || e); }\n  }\n  waitCM();\n})();</script></body></html>"

const RICHTEXT_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-richtext,.ProseMirror{height:100%;width:100%;outline:none;box-sizing:border-box;padding:8px}</style></head><body><div id=\"pyreon-richtext\"></div><script src=\"./assets/tt.js\"></script><script>\n(function () {\n  var tries = 0;\n  function waitTT() {\n    if (window.TT && typeof window.TT.createEditor === 'function') { boot(); return; }\n    if (++tries > 800) { window.__pyreonRichTextError = 'window.TT not provided (timed out)'; return; }\n    setTimeout(waitTT, 10);\n  }\n  function boot() {\n  try {\n  var el = document.getElementById('pyreon-richtext');\n  var cur = { content: null, editable: true };\n  var lastPushed = null; // JSON string of content WE last pushed (loop guard)\n  var editor = window.TT.createEditor(el, {\n    content: null,\n    editable: true,\n    onUpdate: function (json) {\n      var s;\n      try { s = JSON.stringify(json); } catch (e) { return; }\n      // Loop guard: skip the echo of content WE pushed.\n      if (s === lastPushed) return;\n      cur.content = json;\n      if (typeof window.pyreonPostMessage === 'function') {\n        try { window.pyreonPostMessage(JSON.stringify({ content: json })); } catch (e) {}\n      }\n    }\n  });\n  function apply() {\n    var d = window.__pyreonData;\n    if (typeof d === 'string') { try { d = JSON.parse(d); } catch (e) { return; } }\n    if (!d || typeof d !== 'object') return;\n    if (d.content !== undefined) {\n      var s;\n      try { s = JSON.stringify(d.content); } catch (e) { s = null; }\n      if (s !== null && s !== JSON.stringify(cur.content)) {\n        cur.content = d.content;\n        lastPushed = s;\n        editor.setContent(d.content);\n      }\n    }\n    if (d.editable !== undefined && !!d.editable !== cur.editable) {\n      cur.editable = !!d.editable;\n      editor.setEditable(cur.editable);\n    }\n  }\n  window.addEventListener('pyreondata', apply);\n  apply();\n  } catch (e) { window.__pyreonRichTextError = String(e && e.stack || e); }\n  }\n  waitTT();\n})();</script></body></html>"

export function VizApp() {
  const selected = signal('Tap any chart element or flow node, or edit an editor')
  // The code/rich-text editors are driven by these signals over the FORWARD
  // bridge (bump them and the hosted editor's document updates in place). The
  // REVERSE edit fires `onMessage` with the new value/JSON as a raw string —
  // here it just updates the `selected` label (native-clean: no JSON.parse,
  // matching the chart/flow panels). To drive a TYPED native signal from an
  // edit, use `<CodeWebView onChange>` / `<RichTextWebView onChange>` (they
  // parse the payload on web — see each package's /webview browser tests).
  const source = signal('function greet(name) {\n  return "Hello, " + name\n}')
  const doc = signal({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Edit me — this is a real TipTap editor in a WebView.' }] }] })
  // One signal drives every data-driven chart — bump it and they all follow
  // (the forward bridge). 21 chart types + a flow diagram, all in
  // native WebViews from THIS one source.
  const revenue = signal([120, 200, 150, 80, 70])
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

  return (
    <Stack gap={16}>
      <Heading>Multiplatform viz — 21 charts + a flow + a code editor + a WYSIWYG, one source, three targets</Heading>
      <Text>{selected()}</Text>

      <Text>Bar</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'bar', data: revenue() }] }} onMessage={(m) => selected.set('Bar: ' + m)} />

      <Text>Bar (horizontal)</Text>
      <WebView html={CHART_HOST} data={{ xAxis: {}, yAxis: { type: 'category', data: days }, series: [{ type: 'bar', data: revenue() }] }} onMessage={(m) => selected.set('Bar (horizontal): ' + m)} />

      <Text>Bar (stacked)</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'bar', stack: 't', data: revenue() }, { type: 'bar', stack: 't', data: [20, 30, 40, 10, 25] }] }} onMessage={(m) => selected.set('Bar (stacked): ' + m)} />

      <Text>Line</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'line', data: revenue() }] }} onMessage={(m) => selected.set('Line: ' + m)} />

      <Text>Area</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'line', areaStyle: {}, data: revenue() }] }} onMessage={(m) => selected.set('Area: ' + m)} />

      <Text>Line (smooth)</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'line', smooth: true, data: revenue() }] }} onMessage={(m) => selected.set('Line (smooth): ' + m)} />

      <Text>Pie</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'pie', radius: '65%', data: [{ name: 'Mon', value: revenue()[0] }, { name: 'Tue', value: revenue()[1] }, { name: 'Wed', value: revenue()[2] }, { name: 'Thu', value: revenue()[3] }, { name: 'Fri', value: revenue()[4] }] }] }} onMessage={(m) => selected.set('Pie: ' + m)} />

      <Text>Doughnut</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'pie', radius: ['40%', '70%'], data: [{ name: 'Mon', value: revenue()[0] }, { name: 'Tue', value: revenue()[1] }, { name: 'Wed', value: revenue()[2] }, { name: 'Thu', value: revenue()[3] }, { name: 'Fri', value: revenue()[4] }] }] }} onMessage={(m) => selected.set('Doughnut: ' + m)} />

      <Text>Rose</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'pie', roseType: 'area', radius: [10, 90], data: [{ name: 'Mon', value: revenue()[0] }, { name: 'Tue', value: revenue()[1] }, { name: 'Wed', value: revenue()[2] }, { name: 'Thu', value: revenue()[3] }, { name: 'Fri', value: revenue()[4] }] }] }} onMessage={(m) => selected.set('Rose: ' + m)} />

      <Text>Scatter</Text>
      <WebView html={CHART_HOST} data={{ xAxis: {}, yAxis: {}, series: [{ type: 'scatter', data: [[1, 2], [3, 4], [5, 3], [7, 6], [9, 8]] }] }} onMessage={(m) => selected.set('Scatter: ' + m)} />

      <Text>Effect scatter</Text>
      <WebView html={CHART_HOST} data={{ xAxis: {}, yAxis: {}, series: [{ type: 'effectScatter', data: [[2, 3], [5, 4], [8, 7]] }] }} onMessage={(m) => selected.set('Effect scatter: ' + m)} />

      <Text>Radar</Text>
      <WebView html={CHART_HOST} data={{ radar: { indicator: [{ name: 'Speed', max: 100 }, { name: 'Cost', max: 100 }, { name: 'Power', max: 100 }, { name: 'Range', max: 100 }] }, series: [{ type: 'radar', data: [{ value: [80, 60, 90, 40] }] }] }} onMessage={(m) => selected.set('Radar: ' + m)} />

      <Text>Gauge</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'gauge', max: 300, data: [{ value: revenue()[1] }] }] }} onMessage={(m) => selected.set('Gauge: ' + m)} />

      <Text>Funnel</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'funnel', data: [{ name: 'Mon', value: revenue()[0] }, { name: 'Tue', value: revenue()[1] }, { name: 'Wed', value: revenue()[2] }, { name: 'Thu', value: revenue()[3] }, { name: 'Fri', value: revenue()[4] }] }] }} onMessage={(m) => selected.set('Funnel: ' + m)} />

      <Text>Heatmap</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: { type: 'category', data: ['x', 'y', 'z'] }, visualMap: { min: 0, max: 10, calculable: true }, series: [{ type: 'heatmap', data: [[0, 0, 5], [1, 1, 8], [2, 2, 3], [3, 0, 9]] }] }} onMessage={(m) => selected.set('Heatmap: ' + m)} />

      <Text>Candlestick</Text>
      <WebView html={CHART_HOST} data={{ xAxis: { type: 'category', data: days }, yAxis: {}, series: [{ type: 'candlestick', data: [[20, 34, 10, 38], [40, 35, 30, 50], [31, 38, 33, 44], [38, 15, 5, 42], [30, 20, 18, 40]] }] }} onMessage={(m) => selected.set('Candlestick: ' + m)} />

      <Text>Sankey</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'sankey', data: [{ name: 'Ingest' }, { name: 'Transform' }, { name: 'Store' }], links: [{ source: 'Ingest', target: 'Transform', value: 5 }, { source: 'Transform', target: 'Store', value: 3 }] }] }} onMessage={(m) => selected.set('Sankey: ' + m)} />

      <Text>Graph</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'graph', layout: 'force', data: [{ name: 'n1' }, { name: 'n2' }, { name: 'n3' }], links: [{ source: 'n1', target: 'n2' }, { source: 'n2', target: 'n3' }] }] }} onMessage={(m) => selected.set('Graph: ' + m)} />

      <Text>Tree</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'tree', data: [{ name: 'root', children: [{ name: 'a' }, { name: 'b', children: [{ name: 'c' }] }] }] }] }} onMessage={(m) => selected.set('Tree: ' + m)} />

      <Text>Treemap</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'treemap', data: [{ name: 'a', value: 10, children: [{ name: 'a1', value: 4 }, { name: 'a2', value: 6 }] }, { name: 'b', value: 8 }] }] }} onMessage={(m) => selected.set('Treemap: ' + m)} />

      <Text>Sunburst</Text>
      <WebView html={CHART_HOST} data={{ series: [{ type: 'sunburst', data: [{ name: 'a', children: [{ name: 'a1', value: 3 }, { name: 'a2', value: 5 }] }, { name: 'b', value: 4 }] }] }} onMessage={(m) => selected.set('Sunburst: ' + m)} />

      <Text>Pipeline — flow diagram</Text>
      <WebView
        html={FLOW_HOST}
        data={{ nodes: [{ id: 'ingest', position: { x: 0, y: 0 }, data: { label: 'Ingest' } }, { id: 'transform', position: { x: 220, y: 0 }, data: { label: 'Transform' } }, { id: 'store', position: { x: 110, y: 130 }, data: { label: 'Store' } }, { id: 'serve', position: { x: 330, y: 130 }, data: { label: 'Serve' } }], edges: [{ source: 'ingest', target: 'transform' }, { source: 'transform', target: 'store' }, { source: 'transform', target: 'serve' }] }}
        onMessage={(m) => selected.set('Node: ' + m)}
      />

      <Text>Code editor — real CodeMirror in a WebView</Text>
      <WebView
        html={CODE_HOST}
        data={{ value: source(), language: 'javascript' }}
        onMessage={(m) => selected.set('Code edited: ' + m)}
      />

      <Text>Rich text — real TipTap WYSIWYG in a WebView</Text>
      <WebView
        html={RICHTEXT_HOST}
        data={{ content: doc() }}
        onMessage={(m) => selected.set('Doc edited: ' + m)}
      />
    </Stack>
  )
}
