// @ts-nocheck — PMTC handles typing; multi-child JSX + the generated host
// literals are noisy under plain tsc (same rationale as native-analytics).
//
// EXHAUSTIVE MULTIPLATFORM VIZ — ONE `.tsx` -> web + iOS + Android.
//
// The proof that `@pyreon/charts` + `@pyreon/flow` — web-only-rich viz that
// CANNOT compile to SwiftUI/Compose — nonetheless work on every target via the
// `<WebView>` bridge and the reusable HOSTS from `@pyreon/charts/webview` +
// `@pyreon/flow/webview`. `<WebView>` compiles to a WKWebView (iOS), an Android
// WebView, and an `<iframe srcdoc>` (web) — SAME bridge everywhere:
//
//   - FORWARD: `data={option()/graph()}` pushes live signal data INTO the page
//     (`window.__pyreonData` + a `pyreondata` event) with NO reload; the chart
//     / diagram re-renders in place.
//   - REVERSE: tapping a chart bar / flow node calls `window.pyreonPostMessage`
//     -> the `onMessage` closure, driving the native `selected` label.
//
// FOUR live viz surfaces from one source: a BAR, a LINE, and a PIE chart (all
// three share the SAME ECharts host — only the pushed `option` differs), plus a
// FLOW pipeline diagram. Data is a signal; bump it and all four follow.
//
// THE HOSTS. `CHART_HOST` / `FLOW_HOST` below are GENERATED by
// `buildChartHostHtml()` / `buildFlowHostHtml()` (regenerate: `bun
// scripts/gen-hosts.ts`). They are LOCAL consts because PMTC const-ref
// resolution inlines a local literal into the native `PyreonWebView(html:)`
// call (an imported const stays an unresolved reference). This one uses the
// ECharts CDN (small, dev/web); a shipping native app passes its BUNDLED
// echarts to `buildChartHostHtml({ echartsScript })` for an offline,
// App-Store-safe page. The flow host is fully self-contained already.

import { Stack, Text, Heading, WebView } from '@pyreon/primitives'
import { signal } from '@pyreon/reactivity'

const CHART_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-chart{height:100%;width:100%}</style></head><body><div id=\"pyreon-chart\"></div><script src=\"https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js\"></script><script>\n(function () {\n  try {\n  if (typeof echarts === 'undefined') { window.__pyreonChartError = 'echarts undefined'; return; }\n  var el = document.getElementById('pyreon-chart');\n  var chart = echarts.init(el, null, { renderer: 'canvas' });\n\n  function apply() {\n    var opt = window.__pyreonData;\n    // The bridge may deliver the option as an already-parsed object (web:\n    // contentWindow.__pyreonData = value) or, defensively, as a JSON string.\n    if (typeof opt === 'string') { try { opt = JSON.parse(opt); } catch (e) { return; } }\n    if (opt && typeof opt === 'object') { chart.setOption(opt, true); }\n  }\n\n  chart.on('click', function (p) {\n    if (typeof window.pyreonPostMessage !== 'function') return;\n    // Serialize only the JSON-safe fields — the raw event carries engine refs.\n    var payload = {\n      seriesName: p && p.seriesName,\n      seriesIndex: p && p.seriesIndex,\n      name: p && p.name,\n      dataIndex: p && p.dataIndex,\n      value: p && p.value,\n      componentType: p && p.componentType\n    };\n    try { window.pyreonPostMessage(JSON.stringify(payload)); } catch (e) {}\n  });\n\n  window.addEventListener('pyreondata', apply);\n  window.addEventListener('resize', function () { chart.resize(); });\n  // Observe the container's OWN size — a native host (or an iframe) sizing the\n  // page AFTER load doesn't fire a window 'resize' inside it, so without this\n  // a chart inited at 0-size (common: the host lays out after the page boots)\n  // would never render. Covers device rotation + layout changes too.\n  if (typeof ResizeObserver !== 'undefined') {\n    new ResizeObserver(function () { chart.resize(); }).observe(el);\n  }\n  apply();\n  } catch (e) { window.__pyreonChartError = String(e && e.stack || e); }\n})();</script></body></html>"

const FLOW_HOST = "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;padding:0;height:100%;width:100%;background:transparent}#pyreon-flow{height:100%;width:100%}</style></head><body><div id=\"pyreon-flow\"></div><script>\n(function () {\n  try {\n  var NS = 'http://www.w3.org/2000/svg';\n  var NODE_W = 150, NODE_H = 44;\n  var root = document.getElementById('pyreon-flow');\n  var svg = document.createElementNS(NS, 'svg');\n  svg.setAttribute('width', '100%'); svg.setAttribute('height', '100%');\n  svg.style.touchAction = 'none';\n  var defs = document.createElementNS(NS, 'defs');\n  defs.innerHTML = '<marker id=\"pf-arrow\" viewBox=\"0 0 10 10\" refX=\"9\" refY=\"5\" markerWidth=\"7\" markerHeight=\"7\" orient=\"auto-start-reverse\"><path d=\"M0,0 L10,5 L0,10 z\" fill=\"#98a2b3\"/><\\/marker>';\n  svg.appendChild(defs);\n  var g = document.createElementNS(NS, 'g');\n  svg.appendChild(g); root.appendChild(svg);\n\n  var vp = { x: 0, y: 0, k: 1 }, fitted = false;\n  function applyVp() { g.setAttribute('transform', 'translate(' + vp.x + ',' + vp.y + ') scale(' + vp.k + ')'); }\n\n  // getBezierPath: dist * 0.25 control offset, source Bottom / target Top.\n  function bezier(sx, sy, tx, ty) {\n    var dx = Math.abs(tx - sx), dy = Math.abs(ty - sy);\n    var off = Math.sqrt(dx * dx + dy * dy) * 0.25;\n    return 'M' + sx + ',' + sy + ' C' + sx + ',' + (sy + off) + ' ' + tx + ',' + (ty - off) + ' ' + tx + ',' + ty;\n  }\n\n  function labelOf(n) {\n    var d = n.data;\n    if (d == null) return n.id;\n    if (typeof d === 'object') return d.label != null ? d.label : n.id;\n    return d;\n  }\n\n  function fit(nodes) {\n    if (fitted || !nodes.length) return;\n    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;\n    nodes.forEach(function (n) {\n      var w = n.width || NODE_W, h = n.height || NODE_H;\n      minX = Math.min(minX, n.position.x); minY = Math.min(minY, n.position.y);\n      maxX = Math.max(maxX, n.position.x + w); maxY = Math.max(maxY, n.position.y + h);\n    });\n    var vw = root.clientWidth || 1, vh = root.clientHeight || 1;\n    var gw = Math.max(1, maxX - minX), gh = Math.max(1, maxY - minY);\n    var pad = 24;\n    vp.k = Math.max(0.2, Math.min(1.5, Math.min((vw - pad * 2) / gw, (vh - pad * 2) / gh)));\n    vp.x = pad - minX * vp.k + Math.max(0, (vw - pad * 2 - gw * vp.k) / 2);\n    vp.y = pad - minY * vp.k + Math.max(0, (vh - pad * 2 - gh * vp.k) / 2);\n    fitted = true; applyVp();\n  }\n\n  function render() {\n    var d = window.__pyreonData;\n    if (typeof d === 'string') { try { d = JSON.parse(d); } catch (e) { return; } }\n    d = d || {}; var nodes = d.nodes || [], edges = d.edges || [];\n    while (g.firstChild) g.removeChild(g.firstChild);\n    var byId = {}; nodes.forEach(function (n) { byId[n.id] = n; });\n    edges.forEach(function (e) {\n      var s = byId[e.source], t = byId[e.target]; if (!s || !t) return;\n      var sw = s.width || NODE_W, sh = s.height || NODE_H, tw = t.width || NODE_W, th = t.height || NODE_H;\n      var p = document.createElementNS(NS, 'path');\n      p.setAttribute('d', bezier(s.position.x + sw / 2, s.position.y + sh, t.position.x + tw / 2, t.position.y));\n      p.setAttribute('fill', 'none'); p.setAttribute('stroke', '#98a2b3'); p.setAttribute('stroke-width', '1.5');\n      p.setAttribute('marker-end', 'url(#pf-arrow)'); g.appendChild(p);\n    });\n    nodes.forEach(function (n) {\n      var w = n.width || NODE_W, h = n.height || NODE_H;\n      var grp = document.createElementNS(NS, 'g');\n      grp.setAttribute('transform', 'translate(' + n.position.x + ',' + n.position.y + ')');\n      grp.style.cursor = 'pointer'; grp.setAttribute('data-node-id', n.id);\n      var r = document.createElementNS(NS, 'rect');\n      r.setAttribute('width', w); r.setAttribute('height', h); r.setAttribute('rx', '8');\n      r.setAttribute('fill', '#ffffff'); r.setAttribute('stroke', '#c9ced6'); r.setAttribute('stroke-width', '1');\n      grp.appendChild(r);\n      var tx = document.createElementNS(NS, 'text');\n      tx.setAttribute('x', w / 2); tx.setAttribute('y', h / 2);\n      tx.setAttribute('text-anchor', 'middle'); tx.setAttribute('dominant-baseline', 'central');\n      tx.setAttribute('font-family', 'system-ui, sans-serif'); tx.setAttribute('font-size', '13'); tx.setAttribute('fill', '#1f2933');\n      tx.textContent = String(labelOf(n)); grp.appendChild(tx);\n      grp.addEventListener('click', function () {\n        if (typeof window.pyreonPostMessage === 'function') {\n          try { window.pyreonPostMessage(JSON.stringify({ id: n.id, data: n.data })); } catch (e) {}\n        }\n      });\n      g.appendChild(grp);\n    });\n    fit(nodes);\n  }\n\n  // Pan (pointer) — bails on a node so taps aren't swallowed.\n  var panning = false, moved = false, last = null;\n  svg.addEventListener('pointerdown', function (e) {\n    if (e.target.closest && e.target.closest('[data-node-id]')) return;\n    panning = true; moved = false; last = { x: e.clientX, y: e.clientY };\n  });\n  window.addEventListener('pointermove', function (e) {\n    if (!panning) return; moved = true;\n    vp.x += e.clientX - last.x; vp.y += e.clientY - last.y; last = { x: e.clientX, y: e.clientY }; applyVp();\n  });\n  window.addEventListener('pointerup', function () { panning = false; });\n  // Zoom (wheel / trackpad-pinch).\n  svg.addEventListener('wheel', function (e) {\n    e.preventDefault();\n    vp.k = Math.max(0.2, Math.min(4, vp.k * (e.deltaY < 0 ? 1.1 : 0.9))); applyVp();\n  }, { passive: false });\n\n  window.addEventListener('pyreondata', render);\n  if (typeof ResizeObserver !== 'undefined') new ResizeObserver(function () { fitted = false; render(); }).observe(root);\n  applyVp(); render();\n  } catch (e) { window.__pyreonFlowError = String(e && e.stack || e); }\n})();</script></body></html>"

export function VizApp() {
  const selected = signal('Tap a chart bar or a flow node')
  const revenue = signal([120, 200, 150, 80, 70])
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

  return (
    <Stack gap={16}>
      <Heading>Multiplatform viz — one source, three targets</Heading>
      <Text>{selected()}</Text>

      <Text>Revenue — bar</Text>
      <WebView
        html={CHART_HOST}
        data={{ xAxis: { type: 'category', data: days }, yAxis: { type: 'value' }, series: [{ type: 'bar', data: revenue() }] }}
        onMessage={(m) => selected.set('Bar: ' + m)}
      />

      <Text>Revenue — line</Text>
      <WebView
        html={CHART_HOST}
        data={{ xAxis: { type: 'category', data: days }, yAxis: { type: 'value' }, series: [{ type: 'line', smooth: true, data: revenue() }] }}
        onMessage={(m) => selected.set('Line: ' + m)}
      />

      <Text>Revenue — pie</Text>
      <WebView
        html={CHART_HOST}
        data={{ series: [{ type: 'pie', radius: '70%', data: [{ name: 'Mon', value: revenue()[0] }, { name: 'Tue', value: revenue()[1] }, { name: 'Wed', value: revenue()[2] }, { name: 'Thu', value: revenue()[3] }, { name: 'Fri', value: revenue()[4] }] }] }}
        onMessage={(m) => selected.set('Pie: ' + m)}
      />

      <Text>Pipeline — flow</Text>
      <WebView
        html={FLOW_HOST}
        data={{ nodes: [{ id: 'ingest', position: { x: 0, y: 0 }, data: { label: 'Ingest' } }, { id: 'transform', position: { x: 220, y: 0 }, data: { label: 'Transform' } }, { id: 'store', position: { x: 110, y: 130 }, data: { label: 'Store' } }, { id: 'serve', position: { x: 330, y: 130 }, data: { label: 'Serve' } }], edges: [{ source: 'ingest', target: 'transform' }, { source: 'transform', target: 'store' }, { source: 'transform', target: 'serve' }] }}
        onMessage={(m) => selected.set('Node: ' + m)}
      />
    </Stack>
  )
}
