export const tabs = [
  { id: 'dashboard', path: '/', label: '📊 Dashboard' },
  { id: 'store', path: '/store', label: 'Store' },
  { id: 'state-tree', path: '/state-tree', label: 'State Tree' },
  { id: 'form', path: '/form', label: 'Form' },
  { id: 'validation', path: '/validation', label: 'Validation' },
  { id: 'validate', path: '/validate', label: 'Validate' },
  { id: 'i18n', path: '/i18n', label: 'i18n' },
  { id: 'query', path: '/query', label: 'Query' },
  { id: 'table', path: '/table', label: 'Table' },
  { id: 'virtual', path: '/virtual', label: 'Virtual' },
  { id: 'charts', path: '/charts', label: 'Charts' },
  { id: 'code', path: '/code', label: 'Code' },
  { id: 'document', path: '/document', label: 'Document' },
  { id: 'flow', path: '/flow', label: 'Flow' },
  { id: 'storage', path: '/storage', label: 'Storage' },
  { id: 'url-state', path: '/url-state', label: 'URL State' },
  { id: 'hooks', path: '/hooks', label: 'Hooks' },
  { id: 'hotkeys', path: '/hotkeys', label: 'Hotkeys' },
  { id: 'permissions', path: '/permissions', label: 'Permissions' },
  { id: 'machine', path: '/machine', label: 'Machine' },
  { id: 'rx', path: '/rx', label: 'Rx' },
  { id: 'toast', path: '/toast', label: 'Toast' },
  { id: 'dnd', path: '/dnd', label: 'DnD' },
  { id: 'feature', path: '/feature', label: 'Feature' },
] as const
