/**
 * The generated endpoint runtime, for clients that are not `@pyreon/http`.
 *
 * `@pyreon/http` already gives an endpoint the shape every downstream emitter
 * reads — callable, `.key` with a `.prefix`, `.query(args)`, `.mutation()`.
 * That shape is the SEAM: `endpoints/*.ts`, `queries/*.ts`, `keys.ts`,
 * `components.tsx` and the Atlas files are byte-identical whichever transport
 * is underneath, because they only ever touch it.
 *
 * So an axios / ky / fetch client is not a second code path through the
 * generator. It is a different `client.ts` that satisfies the same seam, and
 * the ~120 lines below are what satisfies it.
 *
 * ## Why the URL logic is duplicated here rather than imported
 *
 * A project that chose axios did so to NOT depend on `@pyreon/http`; importing
 * `buildUrl` from it would put the dependency back for the sake of forty
 * lines. The cost of duplicating it is drift, and drift here is not cosmetic —
 * a different base-join or a different query encoding means the SAME generated
 * call issues a DIFFERENT request depending on a config flag, which is the
 * worst kind of silent divergence.
 *
 * That cost is paid down by a differential test rather than by care:
 * `adapter-url-parity.test.ts` runs every adapter's emitted `buildUrl` against
 * `@pyreon/http`'s own as the ORACLE, over a shared matrix that includes the
 * shapes each of these three libraries gets wrong on its own (a leading-slash
 * path under a based URL, a `null` query value, an array query value, a path
 * parameter containing `/`).
 *
 * The semantics being matched are `@pyreon/http`'s, deliberately, including
 * where they differ from the underlying library's defaults:
 *
 *   - `baseUrl` is a pure PREFIX, not a WHATWG `new URL(path, base)`
 *     resolution. Both axios and ky resolve, so `'https://api.test/v1'` plus
 *     `'/books'` gives `…/books` there and `…/v1/books` here. Matching the
 *     library would make the same spec produce a different URL per adapter.
 *   - `undefined` / `null` query entries are DROPPED, never serialized as the
 *     text `"undefined"`.
 *   - path parameters are `encodeURIComponent`-encoded, so an id containing
 *     `/` cannot break out of its segment.
 */

/** Which HTTP runtime the generated client is built on. */
/**
 * What the generated client does when a response does not match its schema --
 * `@pyreon/http`'s `ValidateMode`, with the same meaning on every client:
 * `strict` rejects, `warn` logs and passes the raw body through, `off` skips
 * validation entirely (safe here: generated schemas never transform).
 */
export type ResponseValidation = 'strict' | 'warn' | 'off'

export const ALL_RESPONSE_VALIDATION: readonly ResponseValidation[] = ['strict', 'warn', 'off']

export type ClientName = 'pyreon' | 'fetch' | 'axios' | 'ky'

export const ALL_CLIENTS: readonly ClientName[] = ['pyreon', 'fetch', 'axios', 'ky']

/** The npm package a generated client imports, or `undefined` for none. */
export const CLIENT_PACKAGE: Readonly<Record<ClientName, string | undefined>> = {
  pyreon: '@pyreon/http',
  fetch: undefined,
  axios: 'axios',
  ky: 'ky',
}

/**
 * Only `pyreon` reaches native.
 *
 * PMTC recognises `createHttp` + `api.endpoint(...)` by NAME and lowers the
 * pair to a real `URLSession` / `OkHttp` call. An axios instance is an ordinary
 * import it has never heard of, so a `multiplatform` target over one would emit
 * native modules that lower to nothing — which is precisely the silent
 * regression the target exists to catch.
 */
export function reachesNative(client: ClientName): boolean {
  return client === 'pyreon'
}

/** Shared preamble: types and helpers every generated adapter needs. */
export function runtimePreamble(): string[] {
  return [
    'export type EndpointKey = readonly unknown[]',
    '',
    '/**',
    ' * A value accepted for a query-string entry.',
    ' *',
    ' * Mirrors `@pyreon/http`\'s `QueryValue` exactly. Nullish entries are',
    ' * DROPPED rather than serialized as the strings `"undefined"` / `"null"`,',
    ' * and arrays repeat the key.',
    ' */',
    'export type QueryScalar = string | number | boolean',
    '',
    '/** An object query parameter — bracket keys unless a `QueryStyle` says otherwise. */',
    'export interface QueryObject {',
    '  readonly [key: string]: QueryScalar | null | undefined | readonly QueryScalar[]',
    '}',
    '',
    'export type QueryValue = QueryScalar | null | undefined | readonly QueryScalar[] | QueryObject',
    '',
    '/** OpenAPI query serialization, per key. Mirrors `@pyreon/http`\'s `QueryStyle`. */',
    'export interface QueryStyle {',
    '  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject" | undefined',
    '  explode?: boolean | undefined',
    '}',
    '',
    '/** What a call SENDS. An endpoint may be declared with a narrower input. */',
    'export interface EndpointInput {',
    '  params?: Record<string, string | number> | undefined',
    '  query?: Record<string, QueryValue> | undefined',
    '  json?: unknown',
    '  form?: Record<string, FormValue> | undefined',
    '  multipart?: Record<string, unknown> | undefined',
    '  body?: Blob | ArrayBuffer | string | undefined',
    '}',
    '',
    '/** Per-call options every endpoint accepts, whatever its input type. */',
    'export interface EndpointCallOptions {',
    '  /** `undefined` / `null` values are OMITTED, not sent as text. */',
    '  headers?: Record<string, string | number | boolean | null | undefined> | undefined',
    '  /** Sent as a `Cookie` header (server-side; a browser drops it). */',
    '  cookies?: Record<string, string | number | boolean | null | undefined> | undefined',
    '  signal?: AbortSignal | undefined',
    '}',
    '',
    '/** Makes the argument optional when nothing in it is required. */',
    'export type CallArgs<A> = Record<string, never> extends A ? [args?: A] : [args: A]',
    '',
    '/** How the response body is decoded. Mirrors `@pyreon/http`\'s `ResponseKind`. */',
    'export type ResponseKind = "json" | "text" | "blob" | "stream"',
    '',
    '/** The value an endpoint resolves to for a given kind. */',
    'export type BodyOf<K extends ResponseKind, T> = K extends "text"',
    '  ? string',
    '  : K extends "blob"',
    '    ? Blob',
    '    : K extends "stream"',
    '      ? ReadableStream<Uint8Array> | null',
    '      : T',
    '',
    '/** Arguments an endpoint call accepts. */',
    'export interface EndpointArgs {',
    '  /**',
    '   * `string | number` MATCHES `@pyreon/http` exactly.',
    '   *',
    '   * A boolean path parameter is unsupported on every client here, not just',
    '   * this one — widening it would make the same spec typecheck under one',
    '   * `client` setting and fail under another, which is the divergence this',
    '   * whole seam exists to prevent.',
    '   */',
    '  params?: Record<string, string | number>',
    '  query?: Record<string, QueryValue>',
    '  /** `json`, `form`, `multipart` and `body` are mutually exclusive encodings. */',
    '  json?: unknown',
    '  /** `application/x-www-form-urlencoded`; see `encodeForm`. */',
    '  form?: Record<string, FormValue>',
    '  /** `multipart/form-data`; a `Blob` becomes a file part. */',
    '  multipart?: Record<string, unknown>',
    '  /** A raw body, sent as-is. */',
    '  body?: Blob | ArrayBuffer | string',
    '  /** `undefined` / `null` values are OMITTED, not sent as text. */',
    '  headers?: Record<string, string | number | boolean | null | undefined>',
    '  /** Sent as a `Cookie` header (server-side; a browser drops it). */',
    '  cookies?: Record<string, string | number | boolean | null | undefined>',
    '  signal?: AbortSignal',
    '}',
    '',
    '/** A form value: a scalar, or an array / object of form values. */',
    'export type FormValue =',
    '  | string',
    '  | number',
    '  | boolean',
    '  | null',
    '  | undefined',
    '  | Date',
    '  | readonly FormValue[]',
    '  | { readonly [key: string]: FormValue }',
    '',
    '/** One form field\'s serialization -- OpenAPI\'s Encoding Object. */',
    'export interface FormFieldEncoding {',
    '  style?: "form" | "deepObject" | "spaceDelimited" | "pipeDelimited"',
    '  explode?: boolean',
    '}',
    '',
    '/**',
    ' * Response type inferred from a Standard Schema.',
    ' *',
    ' * Matches zod, valibot, arktype and `@pyreon/validate` alike — the schema',
    ' * emitter is free to change library without this file knowing.',
    ' *',
    ' * The `NonNullable` step is load-bearing. `types` is an OPTIONAL phantom',
    ' * property, so matching `{ types?: { output: infer O } }` directly fails',
    ' * against a library that spells it `types?: Types | undefined` — and it',
    ' * fails SILENTLY, resolving to `unknown`. Every generated hook then reads',
    ' * `Promise<unknown>` and the module does not compile.',
    ' */',
    'type Infer<V> = V extends { readonly "~standard": { readonly types?: infer T } }',
    '  ? NonNullable<T> extends { readonly output: infer O }',
    '    ? O',
    '    : unknown',
    '  : unknown',
    '',
    '/** Structural mirror of TanStack query options — no dependency needed. */',
    'export interface QueryOptionsLike<T> {',
    '  queryKey: EndpointKey',
    '  queryFn: (context: { signal: AbortSignal }) => Promise<T>',
    '}',
    '',
    'export interface MutationOptionsLike<T, TVars> {',
    '  mutationFn: (variables: TVars) => Promise<T>',
    '  invalidates?: EndpointKey[] | undefined',
    '}',
    '',
    '/**',
    ' * An endpoint: callable, plus the key/query/mutation helpers. `I` is what a',
    ' * call sends, exactly as `@pyreon/http`\'s `Endpoint` types it.',
    ' */',
    'export interface Endpoint<T, I = EndpointInput> {',
    '  (...args: CallArgs<I & EndpointCallOptions>): Promise<T>',
    '  readonly method: string',
    '  readonly path: string',
    '  readonly key: ((...args: CallArgs<I & EndpointCallOptions>) => EndpointKey) & {',
    '    readonly prefix: EndpointKey',
    '  }',
    '  query(...args: CallArgs<I & EndpointCallOptions>): QueryOptionsLike<T>',
    '  mutation<TVars extends I & EndpointCallOptions = I & EndpointCallOptions>(options?: {',
    '    invalidates?: readonly { readonly key: { readonly prefix: EndpointKey } }[]',
    '  }): MutationOptionsLike<T, TVars>',
    '}',
    '',
    'const ABSOLUTE_RE = /^[a-z][a-z\\d+\\-.]*:\\/\\//i',
    '',
    '/**',
    ' * Join base and path with exactly one slash.',
    ' *',
    ' * A pure PREFIX join, NOT `new URL(path, base)`. Both axios and ky resolve,',
    ' * so a leading-slash path would discard the base\'s own path segment there',
    ' * and not here; matching them would make the same spec issue a different',
    ' * request depending on which client was configured.',
    ' */',
    'export function joinUrl(base: string | undefined, path: string): string {',
    '  if (!base || ABSOLUTE_RE.test(path)) return path',
    '  const b = base.endsWith("/") ? base.slice(0, -1) : base',
    '  const p = path.startsWith("/") ? path : `/${path}`',
    '  return `${b}${p}`',
    '}',
    '',
    '/**',
    ' * Substitute `:name` placeholders, URI-encoded. Throws on a missing one.',
    ' * `\\\\:` is a LITERAL colon (a custom verb such as `/v1/:name\\\\:cancel`).',
    ' */',
    'export function applyPathParams(path: string, params: EndpointArgs["params"]): string {',
    '  if (!path.includes(":")) return path',
    '  return path.replace(/\\\\:|:([A-Za-z_][A-Za-z0-9_]*)/g, (_m, name: string | undefined) => {',
    '    if (name === undefined) return ":"',
    '    const value = params?.[name]',
    '    if (value === undefined || value === null) {',
    '      throw new Error(',
    '        `[lathe] path "${path}" needs the parameter "${name}" but it was not supplied. ` +',
    '          `Pass it as \\`{ params: { ${name}: … } }\\`.`,',
    '      )',
    '    }',
    '    return encodeURIComponent(String(value))',
    '  })',
    '}',
    '',
    '/**',
    ' * Serialize query parameters. Nullish entries are DROPPED; arrays repeat;',
    ' * objects use bracket keys; `styles` overrides per key.',
    ' */',
    'export function buildQuery(',
    '  query: EndpointArgs["query"],',
    '  styles?: Readonly<Record<string, QueryStyle>>,',
    '): string {',
    '  if (!query) return ""',
    '  const search = new URLSearchParams()',
    '  for (const key of Object.keys(query)) {',
    '    const value = query[key]',
    '    if (value === undefined || value === null) continue',
    '    appendStyled(search, key, value, styles?.[key])',
    '  }',
    '  const out = search.toString()',
    '  return out ? `?${out}` : ""',
    '}',
    '',
    'function scalars(values: readonly (QueryScalar | null | undefined)[]): string[] {',
    '  const out: string[] = []',
    '  for (const v of values) if (v !== undefined && v !== null) out.push(String(v))',
    '  return out',
    '}',
    '',
    'const DELIMITER = { form: ",", spaceDelimited: " ", pipeDelimited: "|" } as const',
    '',
    'function appendStyled(',
    '  search: URLSearchParams,',
    '  key: string,',
    '  value: Exclude<QueryValue, null | undefined>,',
    '  style: QueryStyle | undefined,',
    '): void {',
    '  if (Array.isArray(value)) {',
    '    const items = scalars(value as readonly QueryScalar[])',
    '    const kind = style?.style',
    '    if (kind !== undefined && kind !== "deepObject" && style?.explode === false) {',
    '      if (items.length > 0) search.append(key, items.join(DELIMITER[kind]))',
    '      return',
    '    }',
    '    for (const item of items) search.append(key, item)',
    '    return',
    '  }',
    '  if (typeof value === "object") {',
    '    const obj = value as QueryObject',
    '    const entries = Object.keys(obj).flatMap((prop) => {',
    '      const v = obj[prop]',
    '      if (v === undefined || v === null) return []',
    '      return Array.isArray(v)',
    '        ? scalars(v).map((item) => [prop, item] as const)',
    '        : [[prop, String(v)] as const]',
    '    })',
    '    const kind = style?.style ?? "deepObject"',
    '    if (kind === "deepObject") {',
    '      for (const [prop, v] of entries) search.append(`${key}[${prop}]`, v)',
    '    } else if (style?.explode === false) {',
    '      if (entries.length > 0) search.append(key, entries.flat().join(DELIMITER[kind]))',
    '    } else {',
    '      for (const [prop, v] of entries) search.append(prop, v)',
    '    }',
    '    return',
    '  }',
    '  search.append(key, String(value))',
    '}',
    '',
    '/** Full resolution: base + path + params + query. */',
    'export function buildUrl(',
    '  baseUrl: string | undefined,',
    '  path: string,',
    '  params: EndpointArgs["params"],',
    '  query: EndpointArgs["query"],',
    '  styles?: Readonly<Record<string, QueryStyle>>,',
    '): string {',
    '  const joined = joinUrl(baseUrl, applyPathParams(path, params))',
    '  const qs = buildQuery(query, styles)',
    '  if (!qs) return joined',
    '  return joined.includes("?") ? `${joined}&${qs.slice(1)}` : `${joined}${qs}`',
    '}',
    '',
    ...runtimeBodyEncoders(),
  ]
}

/**
 * Body encoders -- a line-for-line mirror of `@pyreon/http`'s `encodeForm` /
 * `encodeMultipart` / `encodeCookies`, held to byte equality by
 * `adapter-url-parity.test.ts` exactly as the URL builder is. A different form
 * encoding per `client` setting would make the same spec send a different
 * request body depending on a config flag.
 */
function runtimeBodyEncoders(): string[] {
  return [
    'function formScalar(v: FormValue): string | undefined {',
    '  if (v === null || v === undefined) return undefined',
    '  if (v instanceof Date) return v.toISOString()',
    '  return String(v)',
    '}',
    '',
    'function isFormObject(v: unknown): v is { readonly [key: string]: FormValue } {',
    '  return v !== null && typeof v === "object" && !Array.isArray(v) && !(v instanceof Date) && !(v instanceof Blob)',
    '}',
    '',
    'function appendDeep(out: URLSearchParams, key: string, value: FormValue): void {',
    '  if (Array.isArray(value)) {',
    '    value.forEach((item, i) => appendDeep(out, `${key}[${i}]`, item as FormValue))',
    '    return',
    '  }',
    '  if (isFormObject(value)) {',
    '    for (const k of Object.keys(value)) appendDeep(out, `${key}[${k}]`, value[k] as FormValue)',
    '    return',
    '  }',
    '  const s = formScalar(value)',
    '  if (s !== undefined) out.append(key, s)',
    '}',
    '',
    '/** `application/x-www-form-urlencoded`, per OpenAPI encoding. Nullish fields dropped. */',
    'export function encodeForm(',
    '  fields: Readonly<Record<string, FormValue>>,',
    '  encoding: Readonly<Record<string, FormFieldEncoding>> = {},',
    '): URLSearchParams {',
    '  const out = new URLSearchParams()',
    '  for (const key of Object.keys(fields)) {',
    '    const value = fields[key] as FormValue',
    '    if (value === null || value === undefined) continue',
    '    const enc = encoding[key] ?? {}',
    '    const style = enc.style ?? "form"',
    '    const explode = enc.explode ?? style === "form"',
    '    if (style === "deepObject") {',
    '      appendDeep(out, key, value)',
    '      continue',
    '    }',
    '    if (Array.isArray(value)) {',
    '      const items = (value as readonly FormValue[]).filter((v) => v !== null && v !== undefined)',
    '      if (items.some((v) => Array.isArray(v) || isFormObject(v))) {',
    '        appendDeep(out, key, value)',
    '        continue',
    '      }',
    '      const strings = items.map((v) => formScalar(v) as string)',
    '      if (style === "spaceDelimited") out.append(key, strings.join(" "))',
    '      else if (style === "pipeDelimited") out.append(key, strings.join("|"))',
    '      else if (explode) for (const s of strings) out.append(key, s)',
    '      else out.append(key, strings.join(","))',
    '      continue',
    '    }',
    '    if (isFormObject(value)) {',
    '      const entries = Object.keys(value).filter((k) => value[k] !== null && value[k] !== undefined)',
    '      if (explode) {',
    '        for (const k of entries) {',
    '          const inner = value[k] as FormValue',
    '          if (Array.isArray(inner) || isFormObject(inner)) appendDeep(out, k, inner)',
    '          else out.append(k, formScalar(inner) as string)',
    '        }',
    '      } else {',
    '        out.append(key, entries.flatMap((k) => [k, formScalar(value[k] as FormValue) as string]).join(","))',
    '      }',
    '      continue',
    '    }',
    '    out.append(key, formScalar(value) as string)',
    '  }',
    '  return out',
    '}',
    '',
    '/** `multipart/form-data`: a Blob is a file part, an object a JSON text part. */',
    'export function encodeMultipart(fields: Readonly<Record<string, unknown>>): FormData {',
    '  const out = new FormData()',
    '  const put = (key: string, value: unknown): void => {',
    '    if (value === null || value === undefined) return',
    '    if (value instanceof Blob) out.append(key, value)',
    '    else if (value instanceof Date) out.append(key, value.toISOString())',
    '    else if (typeof value === "object") out.append(key, JSON.stringify(value))',
    '    else out.append(key, String(value))',
    '  }',
    '  for (const key of Object.keys(fields)) {',
    '    const value = fields[key]',
    '    if (Array.isArray(value)) for (const item of value) put(key, item)',
    '    else put(key, value)',
    '  }',
    '  return out',
    '}',
    '',
    '/** A `Cookie` header value. Nullish entries omitted, values percent-encoded. */',
    'export function encodeCookies(cookies: Readonly<Record<string, string | number | boolean | null | undefined>>): string {',
    '  const parts: string[] = []',
    '  for (const key of Object.keys(cookies)) {',
    '    const v = cookies[key]',
    '    if (v === null || v === undefined) continue',
    '    parts.push(`${key}=${encodeURIComponent(String(v))}`)',
    '  }',
    '  return parts.join("; ")',
    '}',
  ]
}

/**
 * Response validation through the Standard Schema contract.
 *
 * Three details here are each a documented bug class, and all three are
 * invisible until the exact library that trips them is used:
 *
 *   1. The guard accepts a CALLABLE as well as an object. An ArkType schema is
 *      a function carrying `~standard`, so a `typeof x === 'object'` test
 *      silently reports "not a schema" and skips validation entirely.
 *   2. Failure is discriminated on `issues`, never on the presence of `value`.
 *      Valibot's FAILURE result carries `{ typed: false, value, issues }` — a
 *      `'value' in result` test reads that as success and returns the RAW
 *      invalid input.
 *   3. `validate` may return a Promise. Awaiting a non-Promise is free, so it
 *      is awaited unconditionally rather than branched on.
 */
export function runtimeValidate(): string[] {
  return [
    'type StandardResult = { issues?: readonly { message: string }[]; value?: unknown }',
    'type StandardSchema = { "~standard": { validate: (v: unknown) => StandardResult | Promise<StandardResult> } }',
    '',
    'function isStandardSchema(v: unknown): v is StandardSchema {',
    '  // A schema may be a FUNCTION (ArkType) as well as an object.',
    '  if (v === null || (typeof v !== "object" && typeof v !== "function")) return false',
    '  const std = (v as { "~standard"?: { validate?: unknown } })["~standard"]',
    '  return typeof std?.validate === "function"',
    '}',
    '',
    '/** `@pyreon/http`\'s `ValidateMode`: throw, log-and-pass-through, or skip. */',
    'export type ValidateMode = "strict" | "warn" | "off"',
    '',
    'async function validateResponse(',
    '  schema: unknown,',
    '  body: unknown,',
    '  mode: ValidateMode,',
    '): Promise<unknown> {',
    '  if (mode === "off" || !isStandardSchema(schema)) return body',
    '  const result = await schema["~standard"].validate(body)',
    '  // Failure is `issues` being present and non-empty — NOT the absence of',
    '  // `value`, which some libraries return alongside the issues.',
    '  if (result.issues && result.issues.length > 0) {',
    '    const detail = result.issues.map((i) => i.message).join(", ")',
    '    if (mode === "warn") {',
    '      console.warn(`[lathe] response did not match its schema (validate: "warn"): ${detail}`)',
    '      return body',
    '    }',
    '    throw new Error(`[lathe] response did not match its schema: ${detail}`)',
    '  }',
    '  return result.value',
    '}',
  ]
}

/**
 * The transport seam.
 *
 * `@pyreon/http` reserves this slot with a passthrough middleware because
 * endpoints bind to the client at declaration time. The generated adapters
 * have the same problem for the same reason, so they expose the same function
 * — which is what lets ONE `mocks.ts` install fixtures against any of them.
 *
 * The request shape is deliberately the platform's own `Request`/`Response`
 * rather than an adapter-specific one: a mock written against it works
 * unchanged when the client is swapped, which is the entire point of having
 * the seam in the first place.
 */
export function runtimeTransport(): string[] {
  return [
    '/** A request as the library is about to send it — after its interceptors. */',
    'export interface DevRequest {',
    '  method: string',
    '  /** Fully-resolved request URL, params substituted and query appended. */',
    '  url: string',
    '  headers: Record<string, string>',
    '  /** The serialized body, or `null`. */',
    '  body: string | null',
    '}',
    '',
    '/**',
    ' * An answer, ENVELOPED.',
    ' *',
    ' * The envelope is what distinguishes "handled, and the body is empty" from',
    ' * "not handled, go to the network". `json` answers a JSON body, `body` a raw',
    ' * one; neither is a 204.',
    ' */',
    'export type DevAnswer = {',
    '  status?: number | undefined',
    '  json?: unknown',
    '  body?: string | undefined',
    '  headers?: Record<string, string> | undefined',
    '} | null',
    '',
    'export type DevTransport = (req: DevRequest) => DevAnswer | Promise<DevAnswer>',
    '',
    'let devTransport: DevTransport | null = null',
    '',
    '/**',
    ' * Install a transport that answers requests instead of the network.',
    ' *',
    ' * It sits at the BOTTOM of the library — as its fetch, or its adapter — so',
    ' * everything configured on the client (headers, `configureApi({ use })`',
    ' * interceptors, auth) runs on a mocked request exactly as on a real one.',
    ' * Returning `null` falls through to the network. Pass `null` to uninstall.',
    ' */',
    'export function setDevTransport(transport: DevTransport | null): void {',
    '  devTransport = transport',
    '}',
    '',
    '/** A dev answer as a platform `Response`. */',
    'function answerResponse(answer: NonNullable<DevAnswer>): Response {',
    '  const headers = new Headers(answer.headers)',
    '  let body: string | null = null',
    '  if (answer.json !== undefined) {',
    '    body = JSON.stringify(answer.json)',
    '    if (!headers.has("content-type")) headers.set("content-type", "application/json")',
    '  } else if (answer.body !== undefined) {',
    '    body = answer.body',
    '  }',
    '  const status = answer.status ?? (body === null ? 204 : 200)',
    '  // 204/205/304 must be constructed with a null body or `Response` throws.',
    '  const empty = status === 204 || status === 205 || status === 304',
    '  return new Response(empty ? null : body, { status, headers })',
    '}',
    '',
    '/** Ask the dev transport for a platform `Request`; `null` means the network. */',
    'async function devResponse(request: Request): Promise<Response | null> {',
    '  if (!devTransport) return null',
    '  const headers: Record<string, string> = {}',
    '  request.headers.forEach((value, key) => {',
    '    headers[key] = value',
    '  })',
    '  const body = request.body === null ? null : await request.clone().text()',
    '  const answer = await devTransport({ method: request.method, url: request.url, headers, body })',
    '  return answer === null ? null : answerResponse(answer)',
    '}',
  ]
}

/**
 * A uniform error type across adapters.
 *
 * The three libraries disagree about failure by default: `fetch` resolves a
 * 500 as a normal response, axios rejects with an `AxiosError`, ky rejects
 * with an `HTTPError`. Left alone, switching `client` would change what a
 * generated query's `error` signal CONTAINS — so every adapter normalises to
 * this one shape, which also mirrors `@pyreon/http`'s `HttpError` closely
 * enough that a `status` check written against one keeps working against the
 * others.
 */
export function runtimeError(): string[] {
  return [
    'export class LatheHttpError extends Error {',
    '  constructor(',
    '    readonly status: number,',
    '    readonly url: string,',
    '    /** Parsed body when it was JSON, raw text otherwise, `undefined` when empty. */',
    '    readonly body?: unknown,',
    '  ) {',
    '    super(`[lathe] ${status} for ${url}`)',
    '    this.name = "LatheHttpError"',
    '  }',
    '}',
  ]
}

/**
 * The `Interceptor` type — each library's own request-extension shape, so an
 * interceptor or hook written for that library elsewhere drops straight in.
 */
function interceptorDecl(client: ClientName): string[] {
  const doc = '/** One `configureApi({ use })` entry, in this library\'s own idiom. */'
  if (client === 'axios') {
    return [doc, 'export type Interceptor = (config: InternalAxiosRequestConfig) => InternalAxiosRequestConfig | Promise<InternalAxiosRequestConfig>']
  }
  if (client === 'ky') return [doc, 'export type Interceptor = BeforeRequestHook']
  return [
    doc,
    '// fetch has no interceptor API of its own, so this is the standard',
    '// middleware shape: call `next` with the (possibly replaced) Request.',
    'export type Interceptor = (request: Request, next: (request: Request) => Promise<Response>) => Promise<Response>',
  ]
}

/** How the `use` slot runs, per library. */
function interceptorRun(client: ClientName): string[] {
  if (client === 'axios') {
    return [
      '',
      'const networkAdapter = axios.getAdapter(axios.defaults.adapter)',
      '',
      '/**',
      ' * The instance\'s `adapter` — the bottom of axios, BELOW its interceptors, so',
      ' * a mocked request has been through everything a real one has. The body it',
      ' * returns is RAW; axios\'s own `transformResponse` decodes it after, as for',
      ' * the network.',
      ' */',
      'async function axiosTransport(config: InternalAxiosRequestConfig): Promise<AxiosResponse> {',
      '  if (devTransport) {',
      '    const headers: Record<string, string> = {}',
      '    for (const [k, v] of Object.entries(config.headers.toJSON())) {',
      '      if (v !== undefined && v !== null) headers[k.toLowerCase()] = String(v)',
      '    }',
      '    const data: unknown = config.data',
      '    // An encoded body (FormData, URLSearchParams, a Blob) reads as the text',
      '    // it would put on the wire, exactly as a Request body does.',
      '    const body =',
      '      data === undefined || data === null',
      '        ? null',
      '        : typeof data === "string"',
      '          ? data',
      '          : data instanceof FormData || data instanceof URLSearchParams || data instanceof Blob || data instanceof ArrayBuffer',
      '            ? await new Response(data).text()',
      '            : JSON.stringify(data)',
      '    const answer = await devTransport({',
      '      method: (config.method ?? "get").toUpperCase(),',
      '      url: config.url ?? "",',
      '      headers,',
      '      body,',
      '    })',
      '    if (answer !== null) {',
      '      const res = answerResponse(answer)',
      '      const data =',
      '        config.responseType === "blob"',
      '          ? await res.blob()',
      '          : config.responseType === "stream"',
      '            ? res.body',
      '            : await res.text()',
      '      const response: AxiosResponse = {',
      '        data,',
      '        status: res.status,',
      '        statusText: res.statusText,',
      '        headers: Object.fromEntries(res.headers),',
      '        config,',
      '        request: {},',
      '      }',
      '      const ok = config.validateStatus ? config.validateStatus(res.status) : res.ok',
      '      if (!ok) {',
      '        throw new AxiosError(',
      '          `Request failed with status code ${res.status}`,',
      '          AxiosError.ERR_BAD_RESPONSE,',
      '          config,',
      '          {},',
      '          response,',
      '        )',
      '      }',
      '      return response',
      '    }',
      '  }',
      '  return networkAdapter(config)',
      '}',
      '',
      'let installed: number[] = []',
      '',
      '/**',
      ' * Mirror `settings.use` onto the instance\'s request interceptors. axios runs',
      ' * request interceptors LAST-registered first, so they are registered in',
      ' * reverse to run in `use` order, outermost first.',
      ' */',
      'function installInterceptors(): void {',
      '  for (const id of installed) instance.interceptors.request.eject(id)',
      '  installed = [...settings.use].reverse().map((fn) => instance.interceptors.request.use(fn))',
      '}',
    ]
  }
  if (client === 'ky') {
    return [
      '',
      '/**',
      ' * ky\'s `fetch` option — the bottom of ky, BELOW its hooks and retries, so a',
      ' * mocked request has been through everything a real one has.',
      ' */',
      'async function kyTransport(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {',
      '  const request = new Request(input, init)',
      '  return (await devResponse(request)) ?? fetch(request)',
      '}',
      '',
      '/** The instance\'s one `beforeRequest` hook: ky\'s own semantics over the `use` slot. */',
      'async function runInterceptors(state: BeforeRequestState): Promise<Request | Response | void> {',
      '  let request = state.request',
      '  for (const hook of settings.use) {',
      '    const out = await hook({ ...state, request })',
      '    if (out instanceof Response) return out',
      '    if (out instanceof Request) request = out',
      '  }',
      '  return request === state.request ? undefined : request',
      '}',
    ]
  }
  return [
    '',
    '/** The bottom of the chain: the dev transport when installed, else fetch. */',
    'async function transport(request: Request): Promise<Response> {',
    '  return (await devResponse(request)) ?? fetch(request)',
    '}',
    '',
    '/** Run the `use` slot around the platform fetch, outermost first. */',
    'function runInterceptors(request: Request): Promise<Response> {',
    '  const at = (i: number, r: Request): Promise<Response> => {',
    '    const mw = settings.use[i]',
    '    return mw ? mw(r, (next) => at(i + 1, next)) : transport(r)',
    '  }',
    '  return at(0, request)',
    '}',
  ]
}

/** The adapter-specific request execution. */
function sendFn(client: ClientName): string[] {
  if (client === 'fetch') {
    return [
      'async function send(',
      '  method: string,',
      '  url: string,',
      '  headers: Record<string, string>,',
      '  payload: BodyInit | undefined,',
      '  signal: AbortSignal | undefined,',
      '  kind: ResponseKind,',
      '): Promise<unknown> {',
      '  const res = await runInterceptors(new Request(url, {',
      '    method,',
      '    headers,',
      '    // Spread rather than assigned: under `exactOptionalPropertyTypes` an',
    '    // explicit `undefined` is not assignable to `RequestInit["body"]`, so',
    '    // the key has to be ABSENT rather than present-and-undefined.',
    '    ...(payload === undefined ? {} : { body: payload }),',
      '    ...(signal ? { signal } : {}),',
      '  }))',
      '  // `fetch` resolves a 500 like any other response; every other adapter',
      '  // here rejects. Normalised so the generated hooks behave identically.',
      '  if (!res.ok) throw new LatheHttpError(res.status, url, await readBody(res))',
      '  if (kind === "text") return res.text()',
      '  if (kind === "blob") return res.blob()',
      '  if (kind === "stream") return res.body',
      '  return readBody(res)',
      '}',
      '',
      'async function readBody(res: Response): Promise<unknown> {',
      '  if (res.status === 204 || res.status === 205) return undefined',
      '  const text = await res.text()',
      '  if (text === "") return undefined',
      '  try {',
      '    return JSON.parse(text) as unknown',
      '  } catch {',
      '    // A non-JSON error page is far more useful as its text than as a',
      '    // parse failure that hides what the server actually said.',
      '    return text',
      '  }',
      '}',
    ]
  }
  if (client === 'axios') {
    return [
      'async function send(',
      '  method: string,',
      '  url: string,',
      '  headers: Record<string, string>,',
      '  payload: BodyInit | undefined,',
      '  signal: AbortSignal | undefined,',
      '  kind: ResponseKind,',
      '): Promise<unknown> {',
      '  try {',
      '    const res = await instance.request({',
      '      url,',
      '      method,',
      '      headers,',
      '      ...(payload === undefined ? {} : { data: payload }),',
      '      ...(signal ? { signal } : {}),',
      '      // Non-JSON bodies decode as the platform type, never through JSON.',
      '      ...(kind === "json" ? {} : { responseType: kind }),',
      '    })',
      '    if (kind !== "json") return res.data',
      '    // axios reports an empty body as the EMPTY STRING, not `undefined`,',
      '    // so a 204 would decode to `""` and then fail a schema the other',
      '    // adapters never even reach with a value.',
      '    return res.data === "" ? undefined : res.data',
      '  } catch (err) {',
      '    const res = (err as { response?: { status: number; data: unknown } }).response',
      '    if (res) throw new LatheHttpError(res.status, url, res.data)',
      '    throw err',
      '  }',
      '}',
    ]
  }
  return [
    'async function send(',
    '  method: string,',
    '  url: string,',
    '  headers: Record<string, string>,',
    '  payload: BodyInit | undefined,',
    '  signal: AbortSignal | undefined,',
    '  kind: ResponseKind,',
    '): Promise<unknown> {',
    '  try {',
    '    const res = await instance(url, {',
    '      method,',
    '      headers,',
    '      ...(payload === undefined ? {} : { body: payload }),',
    '      ...(signal ? { signal } : {}),',
    '    })',
    '    if (kind === "text") return res.text()',
    '    if (kind === "blob") return res.blob()',
    '    if (kind === "stream") return res.body',
    '    if (res.status === 204 || res.status === 205) return undefined',
    '    const text = await res.text()',
    '    return text === "" ? undefined : (JSON.parse(text) as unknown)',
    '  } catch (err) {',
    '    const e = err as { response?: Response; data?: unknown }',
    '    if (e.response) {',
    '      // ky CONSUMES the error body into `error.data` and documents that',
    '      // `error.response.json()` will not work afterwards. Reading the',
    '      // response here returns an empty stream, so the status survives and',
    '      // the body silently does not.',
    '      throw new LatheHttpError(e.response.status, url, e.data)',
    '    }',
    '    throw err',
    '  }',
    '}',
  ]
}

/**
 * The endpoint factory — the seam every other emitter reads.
 *
 * Key construction matches `@pyreon/http`'s exactly: `[method, path]` as the
 * prefix, `[method, path, { params?, query? }]` when arguments narrow it. That
 * is not cosmetic — `keys.ts` is generated identically for every adapter, so a
 * different key shape here would make a generated `invalidateQueries` silently
 * match nothing.
 */
export function runtimeEndpoint(
  client: ClientName,
  baseUrl: string,
  keyScope?: string,
  validate: ResponseValidation = 'strict',
): string[] {
  return [
    ...sendFn(client),
    '',
    ...interceptorDecl(client),
    '',
    '/**',
    ' * Runtime configuration — the same `configureApi` the `@pyreon/http` client',
    ' * exposes. `use` takes this library\'s OWN extension shape (see',
    ' * `Interceptor`), so anything written for it elsewhere works here.',
    ' */',
    'export interface ApiConfig {',
    '  /** Replaces the spec\'s server URL for every request. */',
    '  baseUrl?: string | undefined',
    '  /** Headers for every request. An accessor is re-read per request. */',
    '  headers?: Record<string, string> | (() => Record<string, string>) | undefined',
    '  /** Response validation: throw, warn and pass through, or skip. */',
    '  validate?: ValidateMode | undefined',
    '  /** Run around every request, outermost first — auth, logging, tracing. */',
    '  use?: readonly Interceptor[] | undefined',
    '}',
    '',
    `const DEFAULT_BASE_URL = ${JSON.stringify(baseUrl)}`,
    `const DEFAULT_VALIDATE: ValidateMode = ${JSON.stringify(validate)}`,
    '',
    'const settings: {',
    '  baseUrl: string',
    '  headers: ApiConfig["headers"]',
    '  validate: ValidateMode',
    '  use: readonly Interceptor[]',
    '} = {',
    '  baseUrl: DEFAULT_BASE_URL,',
    '  headers: undefined,',
    '  validate: DEFAULT_VALIDATE,',
    '  use: [],',
    '}',
    ...interceptorRun(client),
    '',
    '/** The base URL requests currently go to — the generated default, or what `configureApi` set. */',
    'export function apiBaseUrl(): string {',
    '  return settings.baseUrl',
    '}',
    '',
    '/** A key present with `undefined` resets that slot; an absent key leaves it alone. */',
    'export function configureApi(config: ApiConfig): void {',
    '  if ("baseUrl" in config) settings.baseUrl = config.baseUrl ?? DEFAULT_BASE_URL',
    '  if ("headers" in config) settings.headers = config.headers',
    '  if ("validate" in config) settings.validate = config.validate ?? DEFAULT_VALIDATE',
    '  if ("use" in config) {',
    '    settings.use = config.use ?? []',
    ...(client === 'axios' ? ['    installInterceptors()'] : []),
    '  }',
    '}',
    '',
    '/** Namespace for every cache key — `@pyreon/http`\'s `keyScope`. */',
    `export const KEY_SCOPE: string | undefined = ${keyScope === undefined ? 'undefined' : JSON.stringify(keyScope)}`,
    '',
    'function isEmpty(v: Record<string, unknown> | undefined): boolean {',
    '  return v === undefined || Object.keys(v).length === 0',
    '}',
    '',
    'export const api = {',
    '  /**',
    '   * Declare an endpoint from a `"METHOD /path/:param"` literal.',
    '   *',
    '   * `response` is an optional Standard Schema — zod, valibot, arktype and',
    '   * `@pyreon/validate` all satisfy it. When present the body is validated',
    '   * AND the return type is inferred from it.',
    '   */',
    '  endpoint<',
    '    S extends string = string,',
    '    V = undefined,',
    '    I = EndpointInput,',
    '    K extends ResponseKind = "json",',
    '  >(',
    '    spec: S,',
    '    config?: {',
    '      response?: V',
    '      responseType?: K',
    '      queryStyle?: Readonly<Record<string, QueryStyle>>',
    '      /** Headers every call sends; per-call headers merge over them. */',
    '      headers?: Record<string, string>',
    '      /** How each field of a `form` body serializes. */',
    '      formEncoding?: Readonly<Record<string, FormFieldEncoding>>',
    '    },',
    '  ): Endpoint<BodyOf<K, Infer<V>>, I> {',
    '    const sep = spec.indexOf(" ")',
    '    const method = spec.slice(0, sep).toUpperCase()',
    '    const path = spec.slice(sep + 1)',
    '    const kind: ResponseKind = config?.responseType ?? "json"',
    '    const prefix: EndpointKey = KEY_SCOPE === undefined ? [method, path] : [KEY_SCOPE, method, path]',
    '',
    '    const buildKey = (args?: EndpointArgs): EndpointKey => {',
    '      if (isEmpty(args?.params) && isEmpty(args?.query)) return prefix',
    '      const scope: Record<string, unknown> = {}',
    '      if (!isEmpty(args?.params)) scope.params = args?.params',
    '      if (!isEmpty(args?.query)) scope.query = args?.query',
    '      return [...prefix, scope]',
    '    }',
    '',
    '    const call = async (args?: EndpointArgs): Promise<unknown> => {',
    '      const url = buildUrl(settings.baseUrl, path, args?.params, args?.query, config?.queryStyle)',
    '      const given = [args?.json !== undefined, args?.form !== undefined, args?.multipart !== undefined, args?.body !== undefined]',
    '      if (given.filter(Boolean).length > 1) {',
    '        throw new Error("[lathe] pass ONE of `json`, `form`, `multipart` or `body` -- each is a different encoding of the same body.")',
    '      }',
    '      // Declared headers, then configured ones, then per-call ones (per-call',
    '      // wins); nullish values are omitted rather than sent as "undefined".',
    '      const headers: Record<string, string> = {}',
    '      const put = (h: Record<string, string | number | boolean | null | undefined> | undefined): void => {',
    '        if (!h) return',
    '        for (const k of Object.keys(h)) {',
    '          const v = h[k]',
    '          if (v === null || v === undefined) delete headers[k.toLowerCase()]',
    '          else headers[k.toLowerCase()] = String(v)',
    '        }',
    '      }',
    '      put(config?.headers)',
    '      const configured = settings.headers',
    '      put(typeof configured === "function" ? configured() : configured)',
    '      put(args?.headers)',
    '      if (args?.cookies) {',
    '        const cookie = encodeCookies(args.cookies)',
    '        if (cookie) headers.cookie = headers.cookie ? `${headers.cookie}; ${cookie}` : cookie',
    '      }',
    '      let payload: BodyInit | undefined',
    '      if (args?.json !== undefined) {',
    '        headers["content-type"] ??= "application/json"',
    '        payload = JSON.stringify(args.json)',
    '      } else if (args?.form !== undefined) {',
    '        headers["content-type"] ??= "application/x-www-form-urlencoded"',
    '        payload = encodeForm(args.form, config?.formEncoding).toString()',
    '      } else if (args?.multipart !== undefined) {',
    '        // No content-type: the platform writes it with the boundary it chose.',
    '        payload = encodeMultipart(args.multipart)',
    '      } else if (args?.body !== undefined) {',
    '        payload = args.body',
    '      }',
    '      const body = await send(method, url, headers, payload, args?.signal, kind)',
    '      return kind === "json" ? validateResponse(config?.response, body, settings.validate) : body',
    '    }',
    '',
    '    const key = Object.assign((args?: EndpointArgs) => buildKey(args), { prefix })',
    '',
    '    return Object.assign(call, {',
    '      method,',
    '      path,',
    '      key,',
    '      query: (args?: EndpointArgs) => ({',
    '        queryKey: buildKey(args),',
    '        queryFn: ({ signal }: { signal: AbortSignal }) => call({ ...args, signal }),',
    '      }),',
    '      mutation: (options?: {',
    '        invalidates?: readonly { readonly key: { readonly prefix: EndpointKey } }[]',
    '      }) => ({',
    '        mutationFn: (variables: EndpointArgs) => call(variables),',
    '        invalidates: options?.invalidates?.map((e) => e.key.prefix),',
    '      }),',
    '    }) as unknown as Endpoint<BodyOf<K, Infer<V>>, I>',
    '  },',
    '}',
  ]
}
