/**
 * Reference documentation, rendered from the IR.
 *
 * Kubb reaches for Redoc here, which renders the SPEC. That is a different
 * document from the one a consumer of this client needs: Redoc tells you the
 * HTTP contract, and leaves you to work out which generated hook corresponds
 * to `GET /books/{bookId}`, what its query key looks like, and whether it
 * works on iOS. The spec cannot answer any of those, because the answers are
 * properties of the GENERATED code.
 *
 * So these pages document the generated client, with the HTTP contract beside
 * it. The one column no other generator can print is REACH: whether an
 * operation lowers to a native request under PMTC, and when it does not, why.
 *
 * Markdown rather than a bundled HTML site, because this repo already has two
 * static doc generators (`atlas build`, `@pyreon/zero-content`) and a third
 * would be a worse copy of both. Frontmatter is emitted so the pages drop into
 * a `@pyreon/zero-content` collection unchanged, and they read correctly on
 * GitHub with nothing installed.
 */

import type { IrDocument, IrOperation, IrType, Reach } from '../core/ir'
import { typeIdent } from '../core/naming'
import { byTag, endpointSpec, isMutation, tagFile } from './client'
import { tsType } from './schema'
import type { GeneratedFile } from './writer'
import { safeBlockComment } from './writer'

export const DOCS_DIR = 'docs'

export interface DocsOptions {
  /** Per-operation native reach, from the same analysis the CLI reports. */
  reach?: ReadonlyMap<string, { reach: Reach; reason?: string | undefined }> | undefined
  /** Whether the run emitted hooks, which decides if the usage snippet shows one. */
  hasQueries: boolean
  /**
   * The base URL the generated client actually calls.
   *
   * NOT `doc.baseUrl`. A config `baseUrl` OVERRIDES the spec's `servers[0]`,
   * and the reach analysis already reads the override — so a page rendered
   * from the spec value would print a host the client never contacts, while
   * the reach column beside it was decided from a different one.
   */
  baseUrl: string
}

/** Emit `docs/index.md` plus one page per tag. */
export function emitDocs(doc: IrDocument, opts: DocsOptions): GeneratedFile[] {
  const tags = [...byTag(doc)]
  if (tags.length === 0) return []
  const out: GeneratedFile[] = [indexPage(doc, tags, opts)]
  for (const [tag, ops] of tags) out.push(tagPage(doc, tag, ops, opts))
  if (doc.models.length > 0) out.push(modelsPage(doc))
  return out
}

function frontmatter(title: string, description: string): string[] {
  // Quoted with doubled inner quotes: a spec title carrying a `:` or a `"`
  // otherwise produces YAML that parses as something else, or not at all.
  //
  // The marker is an HTML comment rather than the `//`-prefixed banner the
  // code emitters use: it has to be invisible when the page RENDERS and
  // present when someone opens the file to edit it, which is the one place a
  // generated Markdown page gets edited by mistake.
  return [
    '---',
    `title: "${yaml(title)}"`,
    `description: "${yaml(description)}"`,
    '---',
    '',
    '<!-- @generated by @pyreon/lathe — DO NOT EDIT. Re-run `lathe generate`. -->',
    '',
  ]
}

function yaml(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').replace(/"/g, '""').trim()
}

function indexPage(
  doc: IrDocument,
  tags: readonly (readonly [string, IrOperation[]])[],
  opts: DocsOptions,
): GeneratedFile {
  const lines = frontmatter(doc.title, `Generated client reference for ${doc.title} ${doc.version}.`)
  lines.push(`# ${doc.title}`, '')
  lines.push(
    `\`${doc.version}\`${opts.baseUrl ? ` · \`${opts.baseUrl}\`` : ''} · ${doc.operations.length} operations · ${doc.models.length} models`,
    '',
  )

  const reached = countReach(doc, opts)
  if (reached.total > 0) {
    lines.push('## Reach', '')
    lines.push(
      `${reached.native} of ${reached.total} operations lower to a native request on iOS and Android; the rest run on the web only. Each page states the reason per operation.`,
      '',
    )
  }

  lines.push('## Tags', '')
  lines.push('| Tag | Operations | Page |', '| --- | ---: | --- |')
  for (const [tag, ops] of tags) {
    // The tag is spec-supplied text landing in a table CELL, so it needs the
    // same escape every other cell gets. It did not have one.
    lines.push(`| ${md(tag)} | ${ops.length} | [\`${tagFile(tag)}\`](./${tagFile(tag)}.md) |`)
  }
  lines.push('')
  if (doc.models.length > 0) {
    lines.push(`See [models](./models.md) for the ${doc.models.length} generated types.`, '')
  }

  if (doc.notes.length > 0) {
    // The dropped features belong in the docs, not only in the CLI output. A
    // reader asking "why is this field `unknown`" is holding the page that
    // should answer it.
    lines.push('## Not represented', '')
    lines.push(
      'Everything the spec expressed that this client does not. Each is a deliberate loss recorded at the input boundary, never a silent one.',
      '',
    )
    lines.push('| Code | Where | Detail |', '| --- | --- | --- |')
    for (const n of doc.notes) {
      lines.push(`| \`${n.code}\` | \`${md(n.at)}\` | ${md(n.message)} |`)
    }
    lines.push('')
  }
  return { path: `${DOCS_DIR}/index.md`, contents: `${lines.join('\n')}\n` }
}

function tagPage(
  doc: IrDocument,
  tag: string,
  ops: readonly IrOperation[],
  opts: DocsOptions,
): GeneratedFile {
  const lines = frontmatter(tag, `${ops.length} operations on ${tag}.`)
  lines.push(`# ${tag}`, '')
  lines.push(`[← ${doc.title}](./index.md)`, '')

  for (const op of ops) {
    const info = opts.reach?.get(op.id)
    lines.push(`## \`${op.id}\``, '')
    // `endpointSpec` rather than an inline `${method} ${path}`: it is the same
    // helper the client emitter declares the endpoint with, so the page cannot
    // drift from the literal in the generated code.
    lines.push(`\`${endpointSpec(op)}\``, '')
    if (op.summary) lines.push(md(op.summary), '')

    lines.push(`- **Reach** — ${reachLabel(info)}`)
    if (info?.reason) lines.push(`  - ${md(info.reason)}`)
    lines.push(`- **Response** — ${typeCell(op.response)}`)
    if (op.body) lines.push(`- **Request body** — ${typeCell(op.body)}`)
    lines.push('')

    const params = [...op.pathParams, ...op.queryParams]
    if (params.length > 0) {
      lines.push('| Parameter | In | Required | Type |', '| --- | --- | --- | --- |')
      for (const p of op.pathParams) {
        lines.push(`| \`${p.name}\` | path | yes | ${typeCell(p.type)} |`)
      }
      for (const p of op.queryParams) {
        lines.push(`| \`${p.name}\` | query | ${p.required ? 'yes' : 'no'} | ${typeCell(p.type)} |`)
      }
      lines.push('')
    }

    lines.push('```ts', ...usage(doc, op, tag, opts), '```', '')
  }
  return { path: `${DOCS_DIR}/${tagFile(tag)}.md`, contents: `${lines.join('\n')}\n` }
}

/**
 * The usage snippet — the reason these pages exist rather than a Redoc build.
 *
 * It names the generated symbol, its import site, and the argument shape the
 * types actually require, which is the question a reader of a generated client
 * has and a rendering of the spec cannot answer.
 */
function usage(
  doc: IrDocument,
  op: IrOperation,
  tag: string,
  opts: DocsOptions,
): string[] {
  const file = tagFile(tag)
  const args = argsLiteral(op)
  if (!opts.hasQueries) {
    return [
      `import { ${op.id} } from './gen/endpoints/${file}'`,
      '',
      `const data = await ${op.id}(${args})`,
    ]
  }
  const hook = hookName(op)
  const lines = [
    `import { ${hook} } from './gen/queries/${file}'`,
    '',
  ]
  if (isMutation(op)) {
    lines.push(
      `const ${op.id} = ${hook}()`,
      `${op.id}.mutate(${args || '{}'})`,
    )
  } else {
    lines.push(
      args ? `const query = ${hook}(() => (${args}))` : `const query = ${hook}()`,
      '',
      '// `query.data()` is an accessor — read it in a reactive scope.',
    )
  }
  return lines
}

/** The generated hook's name, matching the client emitter's convention. */
function hookName(op: IrOperation): string {
  return `use${typeIdent(op.id)}`
}

/** An argument literal shaped like the endpoint's own `EndpointArgs`. */
function argsLiteral(op: IrOperation): string {
  const parts: string[] = []
  if (op.pathParams.length > 0) {
    parts.push(`params: { ${op.pathParams.map((p) => `${p.name}: ${sample(p.type)}`).join(', ')} }`)
  }
  const required = op.queryParams.filter((p) => p.required)
  if (required.length > 0) {
    parts.push(`query: { ${required.map((p) => `${p.name}: ${sample(p.type)}`).join(', ')} }`)
  }
  if (op.body) parts.push('json: /* … */ {}')
  return parts.length > 0 ? `{ ${parts.join(', ')} }` : ''
}

function sample(type: IrType): string {
  switch (type.kind) {
    case 'number':
      return '1'
    case 'boolean':
      return 'true'
    case 'string':
      return type.enum && type.enum[0] ? `'${type.enum[0]}'` : "'…'"
    default:
      return "'…'"
  }
}

function reachLabel(info: { reach: Reach; reason?: string | undefined } | undefined): string {
  if (!info) return 'web'
  return info.reach === 'web+native' ? 'web · iOS · Android' : 'web only'
}

function countReach(doc: IrDocument, opts: DocsOptions): { native: number; total: number } {
  if (!opts.reach) return { native: 0, total: 0 }
  let native = 0
  for (const op of doc.operations) {
    if (opts.reach.get(op.id)?.reach === 'web+native') native++
  }
  return { native, total: doc.operations.length }
}

function modelsPage(doc: IrDocument): GeneratedFile {
  const lines = frontmatter('Models', `${doc.models.length} generated types.`)
  lines.push('# Models', '')
  lines.push(`[← ${doc.title}](./index.md)`, '')
  for (const model of doc.models) {
    lines.push(`## \`${model.name}\``, '')
    if (model.doc) lines.push(md(model.doc), '')
    lines.push('```ts', `type ${model.name} = ${tsType(model.type, 0, false)}`, '```', '')
  }
  return { path: `${DOCS_DIR}/models.md`, contents: `${lines.join('\n')}\n` }
}

/** A type rendered for a table cell — one line, pipes escaped. */
function typeCell(type: IrType | undefined): string {
  if (!type) return '_no content_'
  return `\`${mdCell(tsType(type, 0, false).replace(/\s*\n\s*/g, ' '))}\``
}

/**
 * Escape a value for a Markdown table CELL.
 *
 * The BACKSLASH has to go first, and getting that order wrong is not a style
 * point -- it reopens the exact hole the escape exists to close. Escaping only
 * the pipe turns an input of `\|` into `\\|`, which Markdown reads as an
 * escaped BACKSLASH followed by a LIVE pipe, so the cell splits anyway. Escape
 * the escape character first and both survive.
 *
 * Same rule the `q()` string-literal escaper in `writer.ts` follows for the
 * same reason, in a different syntax.
 */
function mdCell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
}

/**
 * Spec text, safe in a Markdown TABLE cell.
 *
 * A raw `|` splits the cell and a newline ends the ROW, so a `description`
 * carrying either does not merely look wrong -- it restructures the table and
 * silently drops the rest of the value. Same class as the block-comment and
 * line-comment escapes the code emitters use, in a third syntax.
 */
function md(value: string): string {
  return mdCell(safeBlockComment(value).replace(/[\r\n]+/g, ' ')).trim()
}
