/**
 * Reference documentation, rendered from the IR.
 *
 * Kubb reaches for Redoc here, which renders the SPEC. That is a different
 * document from the one a consumer of this client needs: Redoc tells you the
 * HTTP contract, and leaves you to work out which generated hook corresponds
 * to `GET /books/{bookId}`, what its query key looks like, and whether it
 * works on iOS. The spec cannot answer any of those, because the answers are
 * properties of the GENERATED code.
 *
 * So these pages document the generated client, with the HTTP contract beside
 * it. The one column no other generator can print is REACH: whether an
 * operation lowers to a native request under PMTC, and when it does not, why.
 *
 * Markdown rather than a bundled HTML site, because this repo already has two
 * static doc generators (`atlas build`, `@pyreon/zero-content`) and a third
 * would be a worse copy of both. Frontmatter is emitted so the pages drop into
 * a `@pyreon/zero-content` collection unchanged, and they read correctly on
 * GitHub with nothing installed.
 */

import { hasInput } from './operation-types'
import { noteSeverity, type IrDocument, type IrOperation, type IrType, type Reach } from '../core/ir'
import { propKey, typeIdent } from '../core/naming'
import { bodyArg, byTag, endpointSpec, isMutation, tagFile } from './client'
import { isStreamOnly, streamHookName, streamHookTakesArgs, streamName } from './stream'
import { tsType } from './schema'
import type { GeneratedFile } from './writer'
import { CONTROL_CHARS, q, safeBlockComment } from './writer'

export const DOCS_DIR = 'docs'

export interface DocsOptions {
  /** Per-operation native reach, from the same analysis the CLI reports. */
  reach?: ReadonlyMap<string, { reach: Reach; reason?: string | undefined }> | undefined
  /** Whether the run emitted hooks, which decides if the usage snippet shows one. */
  hasQueries: boolean
  /**
   * The base URL the generated client actually calls.
   *
   * NOT `doc.baseUrl`. A config `baseUrl` OVERRIDES the spec's `servers[0]`,
   * and the reach analysis already reads the override — so a page rendered
   * from the spec value would print a host the client never contacts, while
   * the reach column beside it was decided from a different one.
   */
  baseUrl: string
  /**
   * The module specifier a page's usage snippets import the generated client
   * from (audit H1). Derived from the configured `output` — see
   * {@link docsImportBase} — rather than hard-coded to `./gen`, which named a
   * directory that does not exist under any non-default output.
   */
  importBase?: string | undefined
}

/**
 * The import specifier for snippets, from the configured output directory.
 *
 * Written relative to `src/` when the output lives under it — the directory
 * application code is written in, so `./src/gen` reads `./gen`, matching what
 * a file at `src/main.ts` imports — and relative to the project root
 * otherwise.
 */
export function docsImportBase(output: string): string {
  let rel = output.replace(/\\/g, '/').replace(/^\.\//, '')
  // Trailing slashes trimmed by index, not `/\/+$/` — an anchored-at-end `+`
  // is retried from every `/` in a long run, which is quadratic on input a
  // config controls.
  let end = rel.length
  while (end > 0 && rel[end - 1] === '/') end--
  rel = rel.slice(0, end)
  if (rel.startsWith('/')) return rel
  return rel.startsWith('src/') ? `./${rel.slice('src/'.length)}` : `./${rel}`
}

/** Emit `docs/index.md` plus one page per tag. */
export function emitDocs(doc: IrDocument, opts: DocsOptions): GeneratedFile[] {
  const tags = [...byTag(doc)]
  if (tags.length === 0) return []
  const out: GeneratedFile[] = [indexPage(doc, tags, opts)]
  for (const [tag, ops] of tags) out.push(tagPage(doc, tag, ops, opts))
  if (doc.models.length > 0) out.push(modelsPage(doc))
  return out
}

function frontmatter(title: string, description: string): string[] {
  // Quoted, with YAML's own escapes: a spec title carrying a `:` or a `"`
  // otherwise produces YAML that parses as something else, or not at all.
  //
  // The marker is an HTML comment rather than the `//`-prefixed banner the
  // code emitters use: it has to be invisible when the page RENDERS and
  // present when someone opens the file to edit it, which is the one place a
  // generated Markdown page gets edited by mistake.
  return [
    '---',
    `title: "${yaml(title)}"`,
    `description: "${yaml(description)}"`,
    '---',
    '',
    '<!-- @generated by @pyreon/lathe — DO NOT EDIT. Re-run `lathe generate`. -->',
    '',
  ]
}

/**
 * Escape a value for a DOUBLE-QUOTED YAML scalar.
 *
 * Doubling the quote (`""`) is the CSV and SINGLE-quoted-YAML convention, and
 * it is wrong here: inside double quotes YAML escapes with a BACKSLASH, so a
 * doubled quote closes the scalar and starts another one. `title: """x"""`
 * does not parse as `"x"` — gray-matter, which is what actually reads these
 * pages, rejects the document outright. A title containing a quote took the
 * whole page down.
 *
 * Backslash first, for the same reason `mdCell` below does it: escaping only
 * the quote turns `\\"` into `\\\"` — an escaped backslash followed by a LIVE
 * quote — and the scalar ends anyway.
 *
 * The control characters go the way they go in every other emitted context:
 * OUT. A double-quoted YAML scalar has no escape available for them at this
 * layer, and js-yaml -- which is what gray-matter reads these pages with --
 * REFUSES the whole document on one, naming a line and column in a file the
 * author never wrote. NUL, BEL and ESC each took a page down; DEL and NEL
 * parsed but were silently dropped, so escaping them would buy nothing a strip
 * does not. TAB is legal and stays.
 */
function yaml(value: string): string {
  return value
    .replace(/[\r\n]+/g, ' ')
    .replace(CONTROL_CHARS, '')
    .trim()
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
}

function indexPage(
  doc: IrDocument,
  tags: readonly (readonly [string, IrOperation[]])[],
  opts: DocsOptions,
): GeneratedFile {
  const lines = frontmatter(doc.title, `Generated client reference for ${doc.title} ${doc.version}.`)
  lines.push(`# ${doc.title}`, '')
  lines.push(
    `\`${doc.version}\`${opts.baseUrl ? ` · \`${opts.baseUrl}\`` : ''} · ${doc.operations.length} operations · ${doc.models.length} models`,
    '',
  )

  const reached = countReach(doc, opts)
  if (reached.total > 0) {
    lines.push('## Reach', '')
    lines.push(
      `${reached.native} of ${reached.total} operations lower to a native request on iOS and Android; the rest run on the web only. Each page states the reason per operation.`,
      '',
    )
  }

  lines.push('## Tags', '')
  lines.push('| Tag | Operations | Page |', '| --- | ---: | --- |')
  for (const [tag, ops] of tags) {
    // The tag is spec-supplied text landing in a table CELL, so it needs the
    // same escape every other cell gets. It did not have one.
    lines.push(`| ${md(tag)} | ${ops.length} | [\`${tagFile(tag)}\`](./${tagFile(tag)}.md) |`)
  }
  lines.push('')
  if (doc.models.length > 0) {
    lines.push(`See [models](./models.md) for the ${doc.models.length} generated types.`, '')
  }

  const losses = doc.notes.filter((n) => noteSeverity(n) === 'loss')
  const choices = doc.notes.filter((n) => noteSeverity(n) === 'choice')
  if (losses.length > 0) {
    // The dropped features belong in the docs, not only in the CLI output. A
    // reader asking "why is this field `unknown`" is holding the page that
    // should answer it.
    lines.push('## Not represented', '')
    lines.push(
      'Everything the spec expressed that this client does not. Each is a deliberate loss recorded at the input boundary, never a silent one.',
      '',
    )
    lines.push('| Code | Where | Detail |', '| --- | --- | --- |')
    for (const n of losses) {
      lines.push(`| \`${n.code}\` | \`${md(n.at)}\` | ${md(n.message)} |`)
    }
    lines.push('')
  }
  if (choices.length > 0) {
    // Kept apart from the losses: "used JSON over XML" is not something this
    // client fails to do, and interleaving the two buries the ones that are.
    lines.push('## Choices made', '')
    lines.push('Where the spec allowed several readings, the one this client uses. Nothing here is lost.', '')
    lines.push('| Code | Where | Detail |', '| --- | --- | --- |')
    for (const n of choices) {
      lines.push(`| \`${n.code}\` | \`${md(n.at)}\` | ${md(n.message)} |`)
    }
    lines.push('')
  }
  return { path: `${DOCS_DIR}/index.md`, contents: `${lines.join('\n')}\n` }
}

function tagPage(
  doc: IrDocument,
  tag: string,
  ops: readonly IrOperation[],
  opts: DocsOptions,
): GeneratedFile {
  const lines = frontmatter(tag, `${ops.length} operations on ${tag}.`)
  lines.push(`# ${tag}`, '')
  lines.push(`[← ${doc.title}](./index.md)`, '')

  for (const op of ops) {
    const info = opts.reach?.get(op.id)
    lines.push(`## \`${op.id}\``, '')
    // `endpointSpec` rather than an inline `${method} ${path}`: it is the same
    // helper the client emitter declares the endpoint with, so the page cannot
    // drift from the literal in the generated code.
    lines.push(`\`${endpointSpec(op)}\``, '')
    if (op.summary) lines.push(md(op.summary), '')

    lines.push(`- **Reach** — ${reachLabel(info)}`)
    if (info?.reason) lines.push(`  - ${md(info.reason)}`)
    if (!isStreamOnly(op)) lines.push(`- **Response** — ${typeCell(op.response)}`)
    if (op.stream) {
      lines.push(
        `- **Stream** — \`${md(op.stream.media)}\` ${op.stream.format === 'sse' ? 'events' : 'lines'} of ${
          op.stream.format === 'sse' && op.stream.data === 'text' ? '`string`' : typeCell(op.stream.event)
        }, via \`${streamName(op)}\`${opts.hasQueries ? ` / \`${streamHookName(op)}\`` : ''} (web only)`,
      )
    }
    if (op.body) lines.push(`- **Request body** — ${typeCell(op.body.type)} as \`${md(op.body.mediaType)}\``)
    lines.push('')

    const params = [...op.pathParams, ...op.queryParams, ...op.headerParams, ...op.cookieParams]
    if (params.length > 0) {
      // A parameter NAME is spec-supplied text landing in a table cell, so it
      // takes the same escape every other cell here takes. A PATH name is
      // normalized to an identifier, but a QUERY name is a WIRE name and
      // survives verbatim -- `p|q` split the row, leaving the header at four
      // cells and that row at five, which silently shifts every value one
      // column left of its heading.
      lines.push('| Parameter | In | Required | Type |', '| --- | --- | --- | --- |')
      for (const p of op.pathParams) {
        lines.push(`| \`${md(p.name)}\` | path | yes | ${typeCell(p.type)} |`)
      }
      for (const [where, list] of [
        ['query', op.queryParams],
        ['header', op.headerParams],
        ['cookie', op.cookieParams],
      ] as const) {
        for (const p of list) {
          lines.push(
            `| \`${md(p.name)}\` | ${where} | ${p.required ? 'yes' : 'no'} | ${typeCell(p.type)} |`,
          )
        }
      }
      lines.push('')
    }

    if (!isStreamOnly(op)) lines.push('```ts', ...usage(doc, op, tag, opts), '```', '')
    if (op.stream) lines.push('```ts', ...streamUsage(op, tag, opts), '```', '')
  }
  return { path: `${DOCS_DIR}/${tagFile(tag)}.md`, contents: `${lines.join('\n')}\n` }
}

/**
 * The usage snippet — the reason these pages exist rather than a Redoc build.
 *
 * It names the generated symbol, its import site, and the argument shape the
 * types actually require, which is the question a reader of a generated client
 * has and a rendering of the spec cannot answer.
 */
function usage(
  doc: IrDocument,
  op: IrOperation,
  tag: string,
  opts: DocsOptions,
): string[] {
  const file = tagFile(tag)
  const args = argsLiteral(op)
  const base = opts.importBase ?? './gen'
  if (!opts.hasQueries) {
    return [
      `import { ${op.id} } from '${base}/endpoints/${file}'`,
      '',
      `const data = await ${op.id}(${args})`,
    ]
  }
  const hook = hookName(op)
  const lines = [
    `import { ${hook} } from '${base}/queries/${file}'`,
    '',
  ]
  if (isMutation(op)) {
    lines.push(
      `const ${op.id} = ${hook}()`,
      // A mutation that sends nothing takes NO variables (`void`); `{}` there
      // is a type error in the reader's code.
      `${op.id}.mutate(${hasInput(op) ? args || '{}' : ''})`,
    )
  } else {
    lines.push(
      args ? `const query = ${hook}(() => (${args}))` : `const query = ${hook}()`,
      '',
      '// `query.data()` is an accessor — read it in a reactive scope.',
    )
  }
  return lines
}

/** How to consume a streaming operation — the iterator, and the hook when queries exist. */
function streamUsage(op: IrOperation, tag: string, opts: DocsOptions): string[] {
  const file = tagFile(tag)
  const base = opts.importBase ?? './gen'
  const args = argsLiteral(op)
  const fn = streamName(op)
  const lines = [
    `import { ${fn} } from '${base}/endpoints/${file}'`,
    '',
    `for await (const ${op.stream?.format === 'ndjson' ? 'row' : 'event'} of ${fn}(${args})) {`,
    '  // `break` closes the connection',
    '}',
  ]
  if (!opts.hasQueries) return lines
  const hook = streamHookName(op)
  return [
    ...lines,
    '',
    `import { ${hook} } from '${base}/queries/${file}'`,
    '',
    streamHookTakesArgs(op) ? `const live = ${hook}(() => (${args || '{}'}))` : `const live = ${hook}()`,
    '// live.events() / live.latest() / live.status() — signals; closed on unmount.',
  ]
}

/** The generated hook's name, matching the client emitter's convention. */
function hookName(op: IrOperation): string {
  return `use${typeIdent(op.id)}`
}

/** An argument literal shaped like the endpoint's own `EndpointArgs`. */
function argsLiteral(op: IrOperation): string {
  const parts: string[] = []
  // `propKey` and `q`, not raw interpolation. The snippet is TypeScript a
  // reader COPIES, and a QUERY name is a WIRE name that survives verbatim by
  // design -- `odd wire-name` produced `query: { odd wire-name: '…' }`, which
  // is not a program. The client emitter has quoted these since the parameter
  // -name fix; the page that documents it did not.
  if (op.pathParams.length > 0) {
    const fields = op.pathParams.map((p) => `${propKey(p.name)}: ${sample(p.type)}`)
    parts.push(`params: { ${fields.join(', ')} }`)
  }
  for (const [arg, list] of [
    ['query', op.queryParams],
    ['headers', op.headerParams],
    ['cookies', op.cookieParams],
  ] as const) {
    const required = list.filter((p) => p.required)
    if (required.length === 0) continue
    const fields = required.map((p) => `${propKey(p.name)}: ${sample(p.type)}`)
    parts.push(`${arg}: { ${fields.join(', ')} }`)
  }
  // An OPTIONAL body (`requestBody.required` absent) is left out, like an
  // optional query parameter — the snippet shows what the types REQUIRE.
  if (op.body?.required) parts.push(`${bodyArg(op.body)}: /* … */ ${op.body.encoding === 'text' ? "''" : op.body.encoding === 'binary' ? 'new Blob()' : '{}'}`)
  return parts.length > 0 ? `{ ${parts.join(', ')} }` : ''
}

function sample(type: IrType): string {
  switch (type.kind) {
    case 'number':
      return '1'
    case 'boolean':
      return 'true'
    case 'string':
      // An enum VALUE is spec text landing in a string literal, so it takes
      // the same escaper the code emitters use. A raw `'` ended the literal
      // and a raw newline ended the LINE, which is how a value breaks out of
      // a fenced snippet.
      return "'…'"
    case 'enum': {
      // An enum VALUE is spec text landing in a string literal, so it takes
      // the same escaper the code emitters use. A raw `'` ended the literal
      // and a raw newline ended the LINE, which is how a value breaks out of
      // a fenced snippet.
      const v = type.values[0]
      return typeof v === 'string' ? q(v) : String(v)
    }
    default:
      return "'…'"
  }
}

function reachLabel(info: { reach: Reach; reason?: string | undefined } | undefined): string {
  if (!info) return 'web'
  return info.reach === 'web+native' ? 'web · iOS · Android' : 'web only'
}

function countReach(doc: IrDocument, opts: DocsOptions): { native: number; total: number } {
  if (!opts.reach) return { native: 0, total: 0 }
  let native = 0
  for (const op of doc.operations) {
    if (opts.reach.get(op.id)?.reach === 'web+native') native++
  }
  return { native, total: doc.operations.length }
}

function modelsPage(doc: IrDocument): GeneratedFile {
  const lines = frontmatter('Models', `${doc.models.length} generated types.`)
  lines.push('# Models', '')
  lines.push(`[← ${doc.title}](./index.md)`, '')
  for (const model of doc.models) {
    lines.push(`## \`${model.name}\``, '')
    if (model.doc) lines.push(md(model.doc), '')
    lines.push('```ts', `type ${model.name} = ${tsType(model.type, 0, false)}`, '```', '')
  }
  return { path: `${DOCS_DIR}/models.md`, contents: `${lines.join('\n')}\n` }
}

/** A type rendered for a table cell — one line, pipes escaped. */
function typeCell(type: IrType | undefined): string {
  if (!type) return '_no content_'
  return `\`${mdCell(tsType(type, 0, false).replace(/\s*\n\s*/g, ' '))}\``
}

/**
 * Escape a value for a Markdown table CELL.
 *
 * The BACKSLASH has to go first, and getting that order wrong is not a style
 * point -- it reopens the exact hole the escape exists to close. Escaping only
 * the pipe turns an input of `\|` into `\\|`, which Markdown reads as an
 * escaped BACKSLASH followed by a LIVE pipe, so the cell splits anyway. Escape
 * the escape character first and both survive.
 *
 * Same rule the `q()` string-literal escaper in `writer.ts` follows for the
 * same reason, in a different syntax.
 */
function mdCell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
}

/**
 * Spec text, safe in a Markdown TABLE cell.
 *
 * A raw `|` splits the cell and a newline ends the ROW, so a `description`
 * carrying either does not merely look wrong -- it restructures the table and
 * silently drops the rest of the value. Same class as the block-comment and
 * line-comment escapes the code emitters use, in a third syntax.
 */
function md(value: string): string {
  return mdCell(safeBlockComment(value).replace(/[\r\n]+/g, ' ')).trim()
}
