/**
 * File construction: an import manager and a small source builder.
 *
 * The import manager is the part worth having. Emitting correct, deduplicated,
 * correctly-ordered imports across a few hundred generated files is the single
 * most error-prone mechanical job in a generator, and it is exactly the job a
 * component tree with a context (Kubb's approach) exists to do. A map keyed by
 * module specifier does the same work with a stack trace you can read.
 *
 * Import ORDER is deterministic — sorted by specifier, named bindings sorted
 * within each — so an unchanged spec regenerates byte-identically. Anything
 * less makes every regeneration an unreviewable diff.
 */

export interface GeneratedFile {
  /** Path relative to the output root, POSIX separators. */
  path: string
  contents: string
}

export class SourceFile {
  /** module specifier -> named bindings. */
  private readonly named = new Map<string, Set<string>>()
  /** module specifier -> type-only named bindings. */
  private readonly typeNamed = new Map<string, Set<string>>()
  private readonly body: string[] = []

  constructor(readonly path: string) {}

  /** Record a value import. Repeated calls collapse. */
  import(from: string, ...names: string[]): this {
    add(this.named, from, names)
    return this
  }

  /**
   * Record a TYPE-only import.
   *
   * Kept separate from value imports because `import type` is fully erased —
   * it costs nothing at runtime and, on the native path, never trips PMTC's
   * "no native lowering" warning for the module it came from.
   */
  importType(from: string, ...names: string[]): this {
    add(this.typeNamed, from, names)
    return this
  }

  /** Append a line (or a blank line with no argument). */
  line(text = ''): this {
    this.body.push(text)
    return this
  }

  /** Append several lines. */
  lines(...text: string[]): this {
    for (const t of text) this.body.push(t)
    return this
  }

  /** Append a JSDoc block, if there is anything to say. */
  doc(...parts: (string | undefined)[]): this {
    const kept = parts.filter((p): p is string => typeof p === 'string' && p.trim().length > 0)
    if (kept.length === 0) return this
    const flat = kept.flatMap((p) => p.split('\n'))
    if (flat.length === 1) {
      this.body.push(`/** ${flat[0]} */`)
      return this
    }
    this.body.push('/**')
    for (const l of flat) this.body.push(` * ${l}`.trimEnd())
    this.body.push(' */')
    return this
  }

  build(header: string): GeneratedFile {
    const out: string[] = [header, '']
    for (const spec of [...this.typeNamed.keys()].sort()) {
      const names = [...(this.typeNamed.get(spec) as Set<string>)].sort()
      // A binding imported both as a value and as a type only needs the value
      // import — emitting both is a duplicate-identifier error.
      const valueSide = this.named.get(spec)
      const only = names.filter((n) => !valueSide?.has(n))
      if (only.length > 0) out.push(`import type { ${only.join(', ')} } from '${spec}'`)
    }
    for (const spec of [...this.named.keys()].sort()) {
      const names = [...(this.named.get(spec) as Set<string>)].sort()
      if (names.length > 0) out.push(`import { ${names.join(', ')} } from '${spec}'`)
    }
    if (out.length > 2) out.push('')
    out.push(...this.body)
    return { path: this.path, contents: `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n` }
  }
}

function add(map: Map<string, Set<string>>, from: string, names: string[]): void {
  let set = map.get(from)
  if (!set) {
    set = new Set()
    map.set(from, set)
  }
  for (const n of names) set.add(n)
}

/**
 * A relative specifier from one generated file to another.
 *
 * Always prefixed with `./` or `../` and always extensionless — the repo's
 * packages resolve through export maps and bundlers, and an emitted `.ts`
 * extension breaks the published `lib/` build.
 */
export function relativeSpecifier(fromPath: string, toPath: string): string {
  const from = fromPath.split('/').slice(0, -1)
  const to = toPath.replace(/\.tsx?$/, '').split('/')
  let i = 0
  while (i < from.length && i < to.length - 1 && from[i] === to[i]) i++
  const up = from.length - i
  const rest = to.slice(i)
  const prefix = up === 0 ? './' : '../'.repeat(up)
  return `${prefix}${rest.join('/')}`
}

/** The header every generated file carries. */
export function banner(specTitle: string, specVersion: string): string {
  return [
    '/* eslint-disable */',
    '// @generated by @pyreon/lathe — DO NOT EDIT.',
    `// source: ${specTitle} ${specVersion}`,
    '//',
    '// Re-run `lathe generate` to update. Edits here are lost on the next run;',
    '// to change the output, change the spec or the emitter.',
  ].join('\n')
}

/** Render a TS string literal with single quotes, matching repo style. */
export function q(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
}
