// Scaffold generator for `create-multiplatform` — turns one project name
// into a complete web + iOS + Android project sharing ONE `src/App.tsx`.
//
// Pure function: `buildScaffold(opts) → FileSpec[]`. No filesystem access
// here (the CLI half writes the files) — so the generator is unit-testable
// in isolation, and the generated shared `App.tsx` can be fed straight
// through PMTC's `transform()` to prove it compiles to SwiftUI + Compose.
//
// Templates mirror the proven `examples/native-todomvc-{web,ios,android}`
// shells (same XcodeGen / Gradle / Vite shapes), parameterized by name. The
// per-platform PROJECT configs (project.yml, Gradle, Info.plist, Vite) are
// copied from those maintained shells; what this package verifies itself is
// the GENERATOR output structure + that the shared source is real
// PMTC-compilable canonical-primitive code. Full device builds are the
// `native-device` CI gate's job (a separate, infra-gated arc).

/** A single file the scaffold emits, relative to the project root. */
export interface FileSpec {
  /** POSIX-style relative path, e.g. `ios/Sources/App.swift`. */
  path: string
  /** Full file contents. */
  content: string
}

export interface ScaffoldOptions {
  /** Project name — kebab-case recommended (`my-app`). Drives the Swift
   *  `@main` struct, the Gradle `rootProject.name`, the bundle id, and the
   *  web `<title>`. */
  name: string
}

/** `my-app` → `MyApp` (PascalCase; used for the Swift struct + display name). */
export function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

/** `My-App` → `myapp` (lowercased, separators stripped) — a valid Android
 *  package segment + bundle-id leaf. */
export function toIdentifierLeaf(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '')
}

/**
 * Build the full file tree for a new multiplatform project. Returns the
 * files in a stable order; the CLT writes each one under the target dir.
 */
export function buildScaffold(opts: ScaffoldOptions): FileSpec[] {
  const name = opts.name.trim()
  if (name.length === 0) throw new Error('[create-multiplatform] project name is required')
  const pascal = toPascalCase(name)
  const leaf = toIdentifierLeaf(name)
  const androidPkg = `com.example.${leaf}`
  const androidPkgPath = androidPkg.replace(/\./g, '/')
  const bundleId = `com.example.${pascal}`

  const files: FileSpec[] = []
  const add = (path: string, content: string) => files.push({ path, content })

  // ── Shared source — the ONE file all three targets render ────────────────
  add(
    'src/App.tsx',
    `// The single source for web, iOS, and Android. Uses the canonical
// @pyreon/primitives vocabulary — the web build auto-imports the DOM
// runtimes; PMTC compiles the same tags to SwiftUI (iOS) + Compose
// (Android) via its canonical-primitives table.

import { signal } from '@pyreon/reactivity'
import { Stack, Text, Button } from '@pyreon/primitives'

export function App() {
  const count = signal(0)
  return (
    <Stack gap="md" align="center">
      <Text>{count}</Text>
      <Button onPress={() => count.set(count() + 1)}>Increment</Button>
    </Stack>
  )
}
`,
  )

  // ── Web target ───────────────────────────────────────────────────────────
  add(
    '.gitignore',
    `node_modules/
dist/
# Android build output + local SDK pin
android/.gradle/
android/build/
android/app/build/
android/local.properties
# iOS generated project + build output
ios/*.xcodeproj/
ios/build/
# Release signing material — self-generated by
# scripts/ensure-release-keystore.sh, NEVER committed (a real upload key
# drops into the same two files; keep them out of git either way).
android/release.keystore
android/keystore.properties
`,
  )
  add(
    'package.json',
    `${JSON.stringify(
      {
        name,
        version: '0.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          lint: 'pyreon-lint .',
          'build:ios': 'bash scripts/build-ios.sh',
          'build:android': 'bash scripts/build-android.sh',
          // Release lane: self-signed keystore (credential-free — Play App
          // Signing re-signs uploads) + a signed, R8-minified release APK.
          'release:keystore': 'bash scripts/ensure-release-keystore.sh',
          'release:android': 'bash scripts/ensure-release-keystore.sh && cd android && gradle assembleRelease',
        },
        dependencies: {
          '@pyreon/core': 'latest',
          '@pyreon/primitives': 'latest',
          '@pyreon/reactivity': 'latest',
          '@pyreon/runtime-dom': 'latest',
        },
        devDependencies: {
          '@pyreon/vite-plugin': 'latest',
          '@pyreon/native-cli': 'latest',
          // Native runtimes — installed into node_modules so the iOS
          // SPM project (project.yml `packages:`) and the Android Gradle
          // source-sets reference them by node_modules path. The emitted
          // Swift `import PyreonRuntime`/`PyreonRouter` + Kotlin
          // `PyreonReactivity`/`PyreonFetch`/… resolve against these.
          '@pyreon/native-runtime-swift': 'latest',
          '@pyreon/native-router-swift': 'latest',
          '@pyreon/native-runtime-kotlin': 'latest',
          '@pyreon/native-router-kotlin': 'latest',
          '@pyreon/lint': 'latest',
          typescript: '^6.0.0',
          vite: '^8.0.0',
        },
      },
      null,
      2,
    )}\n`,
  )
  // A multiplatform app's shared source has to survive THREE targets, and the
  // `portable` rule group is the only thing that says so before a build does.
  // It is opt-in — correctly, since it is noise in a web-only project — which
  // means a scaffolder that ships no config at all hands you a native app with
  // the native rules switched off. The `groups` key is also the shape worth
  // showing: one line moves a whole tier, so an app states its platform story
  // in config rather than rule by rule.
  //
  // `portablePaths` is not optional decoration. `no-out-of-subset-construct`
  // fires on NOTHING until it is told which files must travel — deliberately,
  // because run unscoped it produces thousands of findings in code entitled to
  // the whole language, and "which files reach iOS and Android" cannot be
  // inferred from a file's contents. A scaffolder is the one caller that knows
  // the answer, having just created `src/`. Without this the group key looks
  // like it enabled something and enables nothing.
  //
  // `warn`, not `error`, to match how PMTC itself reports an out-of-subset
  // construct: it names the shape and keeps going.
  add(
    '.pyreonlintrc.json',
    `${JSON.stringify(
      {
        $schema: 'node_modules/@pyreon/lint/schema/pyreonlintrc.schema.json',
        preset: 'recommended',
        groups: { portable: 'warn' },
        rules: {
          'pyreon/no-out-of-subset-construct': ['warn', { portablePaths: ['src/'] }],
        },
      },
      null,
      2,
    )}\n`,
  )
  add(
    'index.html',
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${pascal} — Web</title>
  </head>
  <body>
    <div id="app" data-testid="app-root"></div>
    <script type="module" src="/src/entry-web.tsx"></script>
  </body>
</html>
`,
  )
  add(
    'vite.config.ts',
    `import pyreon from '@pyreon/vite-plugin'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [pyreon()],
})
`,
  )
  add(
    'src/entry-web.tsx',
    `// Web entry — boots the shared App into #app via @pyreon/runtime-dom.
import { mount } from '@pyreon/runtime-dom'
import { App } from './App'

const root = document.getElementById('app')
if (root === null) throw new Error('#app element missing from index.html')
mount(App, root)
`,
  )
  add(
    'tsconfig.json',
    `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ESNext',
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'preserve',
          jsxImportSource: '@pyreon/core',
          strict: true,
          noEmit: true,
          skipLibCheck: true,
        },
        include: ['src', 'vite.config.ts'],
      },
      null,
      2,
    )}\n`,
  )

  // ── iOS target (XcodeGen) ─────────────────────────────────────────────────
  add(
    'ios/project.yml',
    `# XcodeGen project spec. Run \`xcodegen generate\` here, then open the
# generated .xcodeproj. The preBuildScript compiles src/App.tsx → Swift
# before each Xcode build (idempotent).

name: ${pascal}

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '17.0'

# Pyreon native runtimes as local SPM packages — they ship their Swift
# sources via npm, so after \`npm install\` they live under node_modules
# and XcodeGen consumes them by path. This spec lives in ios/, so the
# paths are relative to ios/ (node_modules is one level up at the project
# root). The emitted generated/App.swift's \`import PyreonRuntime\` /
# \`import PyreonRouter\` resolve against these.
packages:
  PyreonRuntime:
    path: ../node_modules/@pyreon/native-runtime-swift
  PyreonRouter:
    path: ../node_modules/@pyreon/native-router-swift

preBuildScripts:
  # SRCROOT is the .xcodeproj dir (ios/); scripts/ lives at the project
  # root, one level up.
  - script: |
      bash "\${SRCROOT}/../scripts/build-ios.sh"
    name: '[Pyreon] Compile src/App.tsx → generated/App.swift'
    runOnlyWhenInstalling: false
    basedOnDependencyAnalysis: false

targets:
  ${pascal}:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    dependencies:
      - package: PyreonRuntime
      - package: PyreonRouter
    sources:
      - path: Sources
        type: group
      - path: generated
        type: group
        optional: true
      # WebView viz bundle (\`web/\` → \`pyreon-native stage-web\`). A
      # \`type: group\` flattens the staged html/js/css into the app
      # bundle's resource root, so PyreonWebView's
      # \`Bundle.main.url(forResource:)\` resolves \`<WebView src="…">\`.
      - path: WebContent
        type: group
        optional: true
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: 0.0.1
        CFBundleVersion: '1'
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleId}
        SWIFT_VERSION: '5.0'
        CODE_SIGN_STYLE: Automatic
`,
  )
  add(
    // NOT "App.swift" — the emitted component file is generated/App.swift
    // (src/App.tsx → App.swift); two files named App.swift in one target
    // is a Swift compile error ("filename used twice").
    'ios/Sources/Main.swift',
    `// @main entry point. SwiftUI App protocol — the canonical iOS entrypoint.
import SwiftUI

// \`SwiftUI.App\` (fully qualified) — the emitted component from
// src/App.tsx is \`struct App: View\`, which shadows the bare \`App\`
// protocol name in this module; without the qualifier this conformance
// would resolve to that struct (a non-protocol type) and fail.
@main
struct ${pascal}App: SwiftUI.App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`,
  )
  add(
    'ios/Sources/ContentView.swift',
    `// Root view — mounts the Pyreon-emitted App() from generated/App.swift
// (produced by scripts/build-ios.sh running \`pyreon-native build\`).
import SwiftUI

struct ContentView: View {
    var body: some View {
        App()
    }
}
`,
  )
  add(
    'ios/Info.plist',
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.0.1</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
</dict>
</plist>
`,
  )
  add(
    'scripts/build-ios.sh',
    `#!/usr/bin/env bash
# Compile src/App.tsx → ios/generated/App.swift via pyreon-native.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "\${SCRIPT_DIR}/.." && pwd)"
mkdir -p "\${PROJECT_DIR}/ios/generated"
npx pyreon-native build --target=ios --source="\${PROJECT_DIR}/src" --out="\${PROJECT_DIR}/ios/generated"
# Asset pipeline: shared assets/ → Assets.xcassets (skipped when empty).
if [[ -d "\${PROJECT_DIR}/assets" ]]; then
  npx pyreon-native assets --target=ios --source="\${PROJECT_DIR}/assets" --out="\${PROJECT_DIR}/ios"
fi
# WebView viz bundle: shared web/ → ios/WebContent (skipped when empty).
if [[ -d "\${PROJECT_DIR}/web" ]]; then
  npx pyreon-native stage-web --target=ios --source="\${PROJECT_DIR}/web" --out="\${PROJECT_DIR}/ios"
fi
`,
  )

  // ── Android target (Gradle) ───────────────────────────────────────────────
  add(
    'android/settings.gradle.kts',
    `pluginManagement {
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = "${pascal}"
include(":app")
`,
  )
  add(
    'android/build.gradle.kts',
    `plugins {
    id("com.android.application") version "8.7.0" apply false
    kotlin("android") version "2.0.21" apply false
    // The Pyreon Kotlin runtime sources use @Serializable (useFetch /
    // loader payloads); the app module applies this plugin, so its
    // version must be declared (apply false) at the root or Gradle can't
    // resolve "org.jetbrains.kotlin.plugin.serialization".
    kotlin("plugin.serialization") version "2.0.21" apply false
}
`,
  )
  add(
    'android/gradle.properties',
    `org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
`,
  )
  add(
    'android/app/build.gradle.kts',
    `// java.util.Properties by explicit import — inside android {} the bare
// \`java\` resolves to Gradle's JavaPluginExtension accessor, shadowing the
// package root (\`Unresolved reference 'util'\`).
import java.util.Properties

plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("plugin.serialization")
    id("org.jetbrains.kotlin.plugin.compose") version "2.0.21"
}

android {
    namespace = "${androidPkg}"
    compileSdk = 35
    defaultConfig {
        applicationId = "${bundleId}"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.0.1"
    }
    buildFeatures { compose = true }
    // Production release build: R8 minify + shrink (the Play Store path).
    // The Pyreon Kotlin runtime uses kotlinx-serialization (useFetch /
    // loader payloads), which ships its OWN R8 keep rules
    // (META-INF/.../kotlinx-serialization-r8.pro, auto-applied), so the
    // framework's @Serializable types survive minification with no manual
    // rules — verified by a real \`gradle assembleRelease\` of a useFetch
    // app. Add app-specific keep rules to proguard-rules.pro.
    // Release SIGNING: a release build that cannot be signed cannot be
    // INSTALLED, so an unsigned assembleRelease proves compilation and
    // nothing more. \`bash scripts/ensure-release-keystore.sh\` generates a
    // SELF-SIGNED keystore + android/keystore.properties (both
    // gitignored) — Play App Signing re-signs store uploads, so the
    // local key proves the full sign→install→run path credential-free;
    // a real upload key drops into the same properties shape.
    signingConfigs {
        create("release") {
            val props = rootProject.file("keystore.properties")
            if (props.exists()) {
                val ks = Properties().apply { props.inputStream().use { load(it) } }
                storeFile = rootProject.file(ks.getProperty("storeFile"))
                storePassword = ks.getProperty("storePassword")
                keyAlias = ks.getProperty("keyAlias")
                keyPassword = ks.getProperty("keyPassword")
            }
            // Missing keystore.properties → assembleRelease fails LOUDLY
            // at the signing step. Never falls back to the debug key.
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            signingConfig = signingConfigs.getByName("release")
            // Test-APK-only rules: androidx.test references compile-only
            // errorprone annotations R8 error-flags when the androidTest APK
            // is minified under testBuildType=release.
            testProguardFiles("proguard-test-rules.pro")
            // Runner-startup keep, applied ONLY in the release-test lane —
            // the shipping config never sees it (see the .pro file header).
            if (project.hasProperty("pyreonReleaseTests")) {
                proguardFile("proguard-releasetest-keep.pro")
            }
        }
    }
    // \`gradle -PpyreonReleaseTests connectedCheck\` re-runs the app's
    // instrumented tests against the SIGNED, R8-MINIFIED release build
    // (same-certificate instrumentation makes a non-debuggable app
    // testable) — the artifact a user would install, not the debug twin.
    testBuildType = if (project.hasProperty("pyreonReleaseTests")) "release" else "debug"
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    // The Pyreon Kotlin runtimes ship source-only via npm (no AAR), so
    // their src/main/kotlin dirs are extra source roots. The resolved,
    // hoisting/pnpm-safe list is written to pyreon-native.srcdirs by
    // pyreon-native wire (run from scripts/build-android.sh, BEFORE this
    // configures). Prefer that file; fall back to the legacy fixed
    // node_modules paths for a flat layout where wire hasn't run yet.
    sourceSets {
        getByName("main") {
            kotlin {
                val srcDirsFile = file("pyreon-native.srcdirs")
                val resolved = if (srcDirsFile.exists()) {
                    srcDirsFile.readLines()
                        .map { it.trim() }
                        .filter { it.isNotEmpty() && !it.startsWith("#") }
                } else emptyList()
                if (resolved.isNotEmpty()) {
                    resolved.forEach { srcDir(it) }
                } else {
                    // Fallback (flat layout / wire not yet run).
                    srcDir("../../node_modules/@pyreon/native-runtime-kotlin/src/main/kotlin")
                    srcDir("../../node_modules/@pyreon/native-router-kotlin/src/main/kotlin")
                }
            }
        }
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom:2024.10.01"))
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material")
    implementation("androidx.compose.runtime:runtime-saveable")
    // Required by the Pyreon Kotlin runtime sources (srcDir above):
    // useFetch/loader need kotlinx-serialization + coroutines; storage needs core-ktx.
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
    implementation("androidx.core:core-ktx:1.13.1")
    // <Icon> emit references Icons.Filled.* at compile time (core set).
    implementation("androidx.compose.material:material-icons-core")
    // Remote <Image src="http…"> → Coil's AsyncImage.
    implementation("io.coil-kt:coil-compose:2.7.0")
    // okhttp — PyreonWebSocketOkHttp.kt / PyreonHttpOkHttp.kt (runtime srcDir
    // above) import okhttp3; the srcDir compiles ALL runtime sources, so the
    // artifact is required whether the app uses websockets or not. Absent
    // until the <Video> arc: the runtime gained these files after this
    // template was last touched, masked because scaffolds install the runtime
    // from npm, which lagged the workspace — the next release would have
    // shipped every scaffolded Android app broken.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // media3 — PyreonVideoPlayerAndroid.kt (<Video> primitive) imports
    // androidx.media3.*. Same deal; R8 strips unused classes from release.
    implementation("androidx.media3:media3-exoplayer:1.4.1")
    implementation("androidx.media3:media3-ui:1.4.1")
}

// Re-run the .tsx → .kt compile on every build (mirrors iOS preBuildScript).
tasks.register<Exec>("pyreonCompile") {
    workingDir = projectDir.parentFile.parentFile
    commandLine("bash", "scripts/build-android.sh")
}
tasks.named("preBuild") { dependsOn("pyreonCompile") }
`,
  )
  add(
    'android/app/proguard-releasetest-keep.pro',
    `# Applied ONLY when -PpyreonReleaseTests is set — the SHIPPING release
# config never includes this file.
#
# Instrumentation shares the app's process, and AGP dedups every library
# both APKs use OUT of the test APK — so the test frameworks resolve
# androidx.tracing, the Kotlin stdlib, kotlinx-coroutines and compose-ui
# test hooks from the APP's classpath, where R8 SHRINKING keeps only what
# app code reaches. Building this lane on Pyreon's own TodoMVC example
# surfaced the failure one class at a time (Trace → kotlin.LazyKt →
# kotlinx.coroutines.JobKt → compose InfiniteAnimationPolicy); an
# enumerated keep list is whack-a-mole, so the TESTED build disables
# SHRINKING wholesale. Obfuscation + optimization stay ON — renamed
# reflection lookups and inlining are still exercised, and the shipped
# APK's config is untouched.
-dontshrink
`,
  )
  add(
    'android/app/proguard-test-rules.pro',
    `# R8 rules for the TEST APK only (testProguardFiles — never reaches the
# shipping release APK's config). androidx.test references error-prone's
# COMPILE-ONLY annotations, absent at runtime by design; R8 error-flags the
# missing classes when the androidTest APK is minified under
# testBuildType=release. These dontwarns are R8's own suggested rules for
# annotation-only classes — not a masked minification failure.
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.MustBeClosed
`,
  )
  add(
    'android/app/proguard-rules.pro',
    `# R8 / ProGuard rules for the release build.
#
# The Pyreon Kotlin runtime needs NO manual rules — its only
# reflection-sensitive dependency is kotlinx-serialization (useFetch /
# loader payloads), which ships its own keep rules
# (META-INF/com.android.tools/r8/kotlinx-serialization-r8.pro) that R8
# applies automatically. A real \`./gradlew assembleRelease\` with
# minify enabled builds clean against the runtime out of the box.
#
# Add keep rules for YOUR app's own reflection / serialization here, e.g.:
#   -keep class com.example.${leaf}.model.** { *; }
`,
  )
  add(
    'android/app/src/main/AndroidManifest.xml',
    `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Required the moment the shared source uses useFetch — without
         it, socket creation fails with the opaque
         \`SocketException: socket failed: EPERM\` (a real device-CI
         finding). Harmless for apps that never touch the network. -->
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:label="${pascal}"
        android:allowBackup="true">
        <activity
            android:name="${androidPkg}.MainActivity"
            android:exported="true"
            android:theme="@android:style/Theme.Material.Light.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`,
  )
  add(
    `android/app/src/main/kotlin/${androidPkgPath}/MainActivity.kt`,
    `// Root activity — mounts the Pyreon-emitted App() from generated/App.kt.
package ${androidPkg}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import ${androidPkg}.generated.App

// ComponentActivity (NOT plain android.app.Activity) — Compose's
// setContent {} is an extension on ComponentActivity; a plain Activity
// fails to resolve it (receiver type mismatch).
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            App()
        }
    }
}
`,
  )
  add(
    'scripts/build-android.sh',
    `#!/usr/bin/env bash
# Compile src/App.tsx → android/app/src/main/kotlin/${androidPkgPath}/generated/App.kt
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "\${SCRIPT_DIR}/.." && pwd)"
OUT="\${PROJECT_DIR}/android/app/src/main/kotlin/${androidPkgPath}/generated"
mkdir -p "\${OUT}"
# --kotlin-package stamps the generated .kt with the FQN MainActivity
# imports (\`${androidPkg}.generated.App\`); without it the emit lands in
# Kotlin's anonymous root package and the import fails to resolve.
npx pyreon-native build --target=android --source="\${PROJECT_DIR}/src" --out="\${OUT}" --kotlin-package=${androidPkg}.generated
# Resolve the Pyreon native Kotlin source roots (base runtime/router + any
# co-located feature native/kotlin/) and write them where build.gradle.kts
# reads them. Hoisting/pnpm-safe — the fix for a monorepo where the runtime
# hoists to the workspace root and the fixed ../../node_modules path dangles.
# This runs BEFORE gradle configures (npm run build:android precedes the
# gradle build), so the srcdirs file exists at Gradle config time.
npx pyreon-native wire --app="\${PROJECT_DIR}" --android-out="\${PROJECT_DIR}/android/app/pyreon-native.srcdirs"
# Asset pipeline: shared assets/ → res/drawable-* (skipped when empty).
if [[ -d "\${PROJECT_DIR}/assets" ]]; then
  npx pyreon-native assets --target=android --source="\${PROJECT_DIR}/assets" --out="\${PROJECT_DIR}/android/app/src/main"
fi
# WebView viz bundle: shared web/ → android assets/ (skipped when empty).
if [[ -d "\${PROJECT_DIR}/web" ]]; then
  npx pyreon-native stage-web --target=android --source="\${PROJECT_DIR}/web" --out="\${PROJECT_DIR}/android/app/src/main"
fi
`,
  )
  add(
    'scripts/ensure-release-keystore.sh',
    `#!/usr/bin/env bash
# Generate a SELF-SIGNED Android release keystore + android/keystore.properties
# if absent. Credential-free by design: Play App Signing re-signs store
# uploads, so a locally-generated key proves the full sign→install→run path
# without any store account; a real upload key drops into the same
# keystore.properties shape. Both outputs are gitignored. Idempotent — an
# existing keystore.properties (e.g. your real upload key) is never touched.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
cd "\${SCRIPT_DIR}/../android"

if [ -f keystore.properties ]; then
  echo "[pyreon] android/keystore.properties present — keeping it."
  exit 0
fi

keytool -genkeypair -v -keystore release.keystore -alias pyreon-release \\
  -keyalg RSA -keysize 2048 -validity 10000 \\
  -storepass pyreon-local -keypass pyreon-local \\
  -dname "CN=Pyreon Local Release, OU=dev, O=pyreon, C=US"

cat > keystore.properties <<'PROPS'
storeFile=release.keystore
storePassword=pyreon-local
keyAlias=pyreon-release
keyPassword=pyreon-local
PROPS

echo "[pyreon] Self-signed release keystore generated (android/release.keystore)."
`,
  )

  // ── README ────────────────────────────────────────────────────────────────
  add(
    'README.md',
    `# ${pascal}

A multiplatform Pyreon app — one \`src/App.tsx\` source rendered on **web**,
**iOS** (SwiftUI), and **Android** (Jetpack Compose).

Every dependency — the web packages AND the native toolchain
(\`@pyreon/native-cli\`, the Swift/Kotlin runtimes and routers) — installs from
npm. The iOS project consumes \`@pyreon/native-runtime-swift\` straight out of
\`node_modules\` as a local SwiftPM package, and the Android project adds the
Kotlin runtime as a Gradle source set, so \`npm install\` is the only fetch
step. Building the native targets additionally needs the platform SDKs on this
machine (Xcode + xcodegen for iOS; the Android SDK + Gradle for Android) — see
<https://pyreon.dev/docs/multiplatform>.

## Web

\`\`\`bash
npm install
npm run dev        # vite dev server
\`\`\`

## iOS (requires Xcode + xcodegen)

\`\`\`bash
npm run build:ios  # src/App.tsx → ios/generated/App.swift
cd ios && xcodegen generate && open ${pascal}.xcodeproj
\`\`\`

## Android (requires the Android SDK + Gradle)

\`\`\`bash
npm run build:android   # src/App.tsx → android/.../generated/App.kt
cd android && ./gradlew assembleDebug
\`\`\`

Edit \`src/App.tsx\` — every target re-compiles from that single file.

## Android release build (signed + R8-minified)

\`\`\`bash
npm run release:android   # generates a self-signed keystore if absent, then assembleRelease
\`\`\`

The keystore is SELF-SIGNED and generated locally (\`android/release.keystore\`
+ \`android/keystore.properties\`, both gitignored) — Play App Signing re-signs
store uploads, so this key is enough to install and run the real release
artifact on a device today. When you create a Play Console upload key, point
\`android/keystore.properties\` at it; nothing else changes. To re-run the
app's instrumented tests against the signed, minified release build:
\`cd android && gradle -PpyreonReleaseTests connectedCheck\`. The build already
carries the one extra piece release-mode testing needs:
\`proguard-releasetest-keep.pro\` disables R8 SHRINKING for the TESTED build
only (obfuscation + optimization stay on) — the test frameworks resolve the
Kotlin stdlib, coroutines, tracing and compose test hooks from the app's
classpath, which shrinking strips of everything app code doesn't reach.
Applied only under the property; the shipping config is untouched.

## Adding a platform capability the framework does not ship

The canonical primitives and the built-in hooks cover the common surface. For
anything else — Bluetooth, ARKit, a payments or analytics SDK — \`useNativeModule\`
lowers to a class **you** provide, so you are not blocked on a framework release:

\`\`\`tsx
import { defineNativeModule, useNativeModule } from '@pyreon/primitives'

type Bluetooth = { connect(id: string): Promise<boolean> }

// The WEB implementation. Native targets never run this — the compiler
// replaces the call with your platform class.
defineNativeModule<Bluetooth>('Bluetooth', { connect: async () => false })

function Pairing() {
  const bt = useNativeModule<Bluetooth>('Bluetooth')
  return <Button onPress={() => { void bt.connect('cuff') }}>Connect</Button>
}
\`\`\`

Then drop in the platform halves as ordinary app code:

\`\`\`swift
// ios/Bluetooth.swift — a NO-ARGUMENT initialiser
final class Bluetooth {
  func connect(_ id: String) async -> Bool { true }
}
\`\`\`

\`\`\`kotlin
// android/…/Bluetooth.kt — a SINGLE Context parameter, and declared in the
// package your generated sources use (the --kotlin-package value), since the
// emit references the class unqualified.
class Bluetooth(private val context: Context) {
  suspend fun connect(id: String): Boolean = true
}
\`\`\`

The class name must match the string, and method names/arities must match what
your \`.tsx\` calls — the compiler passes them through verbatim, so \`swiftc\` and
\`kotlinc\` type-check the result in your own build. \`await\` works with no extra
setup.
`,
  )

  return files
}
