#!/usr/bin/env bun
/**
 * Generate the TROUBLESHOOTING reference from `.claude/rules/anti-patterns.md`
 * — Pyreon's equivalent of Next.js's `/docs/messages/` error reference, and a
 * surface no other framework ships. Reuses the SAME parser that powers MCP
 * `get_anti_patterns` (`packages/tools/mcp/src/anti-patterns.ts`), so the docs
 * and the MCP tool can never drift.
 *
 * Emits one `troubleshooting/<category>.md` per anti-pattern category (each
 * entry = name + body + the detector code that catches it, where one exists),
 * a `troubleshooting.md` index, and `troubleshooting-nav.generated.ts` (the
 * "Troubleshooting" sidebar tier). Single source of truth: anti-patterns.md.
 * Run: `bun docs/scripts/gen-troubleshooting.ts` from the repo root.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseAntiPatterns, type AntiPatternEntry } from '../../packages/tools/mcp/src/anti-patterns'
import { escFlow, yaml } from './_md-safe'

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const SRC = join(REPO_ROOT, '.claude', 'rules', 'anti-patterns.md')
const DOCS = join(REPO_ROOT, 'docs', 'src', 'content', 'docs')
const OUT_DIR = join(DOCS, 'troubleshooting')
const NAV_FILE = join(REPO_ROOT, 'docs', 'src', 'troubleshooting-nav.generated.ts')

const entries = parseAntiPatterns(readFileSync(SRC, 'utf8'))

// Group by category, preserving first-seen order + the file's heading text.
const byCat = new Map<string, { heading: string; items: AntiPatternEntry[] }>()
for (const e of entries) {
  const g = byCat.get(e.category) ?? { heading: e.categoryHeading, items: [] }
  g.items.push(e)
  byCat.set(e.category, g)
}

function renderEntry(e: AntiPatternEntry): string {
  const parts = [`### ${escFlow(e.name)}`, escFlow(e.description)]
  if (e.detectorCodes.length) {
    parts.push(
      '**Detected by:** ' +
        e.detectorCodes.map((c) => `\`${c}\``).join(' · ') +
        ' — surfaced by `@pyreon/lint` / `pyreon doctor` / MCP `validate`.',
    )
  }
  return parts.join('\n\n')
}

mkdirSync(OUT_DIR, { recursive: true })
const navItems: { text: string; slug: string }[] = [{ text: 'Overview', slug: 'troubleshooting' }]
let pageCount = 0

for (const [cat, { heading, items }] of byCat) {
  const out: string[] = []
  out.push('---')
  out.push(`title: ${yaml(heading)}`)
  out.push(`description: ${yaml(`Common ${heading.toLowerCase()} in Pyreon and how to fix them.`)}`)
  out.push('---')
  out.push('')
  out.push(`# ${heading}`)
  out.push('')
  out.push(
    '> **Generated** from `.claude/rules/anti-patterns.md` (the same source as MCP `get_anti_patterns`). Each entry is a real mistake + its fix; where a detector code is listed, the linter / `pyreon doctor` / MCP `validate` catches it automatically.',
  )
  out.push('')
  for (const e of items) {
    out.push(renderEntry(e))
    out.push('')
    out.push('---')
    out.push('')
  }
  writeFileSync(join(OUT_DIR, `${cat}.md`), out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n')
  navItems.push({ text: heading, slug: `troubleshooting/${cat}` })
  pageCount++
}

// Index page.
const idx: string[] = ['---', `title: ${yaml('Troubleshooting')}`, `description: ${yaml('Common Pyreon mistakes and their fixes, grouped by area — the error & anti-pattern reference.')}`, '---', '']
idx.push('# Troubleshooting')
idx.push('')
idx.push(
  `Common mistakes and anti-patterns across Pyreon, grouped by area, each with its fix. Distilled from the framework's own anti-pattern catalog (${entries.length} entries) — the same source MCP \`get_anti_patterns\` serves to AI agents. Many are caught automatically by [\`@pyreon/lint\`](/docs/lint), \`pyreon doctor\`, or MCP \`validate\`; the detector code is noted on each entry that has one.`,
)
idx.push('')
idx.push('## Categories')
idx.push('')
for (const [cat, { heading, items }] of byCat) {
  idx.push(`- **[${heading}](/docs/troubleshooting/${cat})** — ${items.length} ${items.length === 1 ? 'entry' : 'entries'}`)
}
writeFileSync(join(DOCS, 'troubleshooting.md'), idx.join('\n') + '\n')

// Sidebar nav fragment — a dedicated Troubleshooting tier.
const group = { text: 'Troubleshooting', tier: 'Troubleshooting', collapsed: true, items: navItems }
const navSrc = `// GENERATED by docs/scripts/gen-troubleshooting.ts — do not edit.
// Regenerate with \`bun docs/scripts/gen-troubleshooting.ts\`.
import type { SidebarGroup } from './sidebar-config'

export const TROUBLESHOOTING_GROUPS: SidebarGroup[] = ${JSON.stringify([group], null, 2)}
`
writeFileSync(NAV_FILE, navSrc)

console.warn(
  `[gen-troubleshooting] ${pageCount} category pages + index, ${entries.length} entries → docs/src/content/docs/troubleshooting/`,
)
