#!/usr/bin/env bun
/** Generate the homepage inventory and complete package catalog from public workspace manifests. */
import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { escFlow } from './_md-safe'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const packagesRoot = join(root, 'packages')
const groups = []
for (const category of readdirSync(packagesRoot).sort()) {
  const packages = []
  for (const entry of readdirSync(join(packagesRoot, category), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const path = `packages/${category}/${entry.name}`
    if (!existsSync(join(root, path, 'package.json'))) continue
    const pkg = await Bun.file(join(root, path, 'package.json')).json()
    if (pkg.private || !pkg.name.startsWith('@pyreon/')) continue
    const slug = pkg.name.slice('@pyreon/'.length)
    const guide = [
      `docs/src/content/docs/${slug}.md`,
      `docs/src/content/docs/guides/${slug}.md`,
    ].find((candidate) => existsSync(join(root, candidate)))
    const href = guide
      ? `/docs/${guide.replace('docs/src/content/docs/', '').replace(/\.md$/, '')}`
      : slug.startsWith('native-')
        ? '/docs/native-packages'
        : `https://github.com/pyreon/pyreon/tree/main/${path}`
    packages.push({ name: pkg.name as string, description: pkg.description ?? '', href })
  }
  packages.sort((a, b) => a.name.localeCompare(b.name, 'en'))
  if (packages.length) groups.push({ category, packages })
}
const total = groups.reduce((n, group) => n + group.packages.length, 0)
// The homepage needs names/counts only; keep guide descriptions and URLs out
// of its initial client bundle. The complete metadata lives in the Markdown.
const inventory = groups.map((group) => ({
  category: group.category,
  packages: group.packages.map((pkg) => pkg.name),
}))
const header = '// Generated by docs/scripts/gen-package-catalog.ts. Do not edit.\n'
writeFileSync(
  join(root, 'docs/src/package-catalog.generated.ts'),
  header +
    `export const PACKAGE_GROUPS = ${JSON.stringify(inventory, null, 2)} as const\n\n` +
    'export const PACKAGE_COUNT = PACKAGE_GROUPS.reduce((count, group) => count + group.packages.length, 0)\n',
)
const lines = [
  '---',
  'title: Package catalog',
  'description: Every public Pyreon workspace package, with links to its guide or source.',
  'generated_by: docs/scripts/gen-package-catalog.ts',
  '---',
  '',
  '# Package catalog',
  '',
  `${total} public workspace packages across ${groups.length} categories. This inventory describes the current source tree; see each package on npm for the published version.`,
  '',
  'Explore the [live examples](/docs/examples) and the [UI component workbench](/atlas/). The component library is a separate, private workspace and is not included in the public package count.',
  '',
]
for (const group of groups) {
  lines.push(
    `## ${group.category} (${group.packages.length})`,
    '',
    '| Package | Description |',
    '| --- | --- |',
  )
  for (const pkg of group.packages) {
    const description = escFlow(pkg.description)
      .replace(/\|/g, '\\|')
      .replace(/[\r\n]/g, ' ')
    lines.push(`| [${pkg.name}](${pkg.href}) | ${description} |`)
  }
  lines.push('')
}
writeFileSync(join(root, 'docs/src/content/docs/package-catalog.md'), lines.join('\n'))
console.warn(`[gen-package-catalog] ${total} packages across ${groups.length} categories`)
