#!/usr/bin/env bun
/**
 * CI guard: PRs touching SOURCE files in `packages/` PUBLISHED to npm must
 * either add a changeset (regular feature/fix PR) or consume one (the
 * Version PR generated by `changesets/action`).
 *
 * ## Why
 *
 * Every package change that consumers pay for in their `bun.lock` needs
 * a changelog trail. Adding `.changeset/<slug>.md` records the change;
 * the Version PR consumes those markdown files when it bumps versions.
 *
 * ## What counts as a "consumer-affecting change"
 *
 * **Only files under a published-to-npm package** — i.e. a package whose
 * `package.json` does NOT set `"private": true` AND is NOT listed in
 * `.changeset/config.json` `ignore`. The intent is "did a PR change
 * something that ships to npm consumers?"
 *
 * Specifically NOT consumer-affecting:
 *
 * - Changes to a PRIVATE package (`@pyreon/test-utils`, `@pyreon/manifest`,
 *   `@pyreon/perf-harness`, `@pyreon/vitest-config`, `@pyreon/playwright-config`,
 *   `@pyreon/devtools`, `@pyreon/ui-*`, every `@pyreon/native-*` workspace).
 *   These are repo-internal: tooling, demos, test infra. They don't ship.
 * - Changes to an `ignore`d package per `.changeset/config.json` —
 *   examples, the docs site, the AI-reference workspace. They're tagged
 *   along in the monorepo but not on the published-packages train.
 * - Files outside `packages/` entirely — `scripts/`, `docs/`, `.github/`,
 *   root config files. The shell version of this gate already filtered
 *   these correctly via `git diff -- 'packages/**'`.
 * - Test / spec / story files (`*.test.ts(x)`, `*.spec.ts(x)`,
 *   `*.stories.ts(x)`) and anything under a `tests/` / `__tests__/`
 *   directory, even inside a published package's `src/` — `publish.ts`
 *   strips `src/` from the tarball entirely, so test code never reaches
 *   consumers. Classified by the shared `scripts/test-paths.ts`
 *   (`isTestPath`), the SAME source of truth the `check-diagnose-catalog`
 *   gate uses — one definition, no drift.
 *
 * The label-bypass (`skip-changeset`) stays in place for the rare case
 * where a published-package source file changed but the change is
 * legitimately catalog-irrelevant (e.g. a comment-only edit, a
 * type-tightening that doesn't change the runtime contract).
 *
 * ## History
 *
 * The pre-fix gate was inline shell in `.github/workflows/changeset-check.yml`
 * checking `git diff -- 'packages/**'`. That fired on ANY change anywhere
 * under `packages/`, including private internal packages — every PR that
 * touched `@pyreon/test-utils` tests, `@pyreon/perf-harness` instrumentation,
 * or a private demo got blocked + needed manual `skip-changeset` labeling.
 * The label dance was a workaround; the detector was wrong.
 *
 * The structural fix mirrors `scripts/check-diagnose-catalog.ts` (PR #1167):
 * extract the policy as pure functions, route the workflow through the
 * script, add unit tests covering every branch.
 *
 * ## Mechanics
 *
 * 1. Get changed-file list via `git diff origin/${BASE_REF}...HEAD`.
 * 2. Filter to files under a workspace that's PUBLISHED (not private,
 *    not in changeset `ignore` list). If none → exit 0.
 * 3. If `HAS_SKIP_LABEL=true` → exit 0 (deliberate bypass).
 * 4. Count changeset activity: added OR deleted `.changeset/*.md` files
 *    (excluding `README.md` / `config.json`). Deletion satisfies the gate
 *    for the changesets-action Version PR, which consumes markdown files
 *    to produce CHANGELOGs.
 * 5. If changeset activity present → exit 0.
 * 6. Otherwise → exit 1 with actionable guidance.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { isTestPath } from './test-paths'

// ─── Pure exports (testable) ────────────────────────────────────────────────

export interface PackageInfo {
  name: string
  /** Absolute path to the package directory. */
  dir: string
  private: boolean
}

/**
 * Workspace discovery: walks `packages/`, `examples/`, and `docs/` for
 * `package.json` files and returns one entry per workspace with its
 * `name` + `private` field. Same shape as `scripts/affected.ts`'s
 * `discoverWorkspaces` but minus the dep-graph fields (this gate doesn't
 * need them). Templates under `create-zero/templates/` are excluded —
 * those are scaffold output, not real workspaces.
 */
export function discoverPackages(root: string): PackageInfo[] {
  const out: PackageInfo[] = []

  const packagesRoot = join(root, 'packages')
  if (existsSync(packagesRoot)) {
    for (const category of readdirSync(packagesRoot)) {
      const categoryPath = join(packagesRoot, category)
      if (!safeIsDir(categoryPath)) continue
      for (const pkg of readdirSync(categoryPath)) {
        const pkgPath = join(categoryPath, pkg)
        const pkgJson = join(pkgPath, 'package.json')
        if (!existsSync(pkgJson)) continue
        const info = readPackageInfo(pkgJson, pkgPath)
        if (info) out.push(info)
      }
    }
  }

  const examplesRoot = join(root, 'examples')
  if (existsSync(examplesRoot)) {
    for (const ex of readdirSync(examplesRoot)) {
      const exPath = join(examplesRoot, ex)
      const pkgJson = join(exPath, 'package.json')
      if (!existsSync(pkgJson)) continue
      const info = readPackageInfo(pkgJson, exPath)
      if (info) out.push(info)
    }
  }

  const docsPkg = join(root, 'docs', 'package.json')
  if (existsSync(docsPkg)) {
    const info = readPackageInfo(docsPkg, join(root, 'docs'))
    if (info) out.push(info)
  }

  return out
}

function readPackageInfo(pkgJsonPath: string, pkgDir: string): PackageInfo | null {
  try {
    const json = JSON.parse(readFileSync(pkgJsonPath, 'utf-8')) as {
      name?: string
      private?: boolean
    }
    if (!json.name) return null
    return {
      name: json.name,
      dir: pkgDir,
      private: json.private === true,
    }
  } catch {
    return null
  }
}

function safeIsDir(p: string): boolean {
  try {
    return statSync(p).isDirectory()
  } catch {
    return false
  }
}

/**
 * Read the `ignore` array from `.changeset/config.json`. Returns an
 * empty array if the file is missing or malformed — the gate continues
 * conservatively (no packages are auto-ignored).
 */
export function readChangesetIgnore(root: string): string[] {
  const configPath = join(root, '.changeset', 'config.json')
  if (!existsSync(configPath)) return []
  try {
    const json = JSON.parse(readFileSync(configPath, 'utf-8')) as {
      ignore?: string[]
    }
    return json.ignore ?? []
  } catch {
    return []
  }
}

/**
 * Find the owning workspace for a relative repo file path. Returns
 * `null` when the file is outside any workspace (`scripts/`, `docs/`,
 * `.github/`, root config files). Matching is by longest path prefix —
 * a file under `packages/core/router/src/router.ts` belongs to
 * `@pyreon/router`, not its parent `packages/core/`.
 *
 * `repoRoot` is the absolute repo root; `file` is the repo-relative
 * path that came from `git diff --name-only`.
 */
export function findOwningPackage(
  file: string,
  packages: PackageInfo[],
  repoRoot: string,
): PackageInfo | null {
  const abs = resolve(repoRoot, file)
  let best: PackageInfo | null = null
  let bestLen = -1
  for (const pkg of packages) {
    const dirWithSep = pkg.dir.endsWith('/') ? pkg.dir : `${pkg.dir}/`
    if (abs.startsWith(dirWithSep) && pkg.dir.length > bestLen) {
      best = pkg
      bestLen = pkg.dir.length
    }
  }
  return best
}

/**
 * Whether a single changed file represents a "consumer-affecting"
 * change — one that ships to npm consumers and so needs a changeset.
 *
 * Pure function: takes pre-discovered package metadata + the changeset
 * ignore list so unit tests can drive the policy without filesystem
 * mocks.
 *
 * Rules:
 * - File must map to an owning workspace (otherwise: not packages/,
 *   gate not applicable).
 * - Workspace must NOT be `"private": true`.
 * - Workspace name must NOT appear in `.changeset/config.json` `ignore`.
 * - File must NOT be test code (`isTestPath`) — test files never reach
 *   consumers (`scripts/publish.ts` strips `src/` from the tarball, so
 *   tests aren't even shipped), parity with the diagnose-catalog gate.
 *   Both gates share ONE classifier (`scripts/test-paths.ts`).
 */
export function isConsumerAffectingFile(
  file: string,
  packages: PackageInfo[],
  ignoredNames: Set<string>,
  repoRoot: string,
): boolean {
  const owner = findOwningPackage(file, packages, repoRoot)
  if (!owner) return false
  if (owner.private) return false
  if (ignoredNames.has(owner.name)) return false
  if (isTestPath(file)) return false
  return true
}

/**
 * Return the human-readable list of consumer-affecting packages
 * touched (one entry per package whose published source actually
 * changed). Used in the log line so failure messages name what
 * triggered the gate.
 */
export function consumerPackagesTouched(
  files: string[],
  packages: PackageInfo[],
  ignoredNames: Set<string>,
  repoRoot: string,
): string[] {
  const hits = new Set<string>()
  for (const file of files) {
    const owner = findOwningPackage(file, packages, repoRoot)
    if (!owner) continue
    if (owner.private) continue
    if (ignoredNames.has(owner.name)) continue
    hits.add(owner.name)
  }
  return [...hits].sort()
}

/**
 * Whether a changed `.changeset/*` file satisfies the gate. README +
 * config.json don't count — they're infrastructure, not changesets.
 */
export function isChangesetFile(file: string): boolean {
  if (!file.startsWith('.changeset/')) return false
  if (!file.endsWith('.md')) return false
  if (file === '.changeset/README.md') return false
  return true
}

/**
 * Pure policy evaluator. All side-effecting reads (git, env,
 * filesystem) happen in `main()`; the result is computed here from
 * plain data so unit tests can drive every branch directly.
 */
export type GateResult =
  | { kind: 'skip-no-consumer-files' }
  | { kind: 'skip-label' }
  | { kind: 'ok-changeset-activity'; activity: string[] }
  | { kind: 'fail-no-changeset'; touched: string[] }

export interface GateInputs {
  files: string[]
  packages: PackageInfo[]
  ignoredNames: Set<string>
  repoRoot: string
  hasSkipLabel: boolean
}

export function evaluateGate(inp: GateInputs): GateResult {
  const consumerFiles = inp.files.filter((f) =>
    isConsumerAffectingFile(f, inp.packages, inp.ignoredNames, inp.repoRoot),
  )

  if (consumerFiles.length === 0) {
    return { kind: 'skip-no-consumer-files' }
  }

  if (inp.hasSkipLabel) {
    return { kind: 'skip-label' }
  }

  const activity = inp.files.filter(isChangesetFile)
  if (activity.length > 0) {
    return { kind: 'ok-changeset-activity', activity }
  }

  return {
    kind: 'fail-no-changeset',
    touched: consumerPackagesTouched(
      inp.files,
      inp.packages,
      inp.ignoredNames,
      inp.repoRoot,
    ),
  }
}

// ─── Side-effecting helpers ─────────────────────────────────────────────────

/**
 * `git diff` / `git show` runner. Uses `execFileSync` (no shell
 * parsing) with discrete argv so even an unexpected character in a
 * sanitized value can't be interpreted as a shell metacharacter —
 * defense in depth on top of the BASE_REF allowlist.
 */
function git(...args: string[]): string {
  return execFileSync('git', args, { encoding: 'utf8' }).trim()
}

function changedFiles(baseRef: string): string[] {
  // `git diff --name-only` requires the merge-base form
  // `<base>...HEAD` to compare only commits unique to HEAD, not the
  // union of both branches' changes since divergence. Use the
  // diff-filter that catches additions AND deletions (changeset files
  // are deleted when the Version PR consumes them).
  try {
    const out = git('diff', '--name-only', '--diff-filter=ACDMRTUXB', `origin/${baseRef}...HEAD`)
    return out.length === 0 ? [] : out.split('\n')
  } catch {
    return []
  }
}

// ─── Main runner ────────────────────────────────────────────────────────────

const REF_ALLOWLIST = /^[a-zA-Z0-9._/-]+$/

function main(): void {
  const RAW_BASE_REF = process.env['BASE_REF'] || 'main'
  if (!REF_ALLOWLIST.test(RAW_BASE_REF)) {
    console.error(
      `[check-changeset-required] FAILED — BASE_REF "${RAW_BASE_REF}" contains characters outside the allowed set [a-zA-Z0-9._/-]. Refusing to use it.`,
    )
    process.exit(1)
  }
  const BASE_REF = RAW_BASE_REF
  const HAS_SKIP_LABEL = process.env['HAS_SKIP_LABEL'] === 'true'

  const repoRoot = resolve(import.meta.dirname, '..')
  const files = changedFiles(BASE_REF)
  const packages = discoverPackages(repoRoot)
  const ignoredNames = new Set(readChangesetIgnore(repoRoot))

  const result = evaluateGate({
    files,
    packages,
    ignoredNames,
    repoRoot,
    hasSkipLabel: HAS_SKIP_LABEL,
  })

  switch (result.kind) {
    case 'skip-no-consumer-files':
      console.log(
        '[check-changeset-required] PR does not touch any published package source — changeset not required.',
      )
      process.exit(0)
      break

    case 'skip-label':
      console.log(
        '[check-changeset-required] skip-changeset label present — bypassing the gate.',
      )
      process.exit(0)
      break

    case 'ok-changeset-activity':
      console.log(
        `[check-changeset-required] OK — changeset activity found: ${result.activity.join(', ')}`,
      )
      process.exit(0)
      break

    case 'fail-no-changeset':
      console.error(
        `[check-changeset-required] FAILED — PR changes published-package source (${result.touched.join(', ')}) but no changeset is added or consumed.`,
      )
      console.error('')
      console.error('Add one with:')
      console.error('  bun changeset')
      console.error("  git add .changeset && git commit -m 'add changeset' && git push")
      console.error('')
      console.error(
        'Or, if this PR genuinely does not ship to consumers (comment-only edit, type-tightening',
      )
      console.error(
        "with no runtime impact, etc.), add the 'skip-changeset' label to bypass.",
      )
      process.exit(1)
      break
  }
}

// Only run main() when invoked as a script — `import {} from './check-changeset-required'`
// from a test doesn't trigger the runner.
const isScriptInvocation =
  typeof process.argv[1] === 'string' &&
  process.argv[1].endsWith('check-changeset-required.ts')

if (isScriptInvocation) {
  main()
}
