import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { buildChartHostHtml } from '../packages/fundamentals/charts/src/webview'

const output = resolve(
  import.meta.dir,
  '../packages/native/compiler/src/generated-chart-webview-host.ts',
)
const source =
  `// Generated by scripts/gen-chart-webview-host.ts. Do not edit by hand.\n` +
  `// The native compiler embeds the same default host as @pyreon/charts/webview.\n` +
  `export const DEFAULT_CHART_WEBVIEW_HOST_HTML = ${JSON.stringify(buildChartHostHtml())}\n`

writeFileSync(output, source)
console.log(`[gen-chart-webview-host] wrote ${output}`)
