import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { buildFlowHostHtml } from '../packages/fundamentals/flow/src/webview'

const output = resolve(
  import.meta.dir,
  '../packages/fundamentals/flow/src/native-plugin/webview-host.generated.ts',
)
const source =
  `// Generated by scripts/gen-flow-webview-host.ts. Do not edit by hand.\n` +
  `// The flow native plugin embeds the same dependency-free host as @pyreon/flow/webview.\n` +
  `export const DEFAULT_FLOW_WEBVIEW_HOST_HTML = ${JSON.stringify(buildFlowHostHtml())}\n`

writeFileSync(output, source)
console.log(`[gen-flow-webview-host] wrote ${output}`)
