#!/usr/bin/env bun
/**
 * Generates the native compiler's built-in copy of every library-owned plugin.
 *
 * The SOURCE OF TRUTH for `@pyreon/hooks`' native lowering is
 * `packages/fundamentals/hooks/src/native-plugin.ts` — the library owns what
 * its hooks lower to. `@pyreon/native-compiler` must still lower them with no
 * library installed (a zero-config `transform()`), and must not depend on the
 * library to do it, so the compiler keeps a GENERATED copy:
 * `packages/native/compiler/src/built-in-services.generated.ts`. The same
 * pattern as the generated web-only package list.
 *
 * An app whose installed `@pyreon/hooks` is newer than the compiler has the
 * library's plugin discovered from `pyreon.native.plugin` and it replaces the
 * built-in of the same name; the copy is only the fallback.
 *
 * Declaration order is preserved, NOT sorted: the registry order is the order
 * the Swift lifecycle modifiers emit in. Output is otherwise deterministic
 * (the plugin's own key order, no timestamps).
 *
 * Usage:
 *   bun scripts/gen-native-builtin-plugins.ts           # write
 *   bun scripts/gen-native-builtin-plugins.ts --check   # exit 1 when stale
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import hooksPlugin from '../packages/fundamentals/hooks/src/native-plugin'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(SCRIPT_DIR, '..')
export const GENERATED_PATH = join(
  REPO_ROOT,
  'packages/native/compiler/src/built-in-services.generated.ts',
)
const SOURCE_PATH = 'packages/fundamentals/hooks/src/native-plugin.ts'

function quote(value: string): string {
  // The data is plain identifiers, Swift/Kotlin source lines and member names;
  // a control character would mean an escape this renderer does not model.
  // oxlint-disable-next-line no-control-regex
  if (/[\u0000-\u001f]/.test(value)) {
    throw new Error(
      `[gen-native-builtin-plugins] control character in plugin string ${JSON.stringify(value)}`,
    )
  }
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/** Inline TS literal for plain data: strings, booleans, numbers, arrays, objects. */
export function renderValue(value: unknown): string {
  if (typeof value === 'string') return quote(value)
  if (typeof value === 'boolean' || typeof value === 'number') return String(value)
  if (Array.isArray(value)) return `[${value.map(renderValue).join(', ')}]`
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value)
    if (entries.length === 0) return '{}'
    return `{ ${entries.map(([k, v]) => `${IDENT.test(k) ? k : quote(k)}: ${renderValue(v)}`).join(', ')} }`
  }
  throw new Error(
    `[gen-native-builtin-plugins] cannot render ${String(value)} — plugin service data must be plain`,
  )
}

interface ServiceLike {
  readonly [key: string]: unknown
}

export function render(plugin: {
  readonly name: string
  readonly modules?: readonly string[] | undefined
  readonly services?: Readonly<Record<string, ServiceLike>> | undefined
}): string {
  const lines: string[] = [
    `// GENERATED by scripts/gen-native-builtin-plugins.ts — do not edit by hand.`,
    `// Source of truth: ${SOURCE_PATH} (the library owns its lowering).`,
    `// Regenerate: bun scripts/gen-native-builtin-plugins.ts   Verify: --check (validate-fast).`,
    `// Declaration order is meaningful (Swift lifecycle modifiers emit in registry order).`,
    `import type { ServiceSpec } from './plugin'`,
    ``,
    `export const HOOKS_PLUGIN_NAME = ${quote(plugin.name)}`,
    ``,
    `export const HOOKS_PLUGIN_MODULES: readonly string[] = ${renderValue([...(plugin.modules ?? [])])}`,
    ``,
    `export const HOOKS_SERVICES: Readonly<Record<string, ServiceSpec>> = {`,
  ]
  for (const [hook, spec] of Object.entries(plugin.services ?? {})) {
    lines.push(`  ${hook}: {`)
    for (const [key, value] of Object.entries(spec))
      lines.push(`    ${key}: ${renderValue(value)},`)
    lines.push(`  },`)
  }
  lines.push(`}`, ``)
  return lines.join('\n')
}

if (import.meta.main) {
  const next = render(hooksPlugin)
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(GENERATED_PATH, 'utf8')
    } catch {
      // A missing file is stale by definition.
    }
    if (current !== next) {
      console.error(
        `✗ ${relative(REPO_ROOT, GENERATED_PATH)} is stale against ${SOURCE_PATH}.\n` +
          `  Regenerate: bun scripts/gen-native-builtin-plugins.ts`,
      )
      process.exit(1)
    }
    console.log(`✓ ${relative(REPO_ROOT, GENERATED_PATH)} is up to date`)
  } else {
    writeFileSync(GENERATED_PATH, next)
    console.log(`[gen-native-builtin-plugins] wrote ${relative(REPO_ROOT, GENERATED_PATH)}`)
  }
}
