#!/usr/bin/env bun
/**
 * Minimal directory-rewriting static server for SSG e2e gates.
 *
 * **Why this exists**: `vite preview` does SPA fallback — for ANY URL
 * that doesn't map to a literal file in `dist/`, it serves
 * `dist/index.html`. That's correct for SPA builds, but breaks SSG e2e
 * gates: a request to `/cs/posts` should serve `dist/cs/posts/index.html`,
 * NOT `dist/index.html`.
 *
 * Real static hosts (Netlify, Cloudflare Pages, GitHub Pages, S3 +
 * CloudFront, nginx + try_files) do this directory rewriting natively.
 * `vite preview` does not — so e2e tests against `vite preview` were
 * silently testing client-side routing on top of an SPA shell rather
 * than the real SSG-served behaviour.
 *
 * The bug shape this revealed: in PR #516's ssg-i18n e2e, spec (c)
 * documented `useLoaderData() === undefined` post-hydration on
 * `/cs/posts` as a "known gap, framework bug." Investigation in this PR
 * proved the framework was correct all along: the inline
 * `<script>window.__PYREON_LOADER_DATA__=…</script>` was missing from
 * the served HTML because `vite preview` returned `dist/index.html`
 * (which has NO loader data — it's the home page) instead of
 * `dist/cs/posts/index.html` (which DOES carry the dehydrated data
 * keyed correctly by `/cs/posts`).
 *
 * **Behaviour:**
 * - `_redirects` rule match → 301/302/etc. with `Location` header
 *   (Netlify/Cloudflare format, see `loadRedirects` below)
 * - URL ends with `/` → serve `<dir>/index.html`
 * - URL has no extension → treat as directory: `/foo/bar` →
 *   `<dir>/foo/bar/index.html`
 * - URL has an extension → serve the literal file
 * - Missing file → serve `404.html` with status 404 if it exists, else
 *   plain text
 *
 * Path-traversal guard: resolved file must start with the root dir.
 *
 * **Why not `vite preview --rewrite`**: no such flag exists. Vite
 * preview's SPA-fallback behaviour is hardcoded. Patches landing it
 * upstream would take months; a 80-line static server is the
 * pragmatic shape.
 *
 * **Why not `serve` (npm package)**: introduces an external dep just
 * for e2e infra. The lines below ship in the Pyreon monorepo as
 * `scripts/serve-ssg.ts` and serve via `bun scripts/serve-ssg.ts
 * <dist> <port>` — zero deps.
 *
 * @example
 *   bun scripts/serve-ssg.ts examples/ssr-showcase/dist 5199
 */

import { readFileSync, existsSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

// Minimal ambient declaration for `Bun.serve` — the script is a Bun
// bin entry but is also imported by `@pyreon/test-utils` for unit
// testing (no Bun globals needed there since the bin path is gated
// behind `import.meta.main`). The test-utils tsconfig doesn't include
// `@types/bun`; this local declaration keeps both consumers happy
// without forcing every downstream tsconfig to add the dep.
declare const Bun: {
  serve(options: { port: number; fetch: (req: Request) => Promise<Response> }): unknown
}

export type RedirectRule = { from: string; to: string; status: number }

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml',
}

export function getMime(path: string): string {
  const dotIdx = path.lastIndexOf('.')
  if (dotIdx < 0) return 'application/octet-stream'
  const ext = path.slice(dotIdx).toLowerCase()
  return MIME_TYPES[ext] ?? 'application/octet-stream'
}

/**
 * Parse Netlify / Cloudflare Pages `_redirects` format. One rule per
 * line, columns space-separated: `<from> <to> [status]`. Status
 * defaults to 301 if absent (covers hand-written manifests; Pyreon's
 * SSG plugin always emits an explicit status). Lines starting with
 * `#` are comments; blank lines are skipped.
 *
 * Source-of-truth for the emitted shape:
 * `packages/zero/zero/src/ssg-plugin.ts:renderNetlifyRedirects` — one
 * `# Auto-generated by @pyreon/zero SSG. Do not edit.` comment header
 * followed by rule lines.
 *
 * **Splat / param expansion (`/*`, `:slug`) is NOT supported** — the
 * SSG plugin only emits LITERAL `from` paths today (one entry per
 * loader-thrown `redirect()` source path). Add wildcard expansion when
 * redirect manifests start carrying patterns.
 */
export function parseRedirects(content: string): RedirectRule[] {
  const rules: RedirectRule[] = []
  for (const raw of content.split('\n')) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const cols = line.split(/\s+/)
    if (cols.length < 2) continue
    const status = cols[2] ? Number.parseInt(cols[2], 10) : 301
    if (!Number.isFinite(status) || status < 300 || status > 399) continue
    rules.push({ from: cols[0]!, to: cols[1]!, status })
  }
  return rules
}

/**
 * Load + parse `_redirects` from `<root>/_redirects`. Returns `[]` when
 * the file doesn't exist (no redirects configured — common case).
 */
export function loadRedirects(root: string): RedirectRule[] {
  const path = join(root, '_redirects')
  if (!existsSync(path)) return []
  try {
    return parseRedirects(readFileSync(path, 'utf-8'))
  } catch {
    return []
  }
}

/**
 * Match a pathname against redirect rules. First-match-wins (Netlify
 * semantics). Returns `null` when no rule applies.
 *
 * Trailing-slash handling: rules' `from` and the incoming pathname are
 * compared verbatim (same shape `ssg-plugin.ts` emits, same shape the
 * incoming URL carries). If a real consumer needs canonicalisation
 * (e.g. `/foo` ↔ `/foo/` equivalence), add it explicitly in the
 * matcher — silently normalising hides intent.
 */
export function matchRedirect(
  pathname: string,
  rules: readonly RedirectRule[],
): RedirectRule | null {
  for (const rule of rules) {
    if (rule.from === pathname) return rule
  }
  return null
}

/**
 * Build the fetch handler. Exported so unit tests can construct a
 * handler against a synthetic root + rule set without spinning up a
 * real `Bun.serve`.
 */
export function createServeHandler(
  root: string,
  redirects: readonly RedirectRule[],
): (req: Request) => Promise<Response> {
  return async function fetch(req: Request): Promise<Response> {
    const url = new URL(req.url)
    let pathname = url.pathname

    // Redirects fire BEFORE directory rewriting — mirrors real static
    // hosts (Netlify / Cloudflare apply `_redirects` before serving
    // any file).
    const hit = matchRedirect(pathname, redirects)
    if (hit) {
      return new Response(null, {
        status: hit.status,
        headers: { Location: hit.to },
      })
    }

    // Directory rewriting: paths without an extension (and not literal
    // file paths) become `<path>/index.html`. Static hosts do this
    // automatically — we mirror the behaviour so e2e gates against
    // `bun scripts/serve-ssg.ts` reflect production deployment shape.
    const hasExt = /\.[a-z0-9]+$/i.test(pathname)
    if (!hasExt) {
      if (!pathname.endsWith('/')) pathname = `${pathname}/`
      pathname = `${pathname}index.html`
    }

    // Resolve + path-traversal guard.
    const filePath = join(root, pathname)
    const resolved = resolve(filePath)
    if (!resolved.startsWith(root)) {
      return new Response('Forbidden', { status: 403 })
    }

    if (existsSync(resolved) && statSync(resolved).isFile()) {
      return new Response(readFileSync(resolved), {
        headers: { 'content-type': getMime(resolved) },
      })
    }

    // 404 fallback. Static hosts serve `404.html` for unmatched URLs;
    // mirror that so e2e tests for missing routes see the right output.
    const fourOhFour = join(root, '404.html')
    if (existsSync(fourOhFour)) {
      return new Response(readFileSync(fourOhFour), {
        status: 404,
        headers: { 'content-type': 'text/html; charset=utf-8' },
      })
    }
    return new Response('Not Found', { status: 404 })
  }
}

// Bin entry — only runs when invoked as `bun scripts/serve-ssg.ts <dist> <port>`.
// Importing this module from tests does NOT trigger the server boot.
if (import.meta.main) {
  const DIST_ARG = process.argv[2]
  const PORT_ARG = process.argv[3]

  if (!DIST_ARG || !PORT_ARG) {
    console.error('Usage: bun scripts/serve-ssg.ts <dist-dir> <port>')
    process.exit(1)
  }

  const root = resolve(DIST_ARG)
  const port = Number(PORT_ARG)

  if (!Number.isInteger(port) || port <= 0 || port > 65535) {
    console.error(`[serve-ssg] Invalid port: ${PORT_ARG}`)
    process.exit(1)
  }

  if (!existsSync(root)) {
    console.error(`[serve-ssg] Dist directory does not exist: ${root}`)
    process.exit(1)
  }

  const redirects = loadRedirects(root)
  if (redirects.length > 0) {
    console.log(`[serve-ssg] Loaded ${redirects.length} redirect rule(s)`)
  }

  Bun.serve({ port, fetch: createServeHandler(root, redirects) })

  console.log(`[serve-ssg] Serving ${root} at http://localhost:${port}`)
}
