/**
 * Behaviour recorded from `cac@7.0.0` BEFORE it was replaced by `../argv.ts`.
 *
 * Generated by driving the real cac with the exact command table `zero`
 * declared (recording actions, captured `console.info`) over the argv matrix
 * below. It is the characterization baseline: every row is what cac did, so a
 * divergence in the replacement is a behaviour change, not a style choice.
 * Do not regenerate it from `argv.ts` — that would make the test compare the
 * implementation with itself.
 */

export const RUNS: Array<[string[], string, unknown[]]> = [
  [[], "dev", [undefined, {"--": []}]],
  [["dev"], "dev", [undefined, {"--": []}]],
  [["./app"], "dev", ["./app", {"--": []}]],
  [["dev", "./app"], "dev", ["./app", {"--": []}]],
  [["build"], "build", [undefined, {"--": []}]],
  [["build", "x"], "build", ["x", {"--": []}]],
  [["--port", "3000"], "dev", [undefined, {"--": [], "port": 3000}]],
  [["--port=4000"], "dev", [undefined, {"--": [], "port": 4000}]],
  [["dev", "--port", "3000", "--host"], "dev", [undefined, {"--": [], "port": 3000, "host": true}]],
  [["--host", "0.0.0.0"], "dev", [undefined, {"--": [], "host": "0.0.0.0"}]],
  [["--host", "127"], "dev", [undefined, {"--": [], "host": 127}]],
  [["--open"], "dev", [undefined, {"--": [], "open": true}]],
  [["--open", "false"], "dev", [undefined, {"--": [], "open": false}]],
  [["--open", "true"], "dev", [undefined, {"--": [], "open": true}]],
  [["--open", "x"], "dev", ["x", {"--": [], "open": true}]],
  [["--open", "12"], "dev", [12, {"--": [], "open": true}]],
  [["--no-open"], "dev", [undefined, {"--": [], "open": false}]],
  [["--routes"], "dev", [undefined, {"--": [], "routes": true}]],
  [["preview", "--port", "5000", "--host"], "preview", [undefined, {"--": [], "port": 5000, "host": true}]],
  [["preview", "./dist", "--host", "h"], "preview", ["./dist", {"--": [], "host": "h"}]],
  [["doctor", "--fix", "--json", "--ci", "--full"], "doctor", [undefined, {"--": [], "fix": true, "json": true, "ci": true, "full": true}]],
  [["doctor", "x", "--fix"], "doctor", ["x", {"--": [], "fix": true}]],
  [["context", "--out", "a.json"], "context", [undefined, {"--": [], "out": "a.json"}]],
  [["context", "--out=p"], "context", [undefined, {"--": [], "out": "p"}]],
  [["context", "--out", "123"], "context", [undefined, {"--": [], "out": 123}]],
  [["create", "my-app", "--template", "x", "--yes"], "create", [["my-app"], {"--": [], "template": "x", "yes": true}]],
  [["create"], "create", [[], {"--": []}]],
  [["create", "a", "b", "-y", "--no-git"], "create", [["a", "b"], {"--": [], "y": true, "git": false}]],
  [["build", "--version"], "build", [undefined, {"--": [], "version": true, "v": true}]],
  [["dev", "--version"], "dev", [undefined, {"--": [], "version": true, "v": true}]],
  [["biuld"], "dev", ["biuld", {"--": []}]],
  [["--", "x"], "dev", [undefined, {"--": ["x"]}]],
  [["build", "--", "--x"], "build", [undefined, {"--": ["--x"]}]],
  [["--port", "3000", "--port", "4000"], "dev", [undefined, {"--": [], "port": [3000, 4000]}]],
  [["--port", "abc"], "dev", [undefined, {"--": [], "port": "abc"}]],
  [["--host="], "dev", [undefined, {"--": [], "host": true}]],
  [["--port", ""], "dev", [undefined, {"--": [], "port": 0}]],
  [["--host", "--open"], "dev", [undefined, {"--": [], "host": true, "open": true}]],
  [["-"], "dev", [undefined, {"--": []}]],
  [["dev", "build"], "dev", ["build", {"--": []}]],
  [["build", "dev"], "build", ["dev", {"--": []}]],
  [["doctor", "--no-fix"], "doctor", [undefined, {"--": [], "fix": false}]],
  [["--open=false"], "dev", [undefined, {"--": [], "open": false}]],
  [["--open=yes"], "dev", ["yes", {"--": [], "open": true}]],
  [["--host", "false"], "dev", [undefined, {"--": [], "host": "false"}]],
  [["doctor", "--fix", "a"], "doctor", ["a", {"--": [], "fix": true}]],
]

export const ERRORS: Array<[string[], string]> = [
  [["build", "x", "y"], "Unused args: `y`"],
  [["a", "b"], "Unused args: `b`"],
  [["--port"], "option `--port <port>` value is missing"],
  [["--port", "--open"], "option `--port <port>` value is missing"],
  [["--typo"], "Unknown option `--typo`"],
  [["--dry-run"], "Unknown option `--dryRun`"],
  [["-p", "3000"], "Unknown option `-p`"],
  [["build", "--port", "3000"], "Unknown option `--port`"],
  [["doctor", "--dry-run"], "Unknown option `--dryRun`"],
  [["context", "--out"], "option `--out <path>` value is missing"],
  [["-abc"], "Unknown option `-a`"],
  [["--port", "-1"], "Unknown option `-1`"],
  [["--port="], "option `--port <port>` value is missing"],
  [["---port", "1"], "Unknown option `-p`"],
  [["--Port", "1"], "Unknown option `--Port`"],
]

// Help text, byte-for-byte as cac printed it minus each line's trailing space.
export const HELP: Array<[string[][], string]> = [
  [[["--help"], ["-h"], ["dev", "--help"]], "zero/9.9.9\n\nUsage:\n  $ zero [root]\n\nCommands:\n  [root]            Start dev server\n  build [root]      Build for production (one Vite build — the zero plugin owns the pipeline)\n  preview [root]    Preview production build\n  doctor [root]     Check for React patterns and framework issues\n  context [root]    Generate project context for AI tools\n  create [...args]  Scaffold a new Pyreon Zero project (runs @pyreon/create-zero)\n\nFor more info, run any command with the `--help` flag:\n  $ zero --help\n  $ zero build --help\n  $ zero preview --help\n  $ zero doctor --help\n  $ zero context --help\n  $ zero create --help\n\nOptions:\n  --port <port>  Server port (default: 3000)\n  --host [host]  Server host\n  --open         Open browser on start\n  --routes       Print the full route table (collapsed to a one-line summary by default)\n  -h, --help     Display this message\n  -v, --version  Display version number"],
  [[["build", "--help"]], "zero/9.9.9\n\nUsage:\n  $ zero build [root]\n\nOptions:\n  -h, --help  Display this message"],
  [[["doctor", "-h"]], "zero/9.9.9\n\nUsage:\n  $ zero doctor [root]\n\nOptions:\n  --fix       Auto-fix fixable issues\n  --json      Output as JSON\n  --ci        CI mode — exit with code 1 on errors\n  --full      Run slow gates (audit-types, bundle-budgets)\n  -h, --help  Display this message"],
  [[["create", "--help"]], "zero/9.9.9\n\nUsage:\n  $ zero create [...args]\n\nOptions:\n  -h, --help  Display this message"],
  [[["preview", "--help"]], "zero/9.9.9\n\nUsage:\n  $ zero preview [root]\n\nOptions:\n  --port <port>  Server port (default: 3000)\n  --host [host]  Server host\n  -h, --help     Display this message"],
  [[["context", "--help"]], "zero/9.9.9\n\nUsage:\n  $ zero context [root]\n\nOptions:\n  --out <path>  Output path (default: .pyreon/context.json)\n  -h, --help    Display this message"],
]

export const VERSION_ARGV: string[][] = [["--version"], ["-v"]]

// cac printed the default help AND the version line for this argv, in that
// order (help does not short-circuit the version check).
export const HELP_AND_VERSION_ARGV: string[] = ["-v", "--help"]
