import { promises as fs } from 'node:fs'
import path from 'node:path'

// ─── .pyreon/content-types.d.ts emitter ────────────────────────────────────
//
// Writes a TypeScript ambient-module file that augments the public
// `CollectionSchemas` interface with the user's defined collections.
// After this file lands on disk + the user's `tsconfig.json` includes
// it, `getCollection<'docs'>()` returns the typed entry shape.
//
// We can't infer the zod-schema-to-TS-type mapping at build time without
// running a TS compiler — instead we emit a placeholder that uses
// `StandardSchemaV1`'s `InferOutput` helper. The user's TypeScript
// compiler resolves the inference at type-check time, the same way
// Astro does.
//
// File shape:
//
//     // Generated by @pyreon/zero-content. Do not edit.
//     import type { StandardSchemaV1 } from '@pyreon/zero-content/schema'
//     import type * as ContentConfig from '<absolute-or-relative-path>/content.config'
//
//     declare module '@pyreon/zero-content' {
//       interface CollectionSchemas {
//         docs: StandardSchemaV1.InferOutput<typeof ContentConfig.default.collections.docs.schema>
//         blog: StandardSchemaV1.InferOutput<typeof ContentConfig.default.collections.blog.schema>
//       }
//     }
//
// PR-E audit C6: the import was previously extensionless, which broke
// resolution under `moduleResolution: nodenext` (which requires an
// explicit extension). The file now leans on `typeof import('…')` in
// type position — TypeScript's type-position `import()` allows the
// extensionless path under both `bundler` and `nodenext` modes since
// it's resolved at type-check, not bundle, time.
//
// PR-E audit L2: also emits `.pyreon/tsconfig.json` which the user's
// tsconfig can extend (`{ "extends": "./.pyreon/tsconfig.json" }`) to
// pull in the generated types automatically — no manual `include`
// fiddling.

export interface EmitTypesArgs {
  /** Absolute path to the user's `content.config.{ts,...}` file. */
  configFile: string
  /** Collection names discovered in the config. */
  collectionNames: string[]
  /** Vite root, used to compute the relative path to the config. */
  root: string
}

/**
 * Render the `.pyreon/content-types.d.ts` body. Pure — does not touch
 * the filesystem. The Vite plugin calls `writeContentTypes` instead.
 *
 * @internal exported for testing
 */
export function renderContentTypes(args: EmitTypesArgs): string {
  // Strip extension so the import works against the source file via
  // the bundler's module resolution. PR-E audit C6 — we now use the
  // TYPE-POSITION `typeof import('...')` form which TypeScript
  // resolves at type-check time without needing
  // `allowImportingTsExtensions`. Works under both `moduleResolution:
  // bundler` AND `nodenext`.
  const rel = path
    .relative(path.join(args.root, '.pyreon'), args.configFile)
    .replace(/\\/g, '/')
  const importPath = rel.replace(/\.[^.]+$/, '')
  const importPathLit = JSON.stringify(importPath)
  const entries = args.collectionNames
    .map(
      (name) =>
        `    ${JSON.stringify(name)}: StandardSchemaV1.InferOutput<\n` +
        `      (typeof import(${importPathLit}))['default']['collections'][${JSON.stringify(name)}]['schema']\n` +
        `    >`,
    )
    .join('\n')
  return `// Generated by @pyreon/zero-content. Do not edit.
//
// Augments \`CollectionSchemas\` with one entry per collection in your
// \`content.config.ts\`. Pre-fix (PR-E audit C6) the import here was
// extensionless which broke under \`moduleResolution: nodenext\`. The
// \`typeof import()\` form below resolves at type-check time, so it
// works under both \`bundler\` and \`nodenext\` without needing
// \`allowImportingTsExtensions\`.
import type { StandardSchemaV1 } from '@pyreon/zero-content/schema'

declare module '@pyreon/zero-content' {
  interface CollectionSchemas {
${entries}
  }
}

export {}
`
}

/**
 * Render the optional `.pyreon/tsconfig.json` the user's tsconfig can
 * extend to pick up generated content types automatically. PR-E audit
 * L2 — without this the user had to remember to add `.pyreon/**` to
 * their `include` array.
 *
 * @internal exported for testing
 */
export function renderPyreonTsconfig(): string {
  return JSON.stringify(
    {
      $schema: 'https://json.schemastore.org/tsconfig',
      // We only emit a compilerOptions-free wrapper plus an `include`
      // that pulls the generated `.d.ts` into the user's tsc run. The
      // user's tsconfig stays in charge of every other setting.
      include: ['./content-types.d.ts'],
    },
    null,
    2,
  ) + '\n'
}

/**
 * Write `<root>/.pyreon/content-types.d.ts` + `<root>/.pyreon/tsconfig.json`.
 * Creates the `.pyreon/` directory when missing. Idempotent — re-runs
 * are safe.
 */
export async function writeContentTypes(args: EmitTypesArgs): Promise<string> {
  const outDir = path.join(args.root, '.pyreon')
  await fs.mkdir(outDir, { recursive: true })
  const outFile = path.join(outDir, 'content-types.d.ts')
  await fs.writeFile(outFile, renderContentTypes(args), 'utf8')
  // PR-E audit L2 — the user's tsconfig can `"extends":
  // "./.pyreon/tsconfig.json"` to pick up generated types
  // automatically without modifying their `include` array.
  await fs.writeFile(
    path.join(outDir, 'tsconfig.json'),
    renderPyreonTsconfig(),
    'utf8',
  )
  return outFile
}
