import { promises as fs } from 'node:fs'
import path from 'node:path'

// ─── .pyreon/content-types.d.ts emitter ────────────────────────────────────
//
// Writes a TypeScript ambient-module file that augments the public
// `CollectionSchemas` interface with the user's defined collections.
// After this file lands on disk + the user's `tsconfig.json` includes
// it, `getCollection<'docs'>()` returns the typed entry shape.
//
// We can't infer the zod-schema-to-TS-type mapping at build time without
// running a TS compiler — instead we emit a placeholder that uses
// `StandardSchemaV1`'s `InferOutput` helper. The user's TypeScript
// compiler resolves the inference at type-check time, the same way
// Astro does.
//
// File shape:
//
//     // Generated by @pyreon/zero-content. Do not edit.
//     import type { StandardSchemaV1 } from '@pyreon/zero-content/schema'
//     import type * as ContentConfig from '<absolute-or-relative-path>/content.config'
//
//     declare module '@pyreon/zero-content' {
//       interface CollectionSchemas {
//         docs: StandardSchemaV1.InferOutput<typeof ContentConfig.default.collections.docs.schema>
//         blog: StandardSchemaV1.InferOutput<typeof ContentConfig.default.collections.blog.schema>
//       }
//     }

export interface EmitTypesArgs {
  /** Absolute path to the user's `content.config.{ts,...}` file. */
  configFile: string
  /** Collection names discovered in the config. */
  collectionNames: string[]
  /** Vite root, used to compute the relative path to the config. */
  root: string
}

/**
 * Render the `.pyreon/content-types.d.ts` body. Pure — does not touch
 * the filesystem. The Vite plugin calls `writeContentTypes` instead.
 *
 * @internal exported for testing
 */
export function renderContentTypes(args: EmitTypesArgs): string {
  // Strip extension so the import works against the source file via
  // the bundler's module resolution.
  const rel = path
    .relative(path.join(args.root, '.pyreon'), args.configFile)
    .replace(/\\/g, '/')
  const importPath = rel.replace(/\.[^.]+$/, '')
  const entries = args.collectionNames
    .map(
      (name) =>
        `    ${JSON.stringify(name)}: StandardSchemaV1.InferOutput<typeof ContentConfig.default.collections[${JSON.stringify(name)}]["schema"]>`,
    )
    .join('\n')
  return `// Generated by @pyreon/zero-content. Do not edit.
import type { StandardSchemaV1 } from '@pyreon/zero-content/schema'
import type * as ContentConfig from ${JSON.stringify(importPath)}

declare module '@pyreon/zero-content' {
  interface CollectionSchemas {
${entries}
  }
}

export {}
`
}

/**
 * Write `<root>/.pyreon/content-types.d.ts`. Creates the `.pyreon/`
 * directory when missing. Idempotent — re-runs are safe.
 */
export async function writeContentTypes(args: EmitTypesArgs): Promise<string> {
  const outDir = path.join(args.root, '.pyreon')
  await fs.mkdir(outDir, { recursive: true })
  const outFile = path.join(outDir, 'content-types.d.ts')
  await fs.writeFile(outFile, renderContentTypes(args), 'utf8')
  return outFile
}
