/**
 * The generated reference pages.
 *
 * Two things are worth testing and one is not. The prose is not: asserting on
 * wording locks the emitter to a phrasing nobody chose deliberately.
 *
 * What IS worth holding: that the pages state the same REACH the CLI reports
 * (a page and a terminal that disagree about whether an operation runs on iOS
 * is worse than neither saying anything), and that spec-supplied text cannot
 * break the Markdown it lands in — the same escaping class as the block- and
 * line-comment escapes the code emitters carry, in a third syntax.
 */
import matter from 'gray-matter'
import { resolveConfig } from '../core/config'
import { generate } from '../core/generate'

const SPEC = `
openapi: 3.0.3
info: { title: Bookshelf, version: '1.2.0' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /books:
    get:
      operationId: listBooks
      tags: [books]
      summary: Every book.
      responses: { '200': { content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/Book' } } } } } }
    post:
      operationId: createBook
      tags: [books]
      requestBody: { content: { application/json: { schema: { $ref: '#/components/schemas/Book' } } } }
      responses: { '201': { content: { application/json: { schema: { $ref: '#/components/schemas/Book' } } } } }
  /books/{bookId}:
    get:
      operationId: getBook
      tags: [books]
      parameters: [{ name: bookId, in: path, required: true, schema: { type: string } }]
      responses: { '200': { content: { application/json: { schema: { $ref: '#/components/schemas/Book' } } } } }
components:
  schemas:
    Book: { type: object, required: [id], properties: { id: { type: string, format: uuid } } }
`

/** A spec whose text is hostile to every syntax it gets rendered into. */
const HOSTILE = `
openapi: 3.0.3
info: { title: 'A | B', version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /x:
    get:
      operationId: getX
      tags: [x]
      summary: "pipes | and\\nnewlines end the row"
      responses: { '200': { content: { application/json: { schema: { type: string } } } } }
`

function docsFor(spec: string, extra: Record<string, unknown> = {}): Map<string, string> {
  const cfg = resolveConfig({
    input: 'x',
    baseUrl: 'https://api.test/v1',
    plugins: ['schemas', 'client', 'queries', 'docs'],
    ...extra,
  })
  return new Map(
    generate(spec, cfg)
      .files.filter((f) => f.path.startsWith('docs/'))
      .map((f) => [f.path, f.contents]),
  )
}

/**
 * Split a Markdown table row into cells the way a RENDERER does.
 *
 * A regex lookbehind for a preceding backslash is NOT equivalent and shares the
 * exact bug these specs exist to catch: in `\\|` the pipe IS preceded by a
 * backslash, but that backslash is itself escaped, so the pipe is LIVE. Walking
 * the string and consuming `\X` as a pair is the only reading that agrees with
 * the renderer.
 */
function mdCells(row: string): string[] {
  const cells: string[] = []
  let current = ''
  for (let i = 0; i < row.length; i++) {
    const ch = row[i] as string
    if (ch === '\\' && i + 1 < row.length) {
      current += ch + (row[i + 1] as string)
      i++
      continue
    }
    if (ch === '|') {
      cells.push(current)
      current = ''
      continue
    }
    current += ch
  }
  cells.push(current)
  // A leading and trailing pipe produce an empty cell at each end.
  return cells.slice(1, -1)
}

describe('the generated reference pages', () => {
  const pages = docsFor(SPEC)

  it('emits an index, a page per tag, and the models', () => {
    expect([...pages.keys()].sort()).toEqual(['docs/books.md', 'docs/index.md', 'docs/models.md'])
  })

  it('marks every page as generated, invisibly when rendered', () => {
    for (const [path, body] of pages) {
      expect(body, path).toContain('<!-- @generated by @pyreon/lathe')
    }
  })

  it('opens with frontmatter, so the pages drop into a content collection', () => {
    for (const [path, body] of pages) {
      expect(body.startsWith('---\ntitle: "'), path).toBe(true)
    }
  })

  it('names the generated HOOK, not just the HTTP route', () => {
    // The whole reason these pages exist rather than a rendering of the spec:
    // the spec cannot tell you what the generated symbol is called.
    const books = pages.get('docs/books.md') ?? ''
    expect(books).toContain('useListBooks')
    expect(books).toContain("from './gen/queries/books'")
  })

  it('shows the endpoint call instead when no hooks were generated', () => {
    const noQueries = docsFor(SPEC, { plugins: ['schemas', 'client', 'docs'] })
    const books = noQueries.get('docs/books.md') ?? ''
    expect(books).toContain("from './gen/endpoints/books'")
    expect(books).not.toContain('useListBooks')
  })

  it('states the same reach the CLI reports, per operation', () => {
    const cfg = resolveConfig({
      input: 'x',
      baseUrl: 'https://api.test/v1',
      plugins: ['schemas', 'client', 'queries', 'docs'],
    })
    const result = generate(SPEC, cfg)
    const books = result.files.find((f) => f.path === 'docs/books.md')?.contents ?? ''
    // `getBook` is a GET and reaches native; `createBook` is a POST and does
    // not. Both come from the same analysis the terminal prints.
    expect(result.reach.get('getBook')?.reach).toBe('web+native')
    expect(result.reach.get('createBook')?.reach).toBe('web-only')
    expect(books).toContain('web · iOS · Android')
    expect(books).toContain('web only')
    // And the REASON travels with it, so the page answers "why not" too.
    expect(books).toContain('PMTC does not yet recognise')
  })

  it('names the base the CLIENT calls, not the spec default', () => {
    // A config `baseUrl` OVERRIDES `servers[0]`, and the reach analysis already
    // reads the override — so rendering the spec value would print a host the
    // client never contacts, beside a reach column decided from a different one.
    const overridden = docsFor(SPEC, { baseUrl: 'https://override.test/v2' })
    const index = overridden.get('docs/index.md') ?? ''
    expect(index).toContain('https://override.test/v2')
    expect(index).not.toContain('https://api.test/v1')
  })

  it('carries a path parameter into the usage snippet', () => {
    expect(pages.get('docs/books.md')).toContain("params: { bookId: '…' }")
  })

  it('emits nothing when the spec has no operations', () => {
    const empty = docsFor(`
openapi: 3.0.3
info: { title: E, version: '1' }
paths: {}
`)
    expect(empty.size).toBe(0)
  })
})

describe('spec text that is hostile to Markdown', () => {
  const pages = docsFor(HOSTILE)

  it('escapes a pipe so it cannot split a table cell', () => {
    const index = pages.get('docs/index.md') ?? ''
    // The title reaches a heading AND the YAML frontmatter.
    expect(index).toContain('# A | B')
    expect(index).toContain('title: "A | B"')
  })

  it('keeps a newline out of a table row', () => {
    const x = pages.get('docs/x.md') ?? ''
    // The summary is rendered as prose here, but the same escaping applies to
    // the note table; what must never happen is a raw newline inside a row.
    for (const line of x.split('\n')) {
      if (!line.startsWith('|')) continue
      expect(line.endsWith('|')).toBe(true)
    }
  })

  it('escapes a pipe in a TAG name, which lands in a table cell', () => {
    const piped = docsFor(`
openapi: 3.0.3
info: { title: P, version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /z:
    get: { operationId: getZ, tags: ['a | b'], responses: { '200': { content: { application/json: { schema: { type: string } } } } } }
`)
    const index = piped.get('docs/index.md') ?? ''
    // The tag-table rows are the only lines carrying a relative page link.
    const row = index.split('\n').find((l) => l.startsWith('| ') && l.includes('](./')) ?? ''
    expect(row).toContain('a \\| b')
    // Three cells, not four -- which is what a live pipe would make it.
    expect(mdCells(row)).toHaveLength(3)
  })

  it('escapes the BACKSLASH before the pipe, so a `\\|` cannot split a cell', () => {
    // Escaping only the pipe turns `\|` into `\\|`, which Markdown reads as an
    // escaped BACKSLASH followed by a LIVE pipe -- reopening the exact hole the
    // escape exists to close. Found by CodeQL (`js/incomplete-sanitization`).
    const nasty = docsFor(`
openapi: 3.0.3
info: { title: N, version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /w:
    get: { operationId: getW, tags: ['back\\| slash'], responses: { '200': { content: { application/json: { schema: { type: string } } } } } }
`)
    const index = nasty.get('docs/index.md') ?? ''
    const row = index.split('\n').find((l) => l.startsWith('| ') && l.includes('](./')) ?? ''
    expect(row).not.toBe('')
    // Exactly three cells: a LIVE pipe would make four.
    expect(mdCells(row)).toHaveLength(3)
  })

  /**
   * Front-matter is asserted by PARSING it, not by matching the string.
   *
   * The assertion here used to be a `toContain` on the doubled-quote spelling,
   * and it passed against an emitter producing a document gray-matter REJECTS.
   * Doubling is the CSV and single-quoted-YAML convention; inside double
   * quotes YAML escapes with a backslash, so the doubled form closes the
   * scalar and opens another. The test held the emitter to a spelling rather
   * than to a contract, which is how it locked the bug in.
   *
   * `gray-matter` is the parser `@pyreon/zero-content` actually reads these
   * pages with, so the oracle here is the real consumer instead of a re-typed
   * literal — the only reason the corrected escape can be trusted.
   */
  const frontmatterOf = (page: string): Record<string, unknown> =>
    matter(page).data as Record<string, unknown>

  it('emits frontmatter that survives a quote in the title', () => {
    const quoted = docsFor(`
openapi: 3.0.3
info: { title: 'He said "hi"', version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /y:
    get: { operationId: getY, tags: [y], responses: { '200': { content: { application/json: { schema: { type: string } } } } } }
`)
    const page = quoted.get('docs/index.md') ?? ''
    expect(page).not.toBe('')
    // Parses at all, and round-trips the quote rather than merely surviving.
    expect(frontmatterOf(page).title).toBe('He said "hi"')
  })

  it('emits frontmatter that survives a BACKSLASH in the title', () => {
    // The sibling a quote-only escape reopens: a backslash is itself live
    // inside a double-quoted scalar, so an unescaped trailing one swallows
    // the closing quote and the document ends mid-value.
    const backslashed = docsFor(`
openapi: 3.0.3
info: { title: 'a back\\slash', version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /y:
    get: { operationId: getY, tags: [y], responses: { '200': { content: { application/json: { schema: { type: string } } } } } }
`)
    const page = backslashed.get('docs/index.md') ?? ''
    expect(frontmatterOf(page).title).toBe('a back\\slash')
  })

  it('emits frontmatter that survives a COLON, the shape quoting exists for', () => {
    const colon = docsFor(`
openapi: 3.0.3
info: { title: 'Books: the API', version: '1' }
servers: [{ url: 'https://api.test/v1' }]
paths:
  /y:
    get: { operationId: getY, tags: [y], responses: { '200': { content: { application/json: { schema: { type: string } } } } } }
`)
    const page = colon.get('docs/index.md') ?? ''
    expect(frontmatterOf(page).title).toBe('Books: the API')
  })
})
