/**
 * `lathe init`, run through the bin's `main` against real configs of each
 * generator Lathe migrates from.
 *
 * The fixtures under `fixtures/init/` are shaped the way those tools document
 * their configs (they carry a `.fixture` suffix so this package's typecheck
 * and lint do not try to resolve `orval` / `@kubb/*`). Each case copies one
 * into a fresh directory, runs `lathe init --yes`, and asserts on the files
 * that come out: the written config, the package.json scripts, and a client
 * the first generate actually produced.
 */
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { main } from '../cli/main'
import { amendConfig, createConfig, hasLatheSection, requiredPackages, withScripts } from '../cli/init'
import { readExportedConfig, show } from '../cli/init/literal'
import { fromKubb, fromOrval } from '../cli/init/migrate'
import { parseArgv } from '../cli/run'

const HERE = dirname(fileURLToPath(import.meta.url))
const FIXTURES = join(HERE, 'fixtures', 'init')
const PETSTORE = readFileSync(join(HERE, 'fixtures', 'petstore3.json'), 'utf8')

/** A fresh project from a fixture, `.fixture` suffixes stripped, with the petstore spec. */
function project(name: string, specAt = 'petstore.json'): string {
  const root = mkdtempSync(join(tmpdir(), `lathe-init-${name}-`))
  mkdirSync(join(root, '.git'))
  cpSync(join(FIXTURES, name), root, { recursive: true })
  const unsuffix = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry)
      if (statSync(full).isDirectory()) unsuffix(full)
      else if (entry.endsWith('.fixture')) renameSync(full, full.slice(0, -'.fixture'.length))
    }
  }
  unsuffix(root)
  if (specAt) {
    mkdirSync(dirname(join(root, specAt)), { recursive: true })
    writeFileSync(join(root, specAt), PETSTORE)
  }
  return root
}

async function capture(fn: () => Promise<number>): Promise<{ code: number; out: string; err: string }> {
  const out: string[] = []
  const err: string[] = []
  const o = process.stdout.write.bind(process.stdout)
  const e = process.stderr.write.bind(process.stderr)
  process.stdout.write = ((s: string) => (out.push(String(s)), true)) as typeof process.stdout.write
  process.stderr.write = ((s: string) => (err.push(String(s)), true)) as typeof process.stderr.write
  try {
    const code = await fn()
    return { code, out: out.join(''), err: err.join('') }
  } finally {
    process.stdout.write = o
    process.stderr.write = e
  }
}

const read = (root: string, path: string): string => readFileSync(join(root, path), 'utf8')
const scripts = (root: string): Record<string, string> =>
  (JSON.parse(read(root, 'package.json')) as { scripts?: Record<string, string> }).scripts ?? {}

/** Import the written config back, the way `lathe generate` will. */
async function writtenSection(root: string): Promise<Record<string, unknown>> {
  const mod = (await import(`${join(root, 'pyreon.config.ts')}?t=${Date.now()}`)) as { default: { lathe: Record<string, unknown> } }
  return mod.default.lathe
}

describe('lathe init — from orval', { timeout: 60_000 }, () => {
  it('maps input, hooks, mocks, client and base URL; reports the mutator; writes a client', async () => {
    const root = project('orval')
    const r = await capture(() => main(['init', '--yes', '--no-color'], root))
    expect(r.code, r.err + r.out).toBe(0)

    const lathe = await writtenSection(root)
    expect(lathe).toMatchObject({
      input: './petstore.json',
      client: 'fetch',
      baseUrl: 'https://petstore3.swagger.io/api/v3',
      plugins: ['schemas', 'client', 'queries', 'mocks', 'faker'],
    })
    // `src/api` still holds orval's output, so Lathe writes beside it.
    expect(lathe.output).toBe('./src/gen')
    expect(r.out).toContain('src/api holds orval')
    expect(read(root, 'src/api/petstore.ts')).toContain('generated by orval')

    // What could not be mapped is NAMED, with what to do instead.
    expect(r.out).toContain('petstore.output.override.mutator')
    expect(r.out).toContain('configureApi({ use: [yourMiddleware], headers })')
    expect(r.out).toContain('petstore.hooks')
    expect(r.out).toContain('petstore.output.prettier')

    expect(scripts(root)).toMatchObject({ api: 'orval', 'lathe:generate': 'lathe generate', 'lathe:check': 'lathe check' })
    expect(r.out).toContain('these scripts still run the old generator: api')
    expect(r.out).toMatch(/install {2}npm install @pyreon\/http @pyreon\/query @pyreon\/validate && npm install -D @faker-js\/faker @pyreon\/lathe/)

    // The first generate ran.
    expect(existsSync(join(root, 'src/gen/queries/pet.ts'))).toBe(true)
    expect(existsSync(join(root, 'src/gen/mocks.ts'))).toBe(true)
  })

  it('several APIs become `projects`, a URL input becomes `source`', () => {
    const cfg = readExportedConfig(read(project('orval-multi', ''), 'orval.config.ts'))
    expect(cfg).toBeDefined()
    const [remote, zod] = fromOrval(cfg!, 'orval.config.ts')
    expect(remote?.name).toBe('petstore')
    expect(remote?.section).toMatchObject({
      source: 'https://petstore3.swagger.io/api/v3/openapi.json',
      input: './openapi.json',
      output: './src/petstore',
      client: 'axios',
    })
    expect(zod?.section).toMatchObject({ input: './petstore.json', validator: 'zod', output: './src/zod' })
    expect(zod?.unmapped.map((u) => u.from)).toEqual(['petstoreZod.input.filters', 'petstoreZod.output....'])
  })
})

describe('lathe init — from @hey-api/openapi-ts', { timeout: 60_000 }, () => {
  it('maps plugins to client, queries and zod; keeps tab indentation in package.json', async () => {
    const root = project('hey-api')
    const r = await capture(() => main(['init', '--yes', '--no-color'], root))
    expect(r.code, r.err + r.out).toBe(0)
    expect(await writtenSection(root)).toMatchObject({ input: './petstore.json', output: 'src/client', validator: 'zod' })
    expect(r.out).toContain('output.format')
    expect(r.out).toContain('plugins[6]: "fastify"')
    expect(read(root, 'package.json')).toContain('\n\t"scripts": {')
    expect(existsSync(join(root, 'src/client/queries/pet.ts'))).toBe(true)
  })
})

describe('lathe init — from kubb', { timeout: 60_000 }, () => {
  it('reads the object a defineConfig FUNCTION returns, and maps its plugin calls', async () => {
    const root = project('kubb')
    const r = await capture(() => main(['init', '--yes', '--no-generate', '--no-color'], root))
    expect(r.code, r.err + r.out).toBe(0)
    expect(await writtenSection(root)).toMatchObject({
      input: './petstore.json',
      client: 'axios',
      validator: 'zod',
      baseUrl: 'https://petstore3.swagger.io/api/v3',
      plugins: ['schemas', 'client', 'queries', 'mocks', 'faker'],
    })
    // `./src/gen` is empty here, so kubb's own output path is kept.
    expect((await writtenSection(root)).output).toBe('./src/gen')
    const [m] = fromKubb(readExportedConfig(read(root, 'kubb.config.ts'))!, 'kubb.config.ts')
    expect(m?.unmapped.map((u) => u.from)).toEqual([
      'plugins[2] pluginClient.dataReturnType',
      'plugins[3] pluginReactQuery.suspense',
    ])
    expect(scripts(root)).toMatchObject({ generate: 'kubb generate', 'lathe:generate': 'lathe generate' })
  })

  it('a config it cannot read names the file and the way out, and writes nothing', async () => {
    const root = project('kubb')
    writeFileSync(join(root, 'kubb.config.ts'), "import { build } from './build'\nexport default build(process.env)\n")
    const r = await capture(() => main(['init', '--yes', '--no-color'], root))
    expect(r.code).toBe(1)
    expect(r.err).toContain('could not read kubb.config.ts')
    expect(r.err).toContain('lathe init ./openapi.yaml')
    expect(existsSync(join(root, 'pyreon.config.ts'))).toBe(false)
  })
})

describe('lathe init — from openapi-typescript', { timeout: 60_000 }, () => {
  it('reads the CLI script; openapi-fetch + openapi-react-query select client and hooks', async () => {
    const root = project('openapi-typescript')
    const r = await capture(() => main(['init', '--yes', '--no-color'], root))
    expect(r.code, r.err + r.out).toBe(0)
    const lathe = await writtenSection(root)
    expect(lathe).toMatchObject({ input: './petstore.json', output: './src/lib/api' })
    expect(lathe.plugins).toBeUndefined() // the default set: schemas, client, queries
    expect(existsSync(join(root, 'src/lib/api/client.ts'))).toBe(true)
  })
})

describe('lathe init — from a bare spec', { timeout: 60_000 }, () => {
  it('finds api/openapi.json, and --dry-run writes nothing', async () => {
    const root = project('bare', 'api/openapi.json')
    const r = await capture(() => main(['init', '--yes', '--dry-run', '--no-color'], root))
    expect(r.code, r.err).toBe(0)
    expect(r.out).toContain('from an OpenAPI document (api/openapi.json)')
    expect(r.out).toContain('dry run: nothing was written.')
    expect(existsSync(join(root, 'pyreon.config.ts'))).toBe(false)
    expect(scripts(root)).toEqual({})
  })

  it('`--json` is one document, with the first generate inside it', async () => {
    const root = project('bare', 'api/openapi.json')
    const r = await capture(() => main(['init', '--yes', '--json'], root))
    expect(r.code, r.err).toBe(0)
    const doc = JSON.parse(r.out) as { ok: boolean; command: string; section: { input: string }; generated: { ok: boolean } }
    expect(doc).toMatchObject({ ok: true, command: 'init', section: { input: './api/openapi.json' }, generated: { ok: true } })
  })

  it('with nothing to find, and no one to ask, it says what to pass', async () => {
    const root = project('bare', '')
    const r = await capture(() => main(['init', '--yes'], root))
    expect(r.code).toBe(1)
    expect(r.err).toContain('lathe init ./openapi.yaml')
  })
})

describe('lathe init — an existing pyreon.config.ts', { timeout: 60_000 }, () => {
  it('adds `lathe` to it, keeps everything else, and keeps a script the user already has', async () => {
    const root = project('amend')
    const before = read(root, 'pyreon.config.ts')
    const r = await capture(() => main(['init', './petstore.json', '--yes', '--no-generate', '--no-color'], root))
    expect(r.code, r.err + r.out).toBe(0)
    const after = read(root, 'pyreon.config.ts')
    expect(after).toContain("atlas: {\n    title: 'My app',\n  },")
    expect(after).toContain("import { defineConfig } from '@pyreon/config'")
    // Exactly one entry inserted; every other byte as it was.
    expect(after).toBe(before.replace('defineConfig({', "defineConfig({\n  lathe: { input: './petstore.json', output: './src/gen' },"))
    expect(scripts(root)['lathe:generate']).toBe('lathe generate --target multiplatform')
    expect(r.out).toContain('kept your own lathe:generate')
  })

  it('never replaces a lathe section that is already there', async () => {
    const root = project('amend')
    writeFileSync(join(root, 'pyreon.config.ts'), "export default { lathe: { input: './mine.yaml' } }\n")
    const r = await capture(() => main(['init', './petstore.json', '--yes'], root))
    expect(r.code).toBe(1)
    expect(r.err).toContain('already has a `lathe` section')
    expect(read(root, 'pyreon.config.ts')).toBe("export default { lathe: { input: './mine.yaml' } }\n")
  })
})

describe('init building blocks', () => {
  it('the literal reader keeps what it cannot evaluate as text', () => {
    const cfg = readExportedConfig(`
      // comment with a { brace
      export default {
        input: \`./spec.yaml\`,
        target: process.env.TARGET ?? 'web',
        list: [1, 'two', true, null],
        fn: plugin({ a: 1 }),
        tpl: \`\${x}/y\`,
      } satisfies Config
    `)
    expect(show(cfg!)).toBe(
      '{ input: "./spec.yaml", target: process.env.TARGET ?? \'web\', list: [1, "two", true, null], fn: plugin({ a: 1 }), tpl: `${x}/y` }',
    )
  })

  it('follows `export default config` to its declaration', () => {
    expect(show(readExportedConfig("const config = { a: 'b' }\nexport default config")!)).toBe('{ a: "b" }')
  })

  it('amends only the exported object, or refuses', () => {
    expect(amendConfig('export default {}\n', { input: './a.yaml' })).toBe("export default {\n  lathe: { input: './a.yaml' },\n}\n")
    expect(amendConfig('const c = {}\nexport default c\n', { input: './a.yaml' })).toBeUndefined()
    expect(hasLatheSection("export default { 'lathe': {} }")).toBe(true)
    expect(hasLatheSection('export default { /* lathe: later */ atlas: {} }')).toBe(false)
  })

  it('writes a config that loads', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'lathe-init-create-'))
    writeFileSync(join(dir, 'pyreon.config.ts'), createConfig({ input: './a.yaml', plugins: ['schemas'] }))
    expect(await writtenSection(dir)).toEqual({ input: './a.yaml', plugins: ['schemas'] })
  })

  it('keeps package.json formatting', () => {
    expect(withScripts('{\n    "name": "x"\n}\n', { a: 'b' })).toBe('{\n    "name": "x",\n    "scripts": {\n        "a": "b"\n    }\n}\n')
  })

  it('lists the packages the generated code imports', () => {
    expect(requiredPackages({ input: 'x' })).toEqual({ runtime: ['@pyreon/http', '@pyreon/query', '@pyreon/validate'], dev: ['@pyreon/lathe'] })
    expect(requiredPackages({ input: 'x', client: 'axios', validator: 'zod', plugins: ['schemas', 'client'] }).runtime).toEqual([
      '@pyreon/http',
      'axios',
      'zod',
    ])
  })

  it('parses its flags, and refuses them on other commands', () => {
    expect(parseArgv(['init', './a.yaml', '--from', 'orval', '-y', '--no-generate'])).toMatchObject({
      command: 'init',
      input: './a.yaml',
      from: 'orval',
      yes: true,
      noGenerate: true,
      errors: [],
    })
    expect(parseArgv(['init', '--from', 'orvel']).errors[0]).toContain('Did you mean `orval`?')
    expect(parseArgv(['generate', '--yes']).errors).toEqual(['`--from`, `--yes` and `--no-generate` only apply to `lathe init`.'])
  })
})
