/**
 * The public plugin API (`definePlugin`).
 *
 * Every property the module docblock promises is asserted here against the
 * real pipeline: plugin files are ordinary output (banner, manifest, marker,
 * `check`, pruning), errors name the plugin, the document is immutable, and
 * a non-deterministic plugin is refused instead of turning `lathe check` red
 * on every machine but the one that generated.
 */
import { resolveConfig, type LatheSection } from '../core/config'
import { generate } from '../core/generate'
import type { IrDocument } from '../core/ir'
import { definePlugin, isLathePlugin, type LathePlugin } from '../core/plugin'
import { SourceFile } from '../emit/writer'
import { run, parseArgv, type Fs } from '../cli/run'
import { CUSTOMIZE_SPEC } from './helpers/customize-spec'

const gen = (section: Omit<LatheSection, 'input'> = {}) =>
  generate(CUSTOMIZE_SPEC, resolveConfig({ input: 'spec.json', ...section }))

const file = (r: ReturnType<typeof gen>, path: string): string | undefined =>
  r.files.find((f) => f.path === path)?.contents

/** One `export const <op>Path = '…'` per operation — the docs example. */
const pathTable = definePlugin({
  name: 'path-table',
  emit({ doc }) {
    const f = new SourceFile('extras/paths.ts')
    for (const op of doc.operations) f.line(`export const ${op.id}Path = ${JSON.stringify(op.path)}`)
    return [f]
  },
})

describe('definePlugin', () => {
  it('returns the plugin, branded, and rejects a malformed one at definition', () => {
    expect(isLathePlugin(pathTable)).toBe(true)
    expect(isLathePlugin({ name: 'plain', emit: () => [] })).toBe(false)
    // A typo'd hook would otherwise never run, silently.
    expect(() => definePlugin({ name: 'x', transform: () => undefined } as unknown as LathePlugin)).toThrow(
      /unknown key `transform`/,
    )
    expect(() => definePlugin({ name: '' })).toThrow(/non-empty `name`/)
    expect(() => definePlugin({ name: 'x', emit: 'nope' } as unknown as LathePlugin)).toThrow(/`emit` must be a function/)
  })

  it('the config refuses a plain object, a built-in name, and a duplicate name', () => {
    expect(() => resolveConfig({ input: 'x', plugins: [{ name: 'p' } as unknown as LathePlugin] })).toThrow(/definePlugin/)
    expect(() => resolveConfig({ input: 'x', plugins: [definePlugin({ name: 'mocks' })] })).toThrow(/name of a built-in/)
    expect(() => resolveConfig({ input: 'x', plugins: [definePlugin({ name: 'a' }), definePlugin({ name: 'a' })] })).toThrow(
      /two plugins are named `a`/,
    )
  })
})

describe('emit', () => {
  it('writes the plugin file with the standard banner, listed in the manifest', () => {
    const r = gen({ plugins: ['schemas', 'client', pathTable] })
    const paths = file(r, 'extras/paths.ts')
    expect(paths).toContain('// @generated by @pyreon/lathe')
    expect(paths).toContain('export const getPetByIdPath = "/pets/:petId"')
    expect(JSON.parse(file(r, 'lathe-manifest.json') as string).files).toContain('extras/paths.ts')
  })

  it('regenerates byte-identically, plugin output included', () => {
    const a = gen({ plugins: ['schemas', 'client', 'queries', pathTable] })
    const b = gen({ plugins: ['schemas', 'client', 'queries', pathTable] })
    expect(a.files).toEqual(b.files)
  })

  it('REFUSES a non-deterministic emit, naming the plugin', () => {
    let n = 0
    const stamped = definePlugin({
      name: 'stamped',
      emit: () => [{ path: 'stamp.txt', contents: `generated run ${n++}` }],
    })
    expect(() => gen({ plugins: ['schemas', stamped] })).toThrow(
      /plugin `stamped`: `emit` produced different files for the same input/,
    )
  })

  it('the order a plugin returns files in cannot move anything', () => {
    let flip = false
    const unordered = definePlugin({
      name: 'unordered',
      emit: () => {
        flip = !flip
        const files = [
          { path: 'u/a.txt', contents: 'a' },
          { path: 'u/b.txt', contents: 'b' },
        ]
        return flip ? files : files.reverse()
      },
    })
    const paths = gen({ plugins: ['schemas', unordered] }).files.map((f) => f.path)
    expect(paths.indexOf('u/a.txt')).toBeLessThan(paths.indexOf('u/b.txt'))
  })

  it('attributes a throw to the plugin and the hook', () => {
    const broken = definePlugin({
      name: 'broken-emitter',
      emit: () => {
        throw new Error('no template for PetPage')
      },
    })
    expect(() => gen({ plugins: ['schemas', broken] })).toThrow(
      '[Pyreon] lathe: plugin `broken-emitter` failed in `emit`: no template for PetPage',
    )
  })

  it('refuses a path a built-in emits, a bookkeeping path, and a path outside the output', () => {
    const at = (path: string) => definePlugin({ name: 'clash', emit: () => [{ path, contents: 'x' }] })
    expect(() => gen({ plugins: ['schemas', 'client', at('client.ts')] })).toThrow(/`client.ts`, which the built-in emitters already emit/)
    // Case-insensitive: one file on macOS and Windows.
    expect(() => gen({ plugins: ['schemas', 'client', at('CLIENT.ts')] })).toThrow(/already emit/)
    expect(() => gen({ plugins: ['schemas', at('api-surface.json')] })).toThrow(/which Lathe itself writes/)
    expect(() => gen({ plugins: ['schemas', at('../outside.ts')] })).toThrow(/not a relative path inside the output/)
  })

  it('a `sideEffects: true` file is listed in the emitted package.json marker', () => {
    const sw = definePlugin({
      name: 'sw',
      emit: () => [{ path: 'sw-register.ts', contents: 'navigator.serviceWorker.register("/sw.js")\n', sideEffects: true }],
    })
    const marker = JSON.parse(file(gen({ plugins: ['schemas', sw] }), 'package.json') as string)
    expect(marker.sideEffects).toEqual(['./sw-register.ts'])
    expect(JSON.parse(file(gen({ plugins: ['schemas'] }), 'package.json') as string).sideEffects).toBe(false)
  })

  it('`requires` turns on the built-ins the plugin imports from', () => {
    const needsQueries = definePlugin({ name: 'needs-queries', requires: ['queries'] })
    const cfg = resolveConfig({ input: 'x', plugins: ['schemas', needsQueries] })
    expect(cfg.plugins).toEqual(expect.arrayContaining(['schemas', 'client', 'queries']))
    expect(() => resolveConfig({ input: 'x', plugins: [definePlugin({ name: 'z', requires: ['nope' as never] })] })).toThrow(
      /requires `nope`/,
    )
  })

  it('sees the built-in output and the reach analysis', () => {
    let seen: string[] = []
    let reach: string | undefined
    const reader = definePlugin({
      name: 'reader',
      emit: (ctx) => {
        seen = ctx.files.map((f) => f.path)
        reach = ctx.reach.get('deleteUser')?.reach
        return []
      },
    })
    gen({ plugins: ['schemas', 'client', reader] })
    expect(seen).toContain('client.ts')
    expect(reach).toBe('web-only')
  })
})

describe('transformDocument', () => {
  const summaries = definePlugin({
    name: 'summaries',
    transformDocument: (doc) => ({
      ...doc,
      operations: doc.operations.map((op) => ({ ...op, summary: op.summary ?? `The ${op.id} operation.` })),
    }),
  })

  it('rewrites the document every emitter reads', () => {
    const r = gen({ plugins: ['schemas', 'client', summaries] })
    expect(file(r, 'endpoints/users.ts')).toContain('The deleteUser operation.')
  })

  it('REFUSES an in-place mutation, and says to return a copy', () => {
    const mutator = definePlugin({
      name: 'mutator',
      transformDocument: (doc) => {
        ;(doc.operations as IrDocument['operations'][number][]).pop()
        return doc
      },
    })
    expect(() => gen({ plugins: ['schemas', mutator] })).toThrow(
      /plugin `mutator` failed in `transformDocument`: .*return a modified copy/,
    )
  })

  it('REFUSES a non-deterministic transform', () => {
    let n = 0
    const counter = definePlugin({
      name: 'counter',
      transformDocument: (doc) => ({ ...doc, title: `${doc.title} #${n++}` }),
    })
    expect(() => gen({ plugins: ['schemas', counter] })).toThrow(/`transformDocument` returned different documents/)
  })

  it('REFUSES a document whose model references dangle, naming the plugin', () => {
    const halfRename = definePlugin({
      name: 'half-rename',
      transformDocument: (doc) => ({ ...doc, models: doc.models.map((m) => (m.name === 'Pet' ? { ...m, name: 'Animal' } : m)) }),
    })
    expect(() => gen({ plugins: ['schemas', halfRename] })).toThrow(
      /plugin `half-rename` returned an invalid document: it references model\(s\) that do not exist: Pet/,
    )
  })

  it('reports a note through ctx.note — code `plugin`, attributed', () => {
    const noter = definePlugin({
      name: 'noter',
      transformDocument: (_doc, ctx) => {
        ctx.note('could not map `Unused`', '#/components/schemas/Unused')
      },
    })
    const notes = gen({ plugins: ['schemas', noter] }).doc.notes.filter((n) => n.code === 'plugin')
    expect(notes).toEqual([{ code: 'plugin', message: '[noter] could not map `Unused`', at: '#/components/schemas/Unused' }])
    // Quiet when no plugin reports anything.
    expect(gen({ plugins: ['schemas', summaries] }).doc.notes.some((n) => n.code === 'plugin')).toBe(false)
  })

  it('runs in declaration order, each seeing the previous one\'s result', () => {
    const order: string[] = []
    const first = definePlugin({ name: 'first', transformDocument: (doc) => ({ ...doc, title: 'A' }) })
    const second = definePlugin({
      name: 'second',
      transformDocument: (doc) => {
        order.push(doc.title)
      },
    })
    gen({ plugins: ['schemas', first, second] })
    expect(order[0]).toBe('A')
  })

  it('setup runs once per project with the resolved config, and can refuse it', () => {
    const picky = definePlugin({
      name: 'picky',
      setup: ({ config }) => {
        if (config.target !== 'multiplatform') throw new Error('needs target: multiplatform')
      },
    })
    expect(() => gen({ plugins: ['schemas', picky] })).toThrow('plugin `picky` failed in `setup`: needs target: multiplatform')
  })
})

describe('plugins participate in `lathe check` and pruning', () => {
  function memFs(): Fs & { files: Record<string, string> } {
    const files: Record<string, string> = { 'spec.json': CUSTOMIZE_SPEC }
    return {
      files,
      read: (p) => {
        const v = files[p]
        if (v === undefined) throw new Error(`ENOENT ${p}`)
        return v
      },
      write: (p, c) => {
        files[p] = c
      },
      exists: (p) => p in files,
      mkdirp: () => undefined,
      remove: (p) => {
        delete files[p]
      },
      join: (...parts) => parts.join('/').replace(/\/+/g, '/'),
    }
  }

  it('check passes after generate, fails on a hand-edited plugin file, and a dropped plugin prunes its file', async () => {
    const fs = memFs()
    const section: LatheSection = { input: 'spec.json', output: 'gen', plugins: ['schemas', pathTable] }
    expect((await run(parseArgv(['generate']), section, fs)).code).toBe(0)
    expect(fs.files['gen/extras/paths.ts']).toBeDefined()
    expect((await run(parseArgv(['check']), section, fs)).code).toBe(0)

    fs.files['gen/extras/paths.ts'] = '// edited'
    const stale = await run(parseArgv(['check']), section, fs)
    expect(stale.code).toBe(1)
    expect(stale.stdout).toContain('extras/paths.ts')

    expect((await run(parseArgv(['generate']), { ...section, plugins: ['schemas'] }, fs)).code).toBe(0)
    expect(fs.files['gen/extras/paths.ts']).toBeUndefined()
  })
})
